/**
 * Real-world P2P payment rails (mirrors supabase migration).
 * Used as fallback / merge so the picker is rich even before SQL is applied.
 */

export type P2pPaymentMethodSeed = {
  code: string;
  name: string;
  icon: string;
  region: string;
  keywords: string;
  sort_order: number;
};

export const P2P_PAYMENT_METHOD_CATALOG: P2pPaymentMethodSeed[] = [
  { code: "openpay", name: "OpenPay Balance", icon: "◎", region: "Popular", keywords: "balance openpay pro", sort_order: 5 },
  { code: "bank_transfer", name: "Bank Transfer", icon: "🏦", region: "Global", keywords: "bank wire local deposit iban", sort_order: 10 },
  { code: "paypal", name: "PayPal", icon: "🅿️", region: "Global", keywords: "xoom paypal", sort_order: 20 },
  { code: "wise", name: "Wise", icon: "🌍", region: "Global", keywords: "transferwise", sort_order: 30 },
  { code: "payoneer", name: "Payoneer", icon: "💳", region: "Global", keywords: "payoneer card", sort_order: 40 },
  { code: "skrill", name: "Skrill", icon: "💜", region: "Global", keywords: "moneybookers", sort_order: 50 },
  { code: "neteller", name: "Neteller", icon: "💚", region: "Global", keywords: "paysafe", sort_order: 60 },
  { code: "western_union", name: "Western Union", icon: "🟡", region: "Global", keywords: "wu remittance", sort_order: 70 },
  { code: "moneygram", name: "MoneyGram", icon: "🔴", region: "Global", keywords: "remittance", sort_order: 80 },
  { code: "remitly", name: "Remitly", icon: "🔵", region: "Global", keywords: "remittance", sort_order: 90 },
  { code: "worldremit", name: "WorldRemit", icon: "🌐", region: "Global", keywords: "remittance", sort_order: 100 },
  { code: "swift", name: "SWIFT / Wire", icon: "✈️", region: "Global", keywords: "international wire bic", sort_order: 110 },
  { code: "sepa", name: "SEPA Transfer", icon: "🇪🇺", region: "Europe", keywords: "iban euro sepa", sort_order: 120 },
  { code: "cash_in_person", name: "Cash in Person", icon: "💵", region: "Global", keywords: "cash meetup face to face", sort_order: 130 },

  { code: "zelle", name: "Zelle", icon: "🟪", region: "Americas", keywords: "usa bank zelle", sort_order: 200 },
  { code: "cash_app", name: "Cash App", icon: "🟩", region: "Americas", keywords: "cashapp square usa", sort_order: 210 },
  { code: "venmo", name: "Venmo", icon: "🔵", region: "Americas", keywords: "paypal venmo usa", sort_order: 220 },
  { code: "chime", name: "Chime", icon: "🟢", region: "Americas", keywords: "usa neobank", sort_order: 230 },
  { code: "interac", name: "Interac e-Transfer", icon: "🍁", region: "Americas", keywords: "canada etransfer", sort_order: 240 },
  { code: "pix", name: "PIX", icon: "🇧🇷", region: "Americas", keywords: "brazil instant pix", sort_order: 250 },
  { code: "picpay", name: "PicPay", icon: "🟢", region: "Americas", keywords: "brazil", sort_order: 260 },
  { code: "mercado_pago", name: "Mercado Pago", icon: "💙", region: "Americas", keywords: "latam mercadopago", sort_order: 270 },
  { code: "spei", name: "SPEI", icon: "🇲🇽", region: "Americas", keywords: "mexico bank spei", sort_order: 280 },
  { code: "oxxo", name: "OXXO", icon: "🟠", region: "Americas", keywords: "mexico cash", sort_order: 290 },
  { code: "nequi", name: "Nequi", icon: "🟣", region: "Americas", keywords: "colombia", sort_order: 300 },
  { code: "daviplata", name: "Daviplata", icon: "🔴", region: "Americas", keywords: "colombia davivienda", sort_order: 310 },
  { code: "yape", name: "Yape", icon: "💜", region: "Americas", keywords: "peru bcp", sort_order: 320 },
  { code: "plin", name: "Plin", icon: "🔵", region: "Americas", keywords: "peru", sort_order: 330 },
  { code: "banco_inter", name: "Banco Inter", icon: "🧡", region: "Americas", keywords: "brazil", sort_order: 340 },
  { code: "uala", name: "Ualá", icon: "🩵", region: "Americas", keywords: "argentina mexico", sort_order: 350 },
  { code: "pago_movil", name: "Pago Móvil", icon: "🇻🇪", region: "Americas", keywords: "venezuela", sort_order: 360 },

  { code: "revolut", name: "Revolut", icon: "⚡", region: "Europe", keywords: "eu uk revolut", sort_order: 400 },
  { code: "bizum", name: "Bizum", icon: "🇪🇸", region: "Europe", keywords: "spain", sort_order: 410 },
  { code: "blik", name: "BLIK", icon: "🇵🇱", region: "Europe", keywords: "poland", sort_order: 420 },
  { code: "multibanco", name: "Multibanco", icon: "🇵🇹", region: "Europe", keywords: "portugal", sort_order: 430 },
  { code: "mb_way", name: "MB Way", icon: "🇵🇹", region: "Europe", keywords: "portugal mbway", sort_order: 440 },
  { code: "swish", name: "Swish", icon: "🇸🇪", region: "Europe", keywords: "sweden", sort_order: 450 },
  { code: "vipps", name: "Vipps", icon: "🇳🇴", region: "Europe", keywords: "norway", sort_order: 460 },
  { code: "mobilepay", name: "MobilePay", icon: "🇩🇰", region: "Europe", keywords: "denmark finland", sort_order: 470 },
  { code: "twint", name: "TWINT", icon: "🇨🇭", region: "Europe", keywords: "switzerland", sort_order: 480 },
  { code: "ideal", name: "iDEAL", icon: "🇳🇱", region: "Europe", keywords: "netherlands", sort_order: 490 },
  { code: "bancontact", name: "Bancontact", icon: "🇧🇪", region: "Europe", keywords: "belgium", sort_order: 500 },
  { code: "giropay", name: "Giropay", icon: "🇩🇪", region: "Europe", keywords: "germany", sort_order: 510 },
  { code: "sofort", name: "Sofort / Klarna", icon: "🩷", region: "Europe", keywords: "klarna sofort", sort_order: 520 },
  { code: "paysafecard", name: "Paysafecard", icon: "🎫", region: "Europe", keywords: "voucher", sort_order: 530 },
  { code: "fps_uk", name: "Faster Payments (UK)", icon: "🇬🇧", region: "Europe", keywords: "uk fps bank", sort_order: 540 },

  { code: "gcash", name: "GCash", icon: "💙", region: "Asia", keywords: "philippines glife", sort_order: 600 },
  { code: "maya", name: "Maya", icon: "💚", region: "Asia", keywords: "philippines paymaya", sort_order: 610 },
  { code: "grabpay", name: "GrabPay", icon: "🟢", region: "Asia", keywords: "sea grab", sort_order: 620 },
  { code: "shopeepay", name: "ShopeePay", icon: "🧡", region: "Asia", keywords: "sea shopee", sort_order: 630 },
  { code: "gopay", name: "GoPay", icon: "🟢", region: "Asia", keywords: "indonesia gojek", sort_order: 640 },
  { code: "ovo", name: "OVO", icon: "💜", region: "Asia", keywords: "indonesia", sort_order: 650 },
  { code: "dana", name: "DANA", icon: "🔵", region: "Asia", keywords: "indonesia", sort_order: 660 },
  { code: "linkaja", name: "LinkAja", icon: "🔴", region: "Asia", keywords: "indonesia", sort_order: 670 },
  { code: "qris", name: "QRIS", icon: "🇮🇩", region: "Asia", keywords: "indonesia qris", sort_order: 680 },
  { code: "promptpay", name: "PromptPay", icon: "🇹🇭", region: "Asia", keywords: "thailand", sort_order: 690 },
  { code: "true_money", name: "TrueMoney", icon: "🟠", region: "Asia", keywords: "thailand", sort_order: 700 },
  { code: "momo", name: "MoMo", icon: "🩷", region: "Asia", keywords: "vietnam", sort_order: 710 },
  { code: "zalopay", name: "ZaloPay", icon: "🔵", region: "Asia", keywords: "vietnam", sort_order: 720 },
  { code: "viettel_money", name: "Viettel Money", icon: "🔴", region: "Asia", keywords: "vietnam", sort_order: 730 },
  { code: "touch_n_go", name: "Touch 'n Go", icon: "🇲🇾", region: "Asia", keywords: "malaysia tng", sort_order: 740 },
  { code: "boost", name: "Boost", icon: "🔴", region: "Asia", keywords: "malaysia", sort_order: 750 },
  { code: "fpx", name: "FPX", icon: "🇲🇾", region: "Asia", keywords: "malaysia bank", sort_order: 760 },
  { code: "paynow", name: "PayNow", icon: "🇸🇬", region: "Asia", keywords: "singapore", sort_order: 770 },
  { code: "paylah", name: "PayLah!", icon: "🇸🇬", region: "Asia", keywords: "dbs singapore", sort_order: 780 },

  { code: "upi", name: "UPI", icon: "🇮🇳", region: "Asia", keywords: "india upi gpay phonepe", sort_order: 800 },
  { code: "paytm", name: "Paytm", icon: "🔵", region: "Asia", keywords: "india", sort_order: 810 },
  { code: "phonepe", name: "PhonePe", icon: "💜", region: "Asia", keywords: "india", sort_order: 820 },
  { code: "google_pay_in", name: "Google Pay (India)", icon: "🌈", region: "Asia", keywords: "gpay tez india", sort_order: 830 },
  { code: "imps", name: "IMPS", icon: "🇮🇳", region: "Asia", keywords: "india bank instant", sort_order: 840 },
  { code: "neft", name: "NEFT / RTGS", icon: "🏦", region: "Asia", keywords: "india bank", sort_order: 850 },
  { code: "alipay", name: "Alipay", icon: "🩵", region: "Asia", keywords: "china alipay", sort_order: 860 },
  { code: "wechat_pay", name: "WeChat Pay", icon: "💚", region: "Asia", keywords: "weixin china", sort_order: 870 },
  { code: "fps_hk", name: "FPS (Hong Kong)", icon: "🇭🇰", region: "Asia", keywords: "hong kong faster", sort_order: 880 },
  { code: "payme_hk", name: "PayMe", icon: "💙", region: "Asia", keywords: "hsbc hong kong", sort_order: 890 },
  { code: "kakao_pay", name: "Kakao Pay", icon: "💛", region: "Asia", keywords: "korea", sort_order: 900 },
  { code: "toss", name: "Toss", icon: "🔵", region: "Asia", keywords: "korea", sort_order: 910 },
  { code: "naver_pay", name: "Naver Pay", icon: "🟢", region: "Asia", keywords: "korea", sort_order: 920 },
  { code: "paypay", name: "PayPay", icon: "🔴", region: "Asia", keywords: "japan", sort_order: 930 },
  { code: "line_pay", name: "LINE Pay", icon: "💚", region: "Asia", keywords: "japan taiwan thailand", sort_order: 940 },
  { code: "bank_transfer_jp", name: "Bank Transfer (Japan)", icon: "🇯🇵", region: "Asia", keywords: "furikomi japan", sort_order: 950 },
  { code: "bank_transfer_kr", name: "Bank Transfer (Korea)", icon: "🇰🇷", region: "Asia", keywords: "korea bank", sort_order: 960 },
  { code: "bank_transfer_cn", name: "Bank Transfer (China)", icon: "🇨🇳", region: "Asia", keywords: "china bank", sort_order: 970 },
  { code: "bank_transfer_tw", name: "Bank Transfer (Taiwan)", icon: "🇹🇼", region: "Asia", keywords: "taiwan bank", sort_order: 980 },
  { code: "bkash", name: "bKash", icon: "🩷", region: "Asia", keywords: "bangladesh bkash", sort_order: 990 },
  { code: "nagad", name: "Nagad", icon: "🟠", region: "Asia", keywords: "bangladesh", sort_order: 1000 },
  { code: "easypaisa", name: "Easypaisa", icon: "🟢", region: "Asia", keywords: "pakistan", sort_order: 1010 },
  { code: "jazzcash", name: "JazzCash", icon: "🔴", region: "Asia", keywords: "pakistan", sort_order: 1020 },

  { code: "stc_pay", name: "stc pay", icon: "🟣", region: "Middle East", keywords: "saudi arabia", sort_order: 1100 },
  { code: "mada", name: "mada", icon: "🇸🇦", region: "Middle East", keywords: "saudi card network", sort_order: 1110 },
  { code: "bank_transfer_ae", name: "Bank Transfer (UAE)", icon: "🇦🇪", region: "Middle East", keywords: "uae emirates", sort_order: 1120 },
  { code: "bank_transfer_sa", name: "Bank Transfer (Saudi)", icon: "🇸🇦", region: "Middle East", keywords: "ksa", sort_order: 1130 },
  { code: "instapay_eg", name: "InstaPay", icon: "🇪🇬", region: "Middle East", keywords: "egypt", sort_order: 1140 },
  { code: "vodafone_cash", name: "Vodafone Cash", icon: "🔴", region: "Middle East", keywords: "egypt", sort_order: 1150 },
  { code: "fawry", name: "Fawry", icon: "🟡", region: "Middle East", keywords: "egypt", sort_order: 1160 },
  { code: "bank_transfer_tr", name: "Bank Transfer (Turkey)", icon: "🇹🇷", region: "Middle East", keywords: "turkey havale eft", sort_order: 1170 },
  { code: "papara", name: "Papara", icon: "🖤", region: "Middle East", keywords: "turkey", sort_order: 1180 },

  { code: "mpesa", name: "M-Pesa", icon: "🟢", region: "Africa", keywords: "kenya tanzania safaricom", sort_order: 1200 },
  { code: "airtel_money", name: "Airtel Money", icon: "🔴", region: "Africa", keywords: "africa airtel", sort_order: 1210 },
  { code: "orange_money", name: "Orange Money", icon: "🟠", region: "Africa", keywords: "west africa", sort_order: 1220 },
  { code: "mtn_momo", name: "MTN MoMo", icon: "💛", region: "Africa", keywords: "ghana uganda africa", sort_order: 1230 },
  { code: "opay", name: "OPay", icon: "🟢", region: "Africa", keywords: "nigeria", sort_order: 1240 },
  { code: "palmpay", name: "PalmPay", icon: "💜", region: "Africa", keywords: "nigeria", sort_order: 1250 },
  { code: "bank_transfer_ng", name: "Bank Transfer (Nigeria)", icon: "🇳🇬", region: "Africa", keywords: "naira nigeria", sort_order: 1260 },
  { code: "bank_transfer_za", name: "Bank Transfer (South Africa)", icon: "🇿🇦", region: "Africa", keywords: "eft za", sort_order: 1270 },
  { code: "chipper_cash", name: "Chipper Cash", icon: "🩵", region: "Africa", keywords: "africa wallet", sort_order: 1280 },

  { code: "payid", name: "PayID", icon: "🇦🇺", region: "Oceania", keywords: "australia", sort_order: 1300 },
  { code: "osko", name: "Osko", icon: "🇦🇺", region: "Oceania", keywords: "australia npp", sort_order: 1310 },
  { code: "bank_transfer_au", name: "Bank Transfer (Australia)", icon: "🇦🇺", region: "Oceania", keywords: "bsb australia", sort_order: 1320 },
  { code: "bank_transfer_nz", name: "Bank Transfer (New Zealand)", icon: "🇳🇿", region: "Oceania", keywords: "nz bank", sort_order: 1330 },
];
