/**
 * Real-world P2P payment rails (mirrors supabase migration).
 * Used as fallback / merge so the picker is rich even before SQL is applied.
 */

export type P2pPaymentMethodSeed = {
  code: string;
  name: string;
  icon: string;
  region: string;
  keywords: string;
  sort_order: number;
};

export const P2P_PAYMENT_METHOD_CATALOG: P2pPaymentMethodSeed[] = [
  { code: "openpay", name: "OpenPay Balance", icon: "◎", region: "Popular", keywords: "balance openpay pro", sort_order: 5 },
  { code: "bank_transfer", name: "Bank Transfer", icon: "🏦", region: "Global", keywords: "bank wire local deposit iban", sort_order: 10 },
  { code: "paypal", name: "PayPal", icon: "🅿️", region: "Global", keywords: "xoom paypal", sort_order: 20 },
  { code: "wise", name: "Wise", icon: "🌍", region: "Global", keywords: "transferwise", sort_order: 30 },
  { code: "payoneer", name: "Payoneer", icon: "💳", region: "Global", keywords: "payoneer card", sort_order: 40 },
  { code: "skrill", name: "Skrill", icon: "💜", region: "Global", keywords: "moneybookers", sort_order: 50 },
  { code: "neteller", name: "Neteller", icon: "💚", region: "Global", keywords: "paysafe", sort_order: 60 },
  { code: "western_union", name: "Western Union", icon: "🟡", region: "Global", keywords: "wu remittance", sort_order: 70 },
  { code: "moneygram", name: "MoneyGram", icon: "🔴", region: "Global", keywords: "remittance", sort_order: 80 },
  { code: "remitly", name: "Remitly", icon: "🔵", region: "Global", keywords: "remittance", sort_order: 90 },
  { code: "worldremit", name: "WorldRemit", icon: "🌐", region: "Global", keywords: "remittance", sort_order: 100 },
  { code: "swift", name: "SWIFT / Wire", icon: "✈️", region: "Global", keywords: "international wire bic", sort_order: 110 },
  { code: "sepa", name: "SEPA Transfer", icon: "🇪🇺", region: "Europe", keywords: "iban euro sepa", sort_order: 120 },
  { code: "cash_in_person", name: "Cash in Person", icon: "💵", region: "Global", keywords: "cash meetup face to face", sort_order: 130 },

  { code: "zelle", name: "Zelle", icon: "🟪", region: "Americas", keywords: "usa bank zelle", sort_order: 200 },
  { code: "cash_app", name: "Cash App", icon: "🟩", region: "Americas", keywords: "cashapp square usa", sort_order: 210 },
  { code: "venmo", name: "Venmo", icon: "🔵", region: "Americas", keywords: "paypal venmo usa", sort_order: 220 },
  { code: "chime", name: "Chime", icon: "🟢", region: "Americas", keywords: "usa neobank", sort_order: 230 },
  { code: "interac", name: "Interac e-Transfer", icon: "🍁", region: "Americas", keywords: "canada etransfer", sort_order: 240 },
  { code: "pix", name: "PIX", icon: "🇧🇷", region: "Americas", keywords: "brazil instant pix", sort_order: 250 },
  { code: "picpay", name: "PicPay", icon: "🟢", region: "Americas", keywords: "brazil", sort_order: 260 },
  { code: "mercado_pago", name: "Mercado Pago", icon: "💙", region: "Americas", keywords: "latam mercadopago", sort_order: 270 },
  { code: "spei", name: "SPEI", icon: "🇲🇽", region: "Americas", keywords: "mexico bank spei", sort_order: 280 },
  { code: "oxxo", name: "OXXO", icon: "🟠", region: "Americas", keywords: "mexico cash", sort_order: 290 },
  { code: "nequi", name: "Nequi", icon: "🟣", region: "Americas", keywords: "colombia", sort_order: 300 },
  { code: "daviplata", name: "Daviplata", icon: "🔴", region: "Americas", keywords: "colombia davivienda", sort_order: 310 },
  { code: "yape", name: "Yape", icon: "💜", region: "Americas", keywords: "peru bcp", sort_order: 320 },
  { code: "plin", name: "Plin", icon: "🔵", region: "Americas", keywords: "peru", sort_order: 330 },
  { code: "banco_inter", name: "Banco Inter", icon: "🧡", region: "Americas", keywords: "brazil", sort_order: 340 },
  { code: "uala", name: "Ualá", icon: "🩵", region: "Americas", keywords: "argentina mexico", sort_order: 350 },
  { code: "pago_movil", name: "Pago Móvil", icon: "🇻🇪", region: "Americas", keywords: "venezuela", sort_order: 360 },

  { code: "revolut", name: "Revolut", icon: "⚡", region: "Europe", keywords: "eu uk revolut", sort_order: 400 },
  { code: "bizum", name: "Bizum", icon: "🇪🇸", region: "Europe", keywords: "spain", sort_order: 410 },
  { code: "blik", name: "BLIK", icon: "🇵🇱", region: "Europe", keywords: "poland", sort_order: 420 },
  { code: "multibanco", name: "Multibanco", icon: "🇵🇹", region: "Europe", keywords: "portugal", sort_order: 430 },
  { code: "mb_way", name: "MB Way", icon: "🇵🇹", region: "Europe", keywords: "portugal mbway", sort_order: 440 },
  { code: "swish", name: "Swish", icon: "🇸🇪", region: "Europe", keywords: "sweden", sort_order: 450 },
  { code: "vipps", name: "Vipps", icon: "🇳🇴", region: "Europe", keywords: "norway", sort_order: 460 },
  { code: "mobilepay", name: "MobilePay", icon: "🇩🇰", region: "Europe", keywords: "denmark finland", sort_order: 470 },
  { code: "twint", name: "TWINT", icon: "🇨🇭", region: "Europe", keywords: "switzerland", sort_order: 480 },
  { code: "ideal", name: "iDEAL", icon: "🇳🇱", region: "Europe", keywords: "netherlands", sort_order: 490 },
  { code: "bancontact", name: "Bancontact", icon: "🇧🇪", region: "Europe", keywords: "belgium", sort_order: 500 },
  { code: "giropay", name: "Giropay", icon: "🇩🇪", region: "Europe", keywords: "germany", sort_order: 510 },
  { code: "sofort", name: "Sofort / Klarna", icon: "🩷", region: "Europe", keywords: "klarna sofort", sort_order: 520 },
  { code: "paysafecard", name: "Paysafecard", icon: "🎫", region: "Europe", keywords: "voucher", sort_order: 530 },
  { code: "fps_uk", name: "Faster Payments (UK)", icon: "🇬🇧", region: "Europe", keywords: "uk fps bank", sort_order: 540 },

  // —— Philippines (Binance/OKX-style banks, digital banks, e-wallets, rails) ——
  // Already listed elsewhere: openpay, bank_transfer, cash_in_person, gcash, maya, grabpay
  { code: "bancnet", name: "BancNet", icon: "🏧", region: "Philippines", keywords: "philippines atm bancnet", sort_order: 550 },
  { code: "instapay", name: "InstaPay", icon: "⚡", region: "Philippines", keywords: "philippines instant transfer bsp", sort_order: 551 },
  { code: "pesonet", name: "PESONet", icon: "🏦", region: "Philippines", keywords: "philippines batch transfer bsp", sort_order: 552 },
  { code: "qr_ph", name: "QR Ph", icon: "📱", region: "Philippines", keywords: "philippines qrph qr ph", sort_order: 553 },

  { code: "bdo", name: "BDO Unibank", icon: "🔵", region: "Philippines", keywords: "philippines bdo bank", sort_order: 560 },
  { code: "bpi", name: "BPI", icon: "🔴", region: "Philippines", keywords: "philippines bpi bank", sort_order: 561 },
  { code: "metrobank", name: "Metrobank", icon: "🔵", region: "Philippines", keywords: "philippines metrobank", sort_order: 562 },
  { code: "unionbank", name: "UnionBank", icon: "🟠", region: "Philippines", keywords: "philippines unionbank ub", sort_order: 563 },
  { code: "pnb", name: "Philippine National Bank", icon: "🔵", region: "Philippines", keywords: "philippines pnb", sort_order: 564 },
  { code: "chinabank", name: "China Bank", icon: "🔴", region: "Philippines", keywords: "philippines chinabank china bank", sort_order: 565 },
  { code: "security_bank", name: "Security Bank", icon: "🟢", region: "Philippines", keywords: "philippines security bank", sort_order: 566 },
  { code: "landbank", name: "LandBank", icon: "🟢", region: "Philippines", keywords: "philippines landbank lbp", sort_order: 567 },
  { code: "dbp", name: "Development Bank of the Philippines", icon: "🔵", region: "Philippines", keywords: "philippines dbp", sort_order: 568 },
  { code: "eastwest", name: "EastWest Bank", icon: "🟠", region: "Philippines", keywords: "philippines eastwest", sort_order: 569 },
  { code: "rcbc", name: "RCBC", icon: "🔵", region: "Philippines", keywords: "philippines rcbc", sort_order: 570 },
  { code: "psbank", name: "PSBank", icon: "🔴", region: "Philippines", keywords: "philippines psbank", sort_order: 571 },
  { code: "aub", name: "Asia United Bank", icon: "🔵", region: "Philippines", keywords: "philippines aub", sort_order: 572 },
  { code: "bank_of_commerce", name: "Bank of Commerce", icon: "🔵", region: "Philippines", keywords: "philippines bankcom bank of commerce", sort_order: 573 },
  { code: "pbcom", name: "PBCOM", icon: "🔵", region: "Philippines", keywords: "philippines pbcom", sort_order: 574 },
  { code: "maybank", name: "Maybank Philippines", icon: "🟡", region: "Philippines", keywords: "philippines maybank", sort_order: 575 },
  { code: "cimb", name: "CIMB Bank PH", icon: "🔴", region: "Philippines", keywords: "philippines cimb", sort_order: 576 },
  { code: "gotyme", name: "GoTyme Bank", icon: "🟢", region: "Philippines", keywords: "philippines gotyme digital bank", sort_order: 577 },
  { code: "seabank", name: "SeaBank Philippines", icon: "🟠", region: "Philippines", keywords: "philippines seabank shopee", sort_order: 578 },
  { code: "ownbank", name: "OwnBank", icon: "💜", region: "Philippines", keywords: "philippines ownbank digital", sort_order: 579 },
  { code: "tonik", name: "Tonik Bank", icon: "🩷", region: "Philippines", keywords: "philippines tonik digital bank", sort_order: 580 },
  { code: "unobank", name: "UNO Digital Bank", icon: "🖤", region: "Philippines", keywords: "philippines unobank uno digital", sort_order: 581 },
  { code: "uniondigital", name: "UnionDigital Bank", icon: "🟠", region: "Philippines", keywords: "philippines uniondigital union bank digital", sort_order: 582 },
  { code: "mayabank", name: "Maya Bank", icon: "💚", region: "Philippines", keywords: "philippines maya bank digital", sort_order: 583 },

  { code: "gcash", name: "GCash", icon: "💙", region: "Philippines", keywords: "philippines glife gcash ewallet", sort_order: 600 },
  { code: "maya", name: "Maya", icon: "💚", region: "Philippines", keywords: "philippines paymaya maya ewallet", sort_order: 610 },
  { code: "grabpay", name: "GrabPay", icon: "🟢", region: "Philippines", keywords: "philippines sea grab grabpay ewallet", sort_order: 620 },
  { code: "coinsph", name: "Coins.ph", icon: "🟡", region: "Philippines", keywords: "philippines coins ph wallet crypto", sort_order: 630 },
  { code: "paymaya_business", name: "Maya Business", icon: "💚", region: "Philippines", keywords: "philippines maya business paymaya merchant", sort_order: 631 },
  { code: "diskartech", name: "DiskarTech", icon: "🔵", region: "Philippines", keywords: "philippines diskartech rcbc", sort_order: 632 },
  { code: "hellomoney", name: "HelloMoney (AUB)", icon: "🩵", region: "Philippines", keywords: "philippines hellomoney aub", sort_order: 633 },
  { code: "vipwallet", name: "VIP Wallet", icon: "💜", region: "Philippines", keywords: "philippines vip wallet", sort_order: 634 },
  { code: "traxionpay", name: "Traxion Pay", icon: "🟠", region: "Philippines", keywords: "philippines traxion pay", sort_order: 635 },
  { code: "ecpay", name: "ECPay", icon: "🔵", region: "Philippines", keywords: "philippines ecpay bills payment", sort_order: 636 },

  { code: "shopeepay", name: "ShopeePay", icon: "🧡", region: "Asia", keywords: "sea shopee", sort_order: 640 },
  { code: "gopay", name: "GoPay", icon: "🟢", region: "Asia", keywords: "indonesia gojek", sort_order: 650 },
  { code: "ovo", name: "OVO", icon: "💜", region: "Asia", keywords: "indonesia", sort_order: 660 },
  { code: "dana", name: "DANA", icon: "🔵", region: "Asia", keywords: "indonesia", sort_order: 670 },
  { code: "linkaja", name: "LinkAja", icon: "🔴", region: "Asia", keywords: "indonesia", sort_order: 680 },
  { code: "qris", name: "QRIS", icon: "🇮🇩", region: "Asia", keywords: "indonesia qris", sort_order: 690 },
  { code: "promptpay", name: "PromptPay", icon: "🇹🇭", region: "Asia", keywords: "thailand", sort_order: 700 },
  { code: "true_money", name: "TrueMoney", icon: "🟠", region: "Asia", keywords: "thailand", sort_order: 710 },
  { code: "momo", name: "MoMo", icon: "🩷", region: "Asia", keywords: "vietnam", sort_order: 720 },
  { code: "zalopay", name: "ZaloPay", icon: "🔵", region: "Asia", keywords: "vietnam", sort_order: 730 },
  { code: "viettel_money", name: "Viettel Money", icon: "🔴", region: "Asia", keywords: "vietnam", sort_order: 740 },
  { code: "touch_n_go", name: "Touch 'n Go", icon: "🇲🇾", region: "Asia", keywords: "malaysia tng", sort_order: 750 },
  { code: "boost", name: "Boost", icon: "🔴", region: "Asia", keywords: "malaysia", sort_order: 760 },
  { code: "fpx", name: "FPX", icon: "🇲🇾", region: "Asia", keywords: "malaysia bank", sort_order: 770 },
  { code: "paynow", name: "PayNow", icon: "🇸🇬", region: "Asia", keywords: "singapore", sort_order: 780 },
  { code: "paylah", name: "PayLah!", icon: "🇸🇬", region: "Asia", keywords: "dbs singapore", sort_order: 790 },

  { code: "upi", name: "UPI", icon: "🇮🇳", region: "Asia", keywords: "india upi gpay phonepe", sort_order: 800 },
  { code: "paytm", name: "Paytm", icon: "🔵", region: "Asia", keywords: "india", sort_order: 810 },
  { code: "phonepe", name: "PhonePe", icon: "💜", region: "Asia", keywords: "india", sort_order: 820 },
  { code: "google_pay_in", name: "Google Pay (India)", icon: "🌈", region: "Asia", keywords: "gpay tez india", sort_order: 830 },
  { code: "imps", name: "IMPS", icon: "🇮🇳", region: "Asia", keywords: "india bank instant", sort_order: 840 },
  { code: "neft", name: "NEFT / RTGS", icon: "🏦", region: "Asia", keywords: "india bank", sort_order: 850 },
  { code: "alipay", name: "Alipay", icon: "🩵", region: "Asia", keywords: "china alipay", sort_order: 860 },
  { code: "wechat_pay", name: "WeChat Pay", icon: "💚", region: "Asia", keywords: "weixin china", sort_order: 870 },
  { code: "fps_hk", name: "FPS (Hong Kong)", icon: "🇭🇰", region: "Asia", keywords: "hong kong faster", sort_order: 880 },
  { code: "payme_hk", name: "PayMe", icon: "💙", region: "Asia", keywords: "hsbc hong kong", sort_order: 890 },
  { code: "kakao_pay", name: "Kakao Pay", icon: "💛", region: "Asia", keywords: "korea", sort_order: 900 },
  { code: "toss", name: "Toss", icon: "🔵", region: "Asia", keywords: "korea", sort_order: 910 },
  { code: "naver_pay", name: "Naver Pay", icon: "🟢", region: "Asia", keywords: "korea", sort_order: 920 },
  { code: "paypay", name: "PayPay", icon: "🔴", region: "Asia", keywords: "japan", sort_order: 930 },
  { code: "line_pay", name: "LINE Pay", icon: "💚", region: "Asia", keywords: "japan taiwan thailand", sort_order: 940 },
  { code: "bank_transfer_jp", name: "Bank Transfer (Japan)", icon: "🇯🇵", region: "Asia", keywords: "furikomi japan bank", sort_order: 950 },
  { code: "bank_transfer_kr", name: "Bank Transfer (South Korea)", icon: "🇰🇷", region: "Asia", keywords: "korea bank", sort_order: 960 },
  { code: "bank_transfer_cn", name: "Bank Transfer (China)", icon: "🇨🇳", region: "Asia", keywords: "china bank", sort_order: 970 },
  { code: "bank_transfer_tw", name: "Bank Transfer (Taiwan)", icon: "🇹🇼", region: "Asia", keywords: "taiwan bank", sort_order: 980 },
  { code: "bank_transfer_hk", name: "Bank Transfer (Hong Kong)", icon: "🇭🇰", region: "Asia", keywords: "hong kong bank fps", sort_order: 981 },
  { code: "bank_transfer_sg", name: "Bank Transfer (Singapore)", icon: "🇸🇬", region: "Asia", keywords: "singapore bank paynow", sort_order: 982 },
  { code: "bank_transfer_my", name: "Bank Transfer (Malaysia)", icon: "🇲🇾", region: "Asia", keywords: "malaysia bank fpx", sort_order: 983 },
  { code: "bank_transfer_id", name: "Bank Transfer (Indonesia)", icon: "🇮🇩", region: "Asia", keywords: "indonesia bank transfer", sort_order: 984 },
  { code: "bank_transfer_th", name: "Bank Transfer (Thailand)", icon: "🇹🇭", region: "Asia", keywords: "thailand bank promptpay", sort_order: 985 },
  { code: "bank_transfer_vn", name: "Bank Transfer (Vietnam)", icon: "🇻🇳", region: "Asia", keywords: "vietnam bank", sort_order: 986 },
  { code: "bank_transfer_ph", name: "Bank Transfer (Philippines)", icon: "🇵🇭", region: "Philippines", keywords: "philippines bank instapay pesonet", sort_order: 554 },
  { code: "bank_transfer_in", name: "Bank Transfer (India)", icon: "🇮🇳", region: "Asia", keywords: "india bank neft imps rtgs", sort_order: 851 },
  { code: "bank_transfer_bd", name: "Bank Transfer (Bangladesh)", icon: "🇧🇩", region: "Asia", keywords: "bangladesh bank", sort_order: 1001 },
  { code: "bank_transfer_pk", name: "Bank Transfer (Pakistan)", icon: "🇵🇰", region: "Asia", keywords: "pakistan bank", sort_order: 1021 },
  { code: "bkash", name: "bKash", icon: "🩷", region: "Asia", keywords: "bangladesh bkash", sort_order: 990 },
  { code: "nagad", name: "Nagad", icon: "🟠", region: "Asia", keywords: "bangladesh", sort_order: 1000 },
  { code: "easypaisa", name: "Easypaisa", icon: "🟢", region: "Asia", keywords: "pakistan", sort_order: 1010 },
  { code: "jazzcash", name: "JazzCash", icon: "🔴", region: "Asia", keywords: "pakistan", sort_order: 1020 },

  { code: "stc_pay", name: "stc pay", icon: "🟣", region: "Middle East", keywords: "saudi arabia", sort_order: 1100 },
  { code: "mada", name: "mada", icon: "🇸🇦", region: "Middle East", keywords: "saudi card network", sort_order: 1110 },
  { code: "bank_transfer_ae", name: "Bank Transfer (UAE)", icon: "🇦🇪", region: "Middle East", keywords: "uae emirates bank", sort_order: 1120 },
  { code: "bank_transfer_sa", name: "Bank Transfer (Saudi Arabia)", icon: "🇸🇦", region: "Middle East", keywords: "ksa saudi bank", sort_order: 1130 },
  { code: "bank_transfer_eg", name: "Bank Transfer (Egypt)", icon: "🇪🇬", region: "Middle East", keywords: "egypt bank", sort_order: 1135 },
  { code: "instapay_eg", name: "InstaPay", icon: "🇪🇬", region: "Middle East", keywords: "egypt", sort_order: 1140 },
  { code: "vodafone_cash", name: "Vodafone Cash", icon: "🔴", region: "Middle East", keywords: "egypt", sort_order: 1150 },
  { code: "fawry", name: "Fawry", icon: "🟡", region: "Middle East", keywords: "egypt", sort_order: 1160 },
  { code: "bank_transfer_tr", name: "Bank Transfer (Turkey)", icon: "🇹🇷", region: "Middle East", keywords: "turkey havale eft bank", sort_order: 1170 },
  { code: "papara", name: "Papara", icon: "🖤", region: "Middle East", keywords: "turkey", sort_order: 1180 },

  { code: "mpesa", name: "M-Pesa", icon: "🟢", region: "Africa", keywords: "kenya tanzania safaricom", sort_order: 1200 },
  { code: "airtel_money", name: "Airtel Money", icon: "🔴", region: "Africa", keywords: "africa airtel", sort_order: 1210 },
  { code: "orange_money", name: "Orange Money", icon: "🟠", region: "Africa", keywords: "west africa", sort_order: 1220 },
  { code: "mtn_momo", name: "MTN MoMo", icon: "💛", region: "Africa", keywords: "ghana uganda africa", sort_order: 1230 },
  { code: "opay", name: "OPay", icon: "🟢", region: "Africa", keywords: "nigeria", sort_order: 1240 },
  { code: "palmpay", name: "PalmPay", icon: "💜", region: "Africa", keywords: "nigeria", sort_order: 1250 },
  { code: "bank_transfer_ng", name: "Bank Transfer (Nigeria)", icon: "🇳🇬", region: "Africa", keywords: "naira nigeria bank", sort_order: 1260 },
  { code: "bank_transfer_za", name: "Bank Transfer (South Africa)", icon: "🇿🇦", region: "Africa", keywords: "eft za bank", sort_order: 1270 },
  { code: "bank_transfer_ke", name: "Bank Transfer (Kenya)", icon: "🇰🇪", region: "Africa", keywords: "kenya bank", sort_order: 1275 },
  { code: "chipper_cash", name: "Chipper Cash", icon: "🩵", region: "Africa", keywords: "africa wallet", sort_order: 1280 },

  { code: "payid", name: "PayID", icon: "🇦🇺", region: "Oceania", keywords: "australia", sort_order: 1300 },
  { code: "osko", name: "Osko", icon: "🇦🇺", region: "Oceania", keywords: "australia npp", sort_order: 1310 },
  { code: "bank_transfer_au", name: "Bank Transfer (Australia)", icon: "🇦🇺", region: "Oceania", keywords: "bsb australia bank", sort_order: 1320 },
  { code: "bank_transfer_nz", name: "Bank Transfer (New Zealand)", icon: "🇳🇿", region: "Oceania", keywords: "nz bank", sort_order: 1330 },

  // —— Country bank transfers (flag icons) — Americas / Europe ——
  { code: "bank_transfer_us", name: "Bank Transfer (United States)", icon: "🇺🇸", region: "Americas", keywords: "usa ach wire bank", sort_order: 365 },
  { code: "bank_transfer_ca", name: "Bank Transfer (Canada)", icon: "🇨🇦", region: "Americas", keywords: "canada etransfer bank", sort_order: 366 },
  { code: "bank_transfer_mx", name: "Bank Transfer (Mexico)", icon: "🇲🇽", region: "Americas", keywords: "mexico spei bank", sort_order: 367 },
  { code: "bank_transfer_br", name: "Bank Transfer (Brazil)", icon: "🇧🇷", region: "Americas", keywords: "brazil ted doc bank", sort_order: 368 },
  { code: "bank_transfer_ar", name: "Bank Transfer (Argentina)", icon: "🇦🇷", region: "Americas", keywords: "argentina bank cbu", sort_order: 369 },
  { code: "bank_transfer_co", name: "Bank Transfer (Colombia)", icon: "🇨🇴", region: "Americas", keywords: "colombia bank", sort_order: 370 },
  { code: "bank_transfer_pe", name: "Bank Transfer (Peru)", icon: "🇵🇪", region: "Americas", keywords: "peru bank", sort_order: 371 },
  { code: "bank_transfer_gb", name: "Bank Transfer (United Kingdom)", icon: "🇬🇧", region: "Europe", keywords: "uk fps bank faster payments", sort_order: 541 },
  { code: "bank_transfer_fr", name: "Bank Transfer (France)", icon: "🇫🇷", region: "Europe", keywords: "france sepa bank", sort_order: 542 },
  { code: "bank_transfer_de", name: "Bank Transfer (Germany)", icon: "🇩🇪", region: "Europe", keywords: "germany sepa bank", sort_order: 543 },
  { code: "bank_transfer_es", name: "Bank Transfer (Spain)", icon: "🇪🇸", region: "Europe", keywords: "spain sepa bank", sort_order: 544 },
  { code: "bank_transfer_it", name: "Bank Transfer (Italy)", icon: "🇮🇹", region: "Europe", keywords: "italy sepa bank", sort_order: 545 },
  { code: "bank_transfer_nl", name: "Bank Transfer (Netherlands)", icon: "🇳🇱", region: "Europe", keywords: "netherlands sepa ideal bank", sort_order: 546 },
  { code: "bank_transfer_be", name: "Bank Transfer (Belgium)", icon: "🇧🇪", region: "Europe", keywords: "belgium sepa bank", sort_order: 547 },
  { code: "bank_transfer_ch", name: "Bank Transfer (Switzerland)", icon: "🇨🇭", region: "Europe", keywords: "switzerland bank", sort_order: 548 },
  { code: "bank_transfer_se", name: "Bank Transfer (Sweden)", icon: "🇸🇪", region: "Europe", keywords: "sweden bank swish", sort_order: 549 },
  { code: "bank_transfer_no", name: "Bank Transfer (Norway)", icon: "🇳🇴", region: "Europe", keywords: "norway bank vipps", sort_order: 585 },
  { code: "bank_transfer_dk", name: "Bank Transfer (Denmark)", icon: "🇩🇰", region: "Europe", keywords: "denmark bank mobilepay", sort_order: 586 },
  { code: "bank_transfer_pl", name: "Bank Transfer (Poland)", icon: "🇵🇱", region: "Europe", keywords: "poland bank blik", sort_order: 587 },
  { code: "bank_transfer_pt", name: "Bank Transfer (Portugal)", icon: "🇵🇹", region: "Europe", keywords: "portugal bank multibanco", sort_order: 588 },
  { code: "bank_transfer_ie", name: "Bank Transfer (Ireland)", icon: "🇮🇪", region: "Europe", keywords: "ireland sepa bank", sort_order: 589 },
];
