/**
 * Master Token / Market Registry for OpenPay Pro Spot + Perpetual.
 *
 * Sources: CoinGecko + CoinMarketCap top market-cap lists + prior curated
 * majors. Each row enables Spot (`*USDT`) and Perpetual (`*USDT.P`) by default.
 *
 * Not listed as base pairs: quote stables / dollar funds (USDT, USDC, TUSD,
 * DAI, USDS, USD1, USDe, USDG, PYUSD, USDD, RLUSD, FDUSD, EURC, …) and
 * non-tradeable RWA/fund tickers from homepage rankings.
 *
 * Adding a listed market = one `market({...})` row. TradingView / CoinGecko /
 * CMC URLs are generated from symbol + slugs.
 */

import type { MajorTokenId } from "@/lib/major-tokens";
import { isMajorTokenId } from "@/lib/major-tokens";

export type TradeMarketStatus = "listed" | "delisted";

export type TradeMarketDef = {
  symbol: string;
  name: string;
  pair: string;
  network: string;
  contract_address: string | null;
  coingecko_slug: string;
  coinmarketcap_slug: string;
  logo: string;
  majorId?: MajorTokenId;
  status: TradeMarketStatus;
  spot_enabled: boolean;
  perpetual_enabled: boolean;
  margin_enabled: boolean;
  max_leverage: number;
  tick_size: number;
  step_size: number;
  min_qty: number;
  max_qty: number;
  maker_fee: number;
  taker_fee: number;
  spot_tv: string;
  perp_tv: string;
  binance_futures?: string;
  okx_swap?: string;
  gate_futures?: string;
  bybit_linear?: string;
  cmc_rank?: number;
  cmc_ucid?: number;
};

export function tradingViewSpotUrl(symbol: string): string {
  return `https://www.tradingview.com/symbols/${symbol.toUpperCase()}USDT/`;
}

export function tradingViewPerpUrl(symbol: string): string {
  return `https://www.tradingview.com/symbols/${symbol.toUpperCase()}USDT.P/`;
}

export function coingeckoUrl(slug: string): string {
  return `https://www.coingecko.com/en/coins/${slug}`;
}

export function coinmarketcapUrl(slug: string): string {
  return `https://coinmarketcap.com/currencies/${slug}/`;
}

type MarketSeed = {
  symbol: string;
  name: string;
  network: string;
  coingecko_slug: string;
  coinmarketcap_slug?: string;
  logo: string;
  majorId?: MajorTokenId;
  contract_address?: string | null;
  spot_enabled?: boolean;
  perpetual_enabled?: boolean;
  margin_enabled?: boolean;
  max_leverage?: number;
  tick_size?: number;
  step_size?: number;
  min_qty?: number;
  max_qty?: number;
  maker_fee?: number;
  taker_fee?: number;
  spot_tv?: string;
  perp_tv?: string;
  binance_futures?: string | false;
  okx_swap?: string | false;
  gate_futures?: string | false;
  bybit_linear?: string | false;
  cmc_rank?: number;
  cmc_ucid?: number;
};

function market(seed: MarketSeed): TradeMarketDef {
  const symbol = seed.symbol.toUpperCase();
  const pair = `${symbol}USDT`;
  const inferred =
    seed.majorId ??
    (isMajorTokenId(symbol.toLowerCase())
      ? (symbol.toLowerCase() as MajorTokenId)
      : undefined);
  return {
    symbol,
    name: seed.name,
    pair,
    network: seed.network,
    contract_address: seed.contract_address ?? null,
    coingecko_slug: seed.coingecko_slug,
    coinmarketcap_slug: seed.coinmarketcap_slug ?? seed.coingecko_slug,
    logo: seed.logo,
    majorId: inferred,
    status: "listed",
    spot_enabled: seed.spot_enabled ?? true,
    perpetual_enabled: seed.perpetual_enabled ?? true,
    margin_enabled: seed.margin_enabled ?? true,
    max_leverage: seed.max_leverage ?? 20,
    tick_size: seed.tick_size ?? 0.01,
    step_size: seed.step_size ?? 0.0001,
    min_qty: seed.min_qty ?? 0.0001,
    max_qty: seed.max_qty ?? 1_000_000,
    maker_fee: seed.maker_fee ?? 0.0002,
    taker_fee: seed.taker_fee ?? 0.0005,
    spot_tv: seed.spot_tv ?? `BINANCE:${pair}`,
    perp_tv: seed.perp_tv ?? `OKX:${pair}.P`,
    binance_futures:
      seed.binance_futures === false ? undefined : (seed.binance_futures ?? pair),
    okx_swap:
      seed.okx_swap === false ? undefined : (seed.okx_swap ?? `${symbol}-USDT-SWAP`),
    gate_futures:
      seed.gate_futures === false ? undefined : (seed.gate_futures ?? `${symbol}_USDT`),
    bybit_linear:
      seed.bybit_linear === false ? undefined : (seed.bybit_linear ?? pair),
    cmc_rank: seed.cmc_rank,
    cmc_ucid: seed.cmc_ucid,
  };
}

/** CoinGecko large logo helper */
const cg = (path: string) => `https://assets.coingecko.com/coins/images/${path}`;

/** CoinMarketCap 64px logo by UCID */
const cmc = (ucid: number) =>
  `https://s2.coinmarketcap.com/static/img/coins/64x64/${ucid}.png`;

/**
 * Canonical Spot + Perpetual registry (CG/CMC live + curated majors).
 * PI retained as OpenPay Pro native listing.
 */
export const TRADE_MARKETS: TradeMarketDef[] = [
  market({
    symbol: "BTC",
    name: "Bitcoin",
    network: "Bitcoin",
    coingecko_slug: "bitcoin",
    logo: cg("1/large/bitcoin.png"),
    majorId: "btc",
    spot_tv: "BINANCE:BTCUSDT",
    perp_tv: "OKX:BTCUSDT.P",
    tick_size: 0.1,
    cmc_rank: 1,
    cmc_ucid: 1,
  }),
  market({
    symbol: "ETH",
    name: "Ethereum",
    network: "Ethereum",
    coingecko_slug: "ethereum",
    logo: cg("279/large/ethereum.png"),
    majorId: "eth",
    spot_tv: "BINANCE:ETHUSDT",
    perp_tv: "OKX:ETHUSDT.P",
    cmc_rank: 2,
    cmc_ucid: 1027,
  }),
  market({
    symbol: "BNB",
    name: "BNB",
    network: "BNB Chain",
    coingecko_slug: "binancecoin",
    coinmarketcap_slug: "bnb",
    logo: "https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png",
    majorId: "bnb",
    cmc_rank: 4,
    cmc_ucid: 1839,
  }),
  market({
    symbol: "XRP",
    name: "XRP",
    network: "XRP Ledger",
    coingecko_slug: "ripple",
    coinmarketcap_slug: "xrp",
    logo: cg("44/large/xrp-symbol-white-128.png"),
    majorId: "xrp",
    tick_size: 0.0001,
    cmc_rank: 6,
    cmc_ucid: 52,
  }),
  market({
    symbol: "SOL",
    name: "Solana",
    network: "Solana",
    coingecko_slug: "solana",
    logo: cg("4128/large/solana.png"),
    majorId: "sol",
    spot_tv: "BINANCE:SOLUSDT",
    perp_tv: "OKX:SOLUSDT.P",
    cmc_rank: 7,
    cmc_ucid: 5426,
  }),
  market({
    symbol: "TRX",
    name: "TRON",
    network: "TRON",
    coingecko_slug: "tron",
    logo: cg("1094/large/tron-logo.png"),
    majorId: "trx",
    tick_size: 0.00001,
    cmc_rank: 8,
    cmc_ucid: 1958,
  }),
  market({
    symbol: "DOGE",
    name: "Dogecoin",
    network: "Dogecoin",
    coingecko_slug: "dogecoin",
    logo: cg("5/large/dogecoin.png"),
    majorId: "doge",
    tick_size: 0.00001,
    cmc_rank: 9,
    cmc_ucid: 74,
  }),
  market({
    symbol: "HYPE",
    name: "Hyperliquid",
    network: "Hyperliquid",
    coingecko_slug: "hyperliquid",
    logo: cg("50882/large/hyperliquid.jpg"),
    majorId: "hype",
    cmc_rank: 10,
    cmc_ucid: 32196,
  }),
  market({
    symbol: "ADA",
    name: "Cardano",
    network: "Cardano",
    coingecko_slug: "cardano",
    logo: cg("975/large/cardano.png"),
    majorId: "ada",
    tick_size: 0.0001,
    cmc_rank: 11,
    cmc_ucid: 2010,
  }),
  market({
    symbol: "WBTC",
    name: "Wrapped Bitcoin",
    network: "Ethereum",
    coingecko_slug: "wrapped-bitcoin",
    logo: cg("7598/large/wrapped_bitcoin_wbtc.png"),
    contract_address: "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599",
    tick_size: 0.1,
    cmc_rank: 12,
    cmc_ucid: 3717,
  }),
  market({
    symbol: "SUI",
    name: "Sui",
    network: "Sui",
    coingecko_slug: "sui",
    logo: cg("26375/large/sui-ocean-square.png"),
    majorId: "sui",
    tick_size: 0.0001,
    cmc_rank: 13,
    cmc_ucid: 20947,
  }),
  market({
    symbol: "LINK",
    name: "Chainlink",
    network: "Ethereum",
    coingecko_slug: "chainlink",
    logo: cg("877/large/chainlink-new-logo.png"),
    majorId: "link",
    contract_address: "0x514910771af9ca656af840dff83e8264ecf986ca",
    cmc_rank: 14,
    cmc_ucid: 1975,
  }),
  market({
    symbol: "XLM",
    name: "Stellar",
    network: "Stellar",
    coingecko_slug: "stellar",
    logo: cg("100/large/Stellar_symbol_black_RGB.png"),
    majorId: "xlm",
    tick_size: 0.00001,
    cmc_rank: 15,
    cmc_ucid: 512,
  }),
  market({
    symbol: "BCH",
    name: "Bitcoin Cash",
    network: "Bitcoin Cash",
    coingecko_slug: "bitcoin-cash",
    logo: cg("780/large/bitcoin-cash-circle.png"),
    majorId: "bch",
    cmc_rank: 16,
    cmc_ucid: 1831,
  }),
  market({
    symbol: "AVAX",
    name: "Avalanche",
    network: "Avalanche",
    coingecko_slug: "avalanche-2",
    coinmarketcap_slug: "avalanche",
    logo: cg("12559/large/Avalanche_Circle_RedWhite_Trans.png"),
    majorId: "avax",
    cmc_rank: 17,
    cmc_ucid: 5805,
  }),
  market({
    symbol: "LEO",
    name: "UNUS SED LEO",
    network: "Ethereum",
    coingecko_slug: "leo-token",
    coinmarketcap_slug: "unus-sed-leo",
    logo: cg("8418/large/leo_token.png"),
    tick_size: 0.001,
    max_leverage: 10,
    cmc_rank: 18,
    cmc_ucid: 3957,
  }),
  market({
    symbol: "SHIB",
    name: "Shiba Inu",
    network: "Ethereum",
    coingecko_slug: "shiba-inu",
    logo: cg("11939/large/shiba.png"),
    contract_address: "0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce",
    tick_size: 0.00000001,
    step_size: 1000,
    max_leverage: 10,
    cmc_rank: 19,
    cmc_ucid: 5994,
  }),
  market({
    symbol: "GRAM",
    name: "Gram (prev. Toncoin)",
    network: "TON",
    coingecko_slug: "the-open-network",
    coinmarketcap_slug: "gram",
    logo: "https://coin-images.coingecko.com/coins/images/17980/large/Gram_Circular_Badge.png",
    majorId: "gram",
    cmc_rank: 22,
    cmc_ucid: 11419,
  }),
  market({
    symbol: "LTC",
    name: "Litecoin",
    network: "Litecoin",
    coingecko_slug: "litecoin",
    logo: cg("2/large/litecoin.png"),
    cmc_rank: 21,
    cmc_ucid: 2,
  }),
  market({
    symbol: "DOT",
    name: "Polkadot",
    network: "Polkadot",
    coingecko_slug: "polkadot",
    logo: cg("12171/large/polkadot.png"),
    majorId: "dot",
    cmc_rank: 22,
    cmc_ucid: 6636,
  }),
  market({
    symbol: "HBAR",
    name: "Hedera",
    network: "Hedera",
    coingecko_slug: "hedera-hashgraph",
    coinmarketcap_slug: "hedera",
    logo: cg("3441/large/Hedera_Hashgraph_logo.png"),
    tick_size: 0.00001,
    cmc_rank: 23,
    cmc_ucid: 4642,
  }),
  market({
    symbol: "UNI",
    name: "Uniswap",
    network: "Ethereum",
    coingecko_slug: "uniswap",
    logo: "https://coin-images.coingecko.com/coins/images/12504/large/uniswap-logo.png",
    majorId: "uni",
    contract_address: "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984",
    cmc_rank: 24,
    cmc_ucid: 7083,
  }),
  market({
    symbol: "PEPE",
    name: "Pepe",
    network: "Ethereum",
    coingecko_slug: "pepe",
    logo: cg("29850/large/pepe-token.jpeg"),
    contract_address: "0x6982508145454ce325ddbe47a25d4ec3d2311933",
    tick_size: 0.00000001,
    step_size: 10000,
    max_leverage: 10,
    cmc_rank: 25,
    cmc_ucid: 24478,
  }),
  market({
    symbol: "XMR",
    name: "Monero",
    network: "Monero",
    coingecko_slug: "monero",
    logo: cg("69/large/monero_logo.png"),
    // Often thin on Binance USDT-M — prefer OKX/Gate
    binance_futures: false,
    bybit_linear: false,
    cmc_rank: 26,
    cmc_ucid: 328,
  }),
  market({
    symbol: "APT",
    name: "Aptos",
    network: "Aptos",
    coingecko_slug: "aptos",
    logo: cg("26455/large/aptos_round.png"),
    cmc_rank: 27,
    cmc_ucid: 21794,
  }),
  market({
    symbol: "TAO",
    name: "Bittensor",
    network: "Bittensor",
    coingecko_slug: "bittensor",
    logo: cg("28452/large/ARUsPEvY_400x400.jpeg"),
    cmc_rank: 28,
    cmc_ucid: 22974,
  }),
  market({
    symbol: "NEAR",
    name: "NEAR Protocol",
    network: "NEAR",
    coingecko_slug: "near",
    logo: cg("10365/large/near.jpg"),
    majorId: "near",
    cmc_rank: 29,
    cmc_ucid: 6535,
  }),
  market({
    symbol: "ONDO",
    name: "Ondo",
    network: "Ethereum",
    coingecko_slug: "ondo-finance",
    coinmarketcap_slug: "ondo-finance",
    logo: cg("26580/large/ONDO.png"),
    majorId: "ondo",
    tick_size: 0.0001,
    cmc_rank: 30,
    cmc_ucid: 21133,
  }),
  market({
    symbol: "ICP",
    name: "Internet Computer",
    network: "Internet Computer",
    coingecko_slug: "internet-computer",
    logo: cg("14495/large/Internet_Computer_logo.png"),
    cmc_rank: 31,
    cmc_ucid: 8916,
  }),
  market({
    symbol: "ETC",
    name: "Ethereum Classic",
    network: "Ethereum Classic",
    coingecko_slug: "ethereum-classic",
    logo: cg("453/large/ethereum-classic-logo.png"),
    cmc_rank: 32,
    cmc_ucid: 1321,
  }),
  market({
    symbol: "CRO",
    name: "Cronos",
    network: "Cronos",
    coingecko_slug: "crypto-com-chain",
    coinmarketcap_slug: "cronos",
    logo: cg("7310/large/cro_token_logo.png"),
    tick_size: 0.00001,
    cmc_rank: 33,
    cmc_ucid: 3635,
  }),
  market({
    symbol: "AAVE",
    name: "Aave",
    network: "Ethereum",
    coingecko_slug: "aave",
    logo: cg("12645/large/aave-token-round.png"),
    majorId: "aave",
    contract_address: "0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9",
    cmc_rank: 34,
    cmc_ucid: 7278,
  }),
  market({
    symbol: "MNT",
    name: "Mantle",
    network: "Mantle",
    coingecko_slug: "mantle",
    logo: cg("30980/large/token-logo.png"),
    tick_size: 0.0001,
    cmc_rank: 35,
    cmc_ucid: 27075,
  }),
  market({
    symbol: "POL",
    name: "Polygon",
    network: "Polygon",
    coingecko_slug: "polygon-ecosystem-token",
    coinmarketcap_slug: "polygon-ecosystem-token",
    logo: cg("32440/large/polygon.png"),
    tick_size: 0.0001,
    cmc_rank: 36,
    cmc_ucid: 28321,
  }),
  market({
    symbol: "VET",
    name: "VeChain",
    network: "VeChain",
    coingecko_slug: "vechain",
    logo: cg("1167/large/VeChain-Logo-768x725.png"),
    tick_size: 0.00001,
    cmc_rank: 37,
    cmc_ucid: 3077,
  }),
  market({
    symbol: "ALGO",
    name: "Algorand",
    network: "Algorand",
    coingecko_slug: "algorand",
    logo: cg("4380/large/download.png"),
    tick_size: 0.0001,
    cmc_rank: 38,
    cmc_ucid: 4030,
  }),
  market({
    symbol: "FIL",
    name: "Filecoin",
    network: "Filecoin",
    coingecko_slug: "filecoin",
    logo: cg("12817/large/filecoin.png"),
    cmc_rank: 39,
    cmc_ucid: 2280,
  }),
  market({
    symbol: "RENDER",
    name: "Render",
    network: "Solana",
    coingecko_slug: "render-token",
    coinmarketcap_slug: "render",
    logo: cg("11636/large/rndr.png"),
    cmc_rank: 40,
    cmc_ucid: 5690,
  }),
  market({
    symbol: "ATOM",
    name: "Cosmos",
    network: "Cosmos",
    coingecko_slug: "cosmos",
    logo: cg("1481/large/cosmos_hub.png"),
    cmc_rank: 41,
    cmc_ucid: 3794,
  }),
  market({
    symbol: "ARB",
    name: "Arbitrum",
    network: "Arbitrum",
    coingecko_slug: "arbitrum",
    logo: cg("16547/large/photo_2023-03-29_21.47.00.jpeg"),
    contract_address: "0x912ce59144191c1204e64559fe8253a0e49e6548",
    tick_size: 0.0001,
    cmc_rank: 42,
    cmc_ucid: 11841,
  }),
  market({
    symbol: "OP",
    name: "Optimism",
    network: "Optimism",
    coingecko_slug: "optimism",
    logo: cg("25244/large/Optimism.png"),
    contract_address: "0x4200000000000000000000000000000000000042",
    tick_size: 0.0001,
    cmc_rank: 43,
    cmc_ucid: 11840,
  }),
  market({
    symbol: "INJ",
    name: "Injective",
    network: "Injective",
    coingecko_slug: "injective-protocol",
    coinmarketcap_slug: "injective",
    logo: cg("12882/large/Secondary_Symbol.png"),
    cmc_rank: 44,
    cmc_ucid: 7226,
  }),
  market({
    symbol: "SEI",
    name: "Sei",
    network: "Sei",
    coingecko_slug: "sei-network",
    coinmarketcap_slug: "sei",
    logo: cg("28205/large/Sei_Logo_-_Transparent.png"),
    tick_size: 0.0001,
    cmc_rank: 45,
    cmc_ucid: 23149,
  }),
  market({
    symbol: "JUP",
    name: "Jupiter",
    network: "Solana",
    coingecko_slug: "jupiter-exchange-solana",
    coinmarketcap_slug: "jupiter-ag",
    logo: cg("34188/large/jup.png"),
    majorId: "jup",
    tick_size: 0.0001,
    cmc_rank: 46,
    cmc_ucid: 29210,
  }),
  market({
    symbol: "FET",
    name: "Fetch.ai",
    network: "Fetch.ai",
    coingecko_slug: "fetch-ai",
    coinmarketcap_slug: "artificial-superintelligence-alliance",
    logo: cg("5681/large/Fetch.jpg"),
    tick_size: 0.0001,
    cmc_rank: 47,
    cmc_ucid: 3773,
  }),
  market({
    symbol: "KAS",
    name: "Kaspa",
    network: "Kaspa",
    coingecko_slug: "kaspa",
    logo: cg("25751/large/kaspa-icon-exchanges.png"),
    tick_size: 0.00001,
    binance_futures: false,
    cmc_rank: 48,
    cmc_ucid: 20396,
  }),
  market({
    symbol: "BONK",
    name: "Bonk",
    network: "Solana",
    coingecko_slug: "bonk",
    logo: cg("28600/large/bonk.jpg"),
    tick_size: 0.00000001,
    step_size: 10000,
    max_leverage: 10,
    cmc_rank: 49,
    cmc_ucid: 23095,
  }),
  market({
    symbol: "WIF",
    name: "dogwifhat",
    network: "Solana",
    coingecko_slug: "dogwifcoin",
    coinmarketcap_slug: "dogwifhat",
    logo: cg("33566/large/dogwifhat.jpg"),
    tick_size: 0.0001,
    max_leverage: 10,
    cmc_rank: 50,
    cmc_ucid: 28752,
  }),
  market({
    symbol: "ENA",
    name: "Ethena",
    network: "Ethereum",
    coingecko_slug: "ethena",
    logo: cg("36530/large/ethena.png"),
    contract_address: "0x57e114b691db790c35207b2e685d4a43181e6061",
    tick_size: 0.0001,
    cmc_rank: 51,
    cmc_ucid: 30171,
  }),
  market({
    symbol: "PYTH",
    name: "Pyth Network",
    network: "Solana",
    coingecko_slug: "pyth-network",
    logo: cg("31924/large/pyth.png"),
    tick_size: 0.0001,
    cmc_rank: 52,
    cmc_ucid: 28177,
  }),
  market({
    symbol: "PENDLE",
    name: "Pendle",
    network: "Ethereum",
    coingecko_slug: "pendle",
    logo: cg("15069/large/Pendle_Logo_Normal-03.png"),
    tick_size: 0.001,
    cmc_rank: 53,
    cmc_ucid: 9481,
  }),
  market({
    symbol: "SAND",
    name: "The Sandbox",
    network: "Ethereum",
    coingecko_slug: "the-sandbox",
    logo: cg("12129/large/sandbox_logo.jpg"),
    tick_size: 0.0001,
    cmc_rank: 54,
    cmc_ucid: 6210,
  }),
  market({
    symbol: "MANA",
    name: "Decentraland",
    network: "Ethereum",
    coingecko_slug: "decentraland",
    logo: cg("878/large/decentraland-mana.png"),
    tick_size: 0.0001,
    cmc_rank: 55,
    cmc_ucid: 1966,
  }),
  market({
    symbol: "GRT",
    name: "The Graph",
    network: "Ethereum",
    coingecko_slug: "the-graph",
    logo: cg("13397/large/Graph_Token.png"),
    tick_size: 0.0001,
    cmc_rank: 56,
    cmc_ucid: 6719,
  }),
  market({
    symbol: "THETA",
    name: "Theta Network",
    network: "Theta",
    coingecko_slug: "theta-token",
    coinmarketcap_slug: "theta-network",
    logo: cg("2538/large/theta-token-logo.png"),
    tick_size: 0.001,
    cmc_rank: 57,
    cmc_ucid: 2416,
  }),
  market({
    symbol: "FLOW",
    name: "Flow",
    network: "Flow",
    coingecko_slug: "flow",
    logo: cg("13446/large/5f6294c0c7a8cbe6eead49a9af_5f59c3930e6492d2e1bfa9a9_flow.png"),
    tick_size: 0.001,
    cmc_rank: 58,
    cmc_ucid: 4558,
  }),
  market({
    symbol: "EOS",
    name: "EOS",
    network: "EOS",
    coingecko_slug: "eos",
    logo: cg("738/large/eos-eos-logo.png"),
    tick_size: 0.001,
    cmc_rank: 59,
    cmc_ucid: 1765,
  }),
  market({
    symbol: "EGLD",
    name: "MultiversX",
    network: "MultiversX",
    coingecko_slug: "elrond-erd-2",
    coinmarketcap_slug: "multiversx-egld",
    logo: cg("12335/large/egld-token-logo.png"),
    cmc_rank: 60,
    cmc_ucid: 6892,
  }),
  market({
    symbol: "QNT",
    name: "Quant",
    network: "Ethereum",
    coingecko_slug: "quant-network",
    logo: cg("3370/large/5ZOu7brX_400x400.jpg"),
    tick_size: 0.01,
    cmc_rank: 61,
    cmc_ucid: 3155,
  }),
  market({
    symbol: "STX",
    name: "Stacks",
    network: "Stacks",
    coingecko_slug: "blockstack",
    coinmarketcap_slug: "stacks",
    logo: cg("2069/large/Stacks_logo_full.png"),
    tick_size: 0.001,
    cmc_rank: 62,
    cmc_ucid: 4847,
  }),
  market({
    symbol: "XDC",
    name: "XDC Network",
    network: "XDC",
    coingecko_slug: "xdce-crowd-sale",
    coinmarketcap_slug: "xdc-network",
    logo: cg("2912/large/xdc-icon.png"),
    tick_size: 0.00001,
    binance_futures: false,
    cmc_rank: 63,
    cmc_ucid: 2634,
  }),
  market({
    symbol: "NEXO",
    name: "Nexo",
    network: "Ethereum",
    coingecko_slug: "nexo",
    logo: cg("3695/large/nexo.png"),
    tick_size: 0.001,
    max_leverage: 10,
    binance_futures: false,
    cmc_rank: 64,
    cmc_ucid: 2694,
  }),
  market({
    symbol: "BSV",
    name: "Bitcoin SV",
    network: "Bitcoin SV",
    coingecko_slug: "bitcoin-cash-sv",
    coinmarketcap_slug: "bitcoin-sv",
    logo: cg("6799/large/BSV.png"),
    binance_futures: false,
    bybit_linear: false,
    cmc_rank: 65,
    cmc_ucid: 3602,
  }),
  market({
    symbol: "IMX",
    name: "Immutable",
    network: "Ethereum",
    coingecko_slug: "immutable-x",
    coinmarketcap_slug: "immutable-x",
    logo: cg("17233/large/immutableX-symbol-BLK-RGB.png"),
    tick_size: 0.0001,
    cmc_rank: 66,
    cmc_ucid: 10603,
  }),
  market({
    symbol: "RUNE",
    name: "THORChain",
    network: "THORChain",
    coingecko_slug: "thorchain",
    logo: cg("6595/large/Rune200x200.png"),
    tick_size: 0.001,
    cmc_rank: 67,
    cmc_ucid: 4157,
  }),
  market({
    symbol: "KCS",
    name: "KuCoin Token",
    network: "KuCoin Community Chain",
    coingecko_slug: "kucoin-shares",
    coinmarketcap_slug: "kucoin-token",
    logo: cg("1047/large/sa9z79.png"),
    tick_size: 0.001,
    binance_futures: false,
    bybit_linear: false,
    cmc_rank: 68,
    cmc_ucid: 2087,
  }),
  market({
    symbol: "CAKE",
    name: "PancakeSwap",
    network: "BNB Chain",
    coingecko_slug: "pancakeswap-token",
    logo: cg("12632/large/pancakeswap-cake-logo_%281%29.png"),
    majorId: "cake",
    tick_size: 0.001,
    cmc_rank: 69,
    cmc_ucid: 7186,
  }),
  market({
    symbol: "FLR",
    name: "Flare",
    network: "Flare",
    coingecko_slug: "flare-networks",
    coinmarketcap_slug: "flare",
    logo: cg("28665/large/flr.png"),
    tick_size: 0.00001,
    cmc_rank: 70,
    cmc_ucid: 7950,
  }),
  market({
    symbol: "MKR",
    name: "Maker",
    network: "Ethereum",
    coingecko_slug: "maker",
    logo: cg("1364/large/Mark_Maker.png"),
    tick_size: 0.1,
    cmc_rank: 71,
    cmc_ucid: 1518,
  }),
  market({
    symbol: "CRV",
    name: "Curve DAO",
    network: "Ethereum",
    coingecko_slug: "curve-dao-token",
    logo: cg("12124/large/Curve.png"),
    tick_size: 0.001,
    cmc_rank: 72,
    cmc_ucid: 6538,
  }),
  market({
    symbol: "COMP",
    name: "Compound",
    network: "Ethereum",
    coingecko_slug: "compound-governance-token",
    logo: cg("10775/large/COMP.png"),
    tick_size: 0.01,
    cmc_rank: 73,
    cmc_ucid: 5692,
  }),
  market({
    symbol: "SNX",
    name: "Synthetix",
    network: "Ethereum",
    coingecko_slug: "havven",
    coinmarketcap_slug: "synthetix",
    logo: cg("3406/large/SNX.png"),
    tick_size: 0.001,
    cmc_rank: 74,
    cmc_ucid: 2586,
  }),
  market({
    symbol: "LDO",
    name: "Lido DAO",
    network: "Ethereum",
    coingecko_slug: "lido-dao",
    logo: cg("13573/large/Lido_DAO.png"),
    tick_size: 0.001,
    cmc_rank: 75,
    cmc_ucid: 13538,
  }),
  market({
    symbol: "AXS",
    name: "Axie Infinity",
    network: "Ethereum",
    coingecko_slug: "axie-infinity",
    logo: cg("13029/large/axie_infinity_logo.png"),
    tick_size: 0.001,
    cmc_rank: 76,
    cmc_ucid: 6783,
  }),
  market({
    symbol: "GALA",
    name: "Gala",
    network: "Ethereum",
    coingecko_slug: "gala",
    logo: cg("12493/large/GALA-COINGECKO.png"),
    tick_size: 0.00001,
    cmc_rank: 77,
    cmc_ucid: 7080,
  }),
  market({
    symbol: "CHZ",
    name: "Chiliz",
    network: "Chiliz",
    coingecko_slug: "chiliz",
    logo: cg("8834/large/CHZ_Token_updated.png"),
    tick_size: 0.0001,
    cmc_rank: 78,
    cmc_ucid: 4066,
  }),
  market({
    symbol: "IOTA",
    name: "IOTA",
    network: "IOTA",
    coingecko_slug: "iota",
    logo: cg("692/large/IOTA_Swirl.png"),
    tick_size: 0.0001,
    cmc_rank: 79,
    cmc_ucid: 1720,
  }),
  market({
    symbol: "ROSE",
    name: "Oasis",
    network: "Oasis",
    coingecko_slug: "oasis-network",
    coinmarketcap_slug: "oasis-network",
    logo: cg("13162/large/rose.png"),
    tick_size: 0.00001,
    cmc_rank: 80,
    cmc_ucid: 7653,
  }),
  market({
    symbol: "KAVA",
    name: "Kava",
    network: "Kava",
    coingecko_slug: "kava",
    logo: cg("9761/large/kava.png"),
    tick_size: 0.001,
    cmc_rank: 81,
    cmc_ucid: 4846,
  }),
  market({
    symbol: "MINA",
    name: "Mina",
    network: "Mina",
    coingecko_slug: "mina-protocol",
    logo: cg("15628/large/JM4_cQEwn1.png"),
    tick_size: 0.001,
    cmc_rank: 82,
    cmc_ucid: 8646,
  }),
  market({
    symbol: "ZEC",
    name: "Zcash",
    network: "Zcash",
    coingecko_slug: "zcash",
    logo: cg("486/large/circle-zcash-color.png"),
    majorId: "zec",
    cmc_rank: 83,
    cmc_ucid: 1437,
  }),
  market({
    symbol: "DASH",
    name: "Dash",
    network: "Dash",
    coingecko_slug: "dash",
    logo: cg("19/large/dash-logo.png"),
    cmc_rank: 84,
    cmc_ucid: 131,
  }),
  market({
    symbol: "NEO",
    name: "Neo",
    network: "Neo",
    coingecko_slug: "neo",
    logo: cg("480/large/NEO_512_512.png"),
    cmc_rank: 85,
    cmc_ucid: 1376,
  }),
  market({
    symbol: "SFP",
    name: "SafePal",
    network: "BNB Chain",
    coingecko_slug: "safepal",
    logo: cg("13905/large/sfp.png"),
    tick_size: 0.001,
    max_leverage: 10,
    cmc_rank: 86,
    cmc_ucid: 8119,
  }),
  market({
    symbol: "TWT",
    name: "Trust Wallet",
    network: "BNB Chain",
    coingecko_slug: "trust-wallet-token",
    logo: cg("11085/large/Trust.png"),
    tick_size: 0.001,
    max_leverage: 10,
    cmc_rank: 87,
    cmc_ucid: 5964,
  }),
  market({
    symbol: "ZRO",
    name: "LayerZero",
    network: "Ethereum",
    coingecko_slug: "layerzero",
    logo: cg("28206/large/ftxG9nQG_400x400.jpg"),
    tick_size: 0.001,
    cmc_rank: 88,
    cmc_ucid: 26997,
  }),
  market({
    symbol: "STRK",
    name: "Starknet",
    network: "Starknet",
    coingecko_slug: "starknet",
    logo: cg("26433/large/starknet.png"),
    tick_size: 0.0001,
    cmc_rank: 89,
    cmc_ucid: 22691,
  }),
  market({
    symbol: "AERO",
    name: "Aerodrome Finance",
    network: "Base",
    coingecko_slug: "aerodrome-finance",
    logo: cg("31745/large/token.png"),
    tick_size: 0.0001,
    binance_futures: false,
    cmc_rank: 90,
    cmc_ucid: 29270,
  }),
  market({
    symbol: "VIRTUAL",
    name: "Virtuals Protocol",
    network: "Base",
    coingecko_slug: "virtual-protocol",
    logo: cg("34057/large/LOGOMARK.png"),
    tick_size: 0.001,
    cmc_rank: 91,
    cmc_ucid: 29420,
  }),
  market({
    symbol: "BEAM",
    name: "Beam",
    network: "Beam",
    coingecko_slug: "beam-2",
    coinmarketcap_slug: "beam",
    logo: cg("32417/large/chain-logo.png"),
    tick_size: 0.00001,
    cmc_rank: 92,
    cmc_ucid: 28298,
  }),
  market({
    symbol: "AKT",
    name: "Akash Network",
    network: "Akash",
    coingecko_slug: "akash-network",
    logo: cg("12785/large/akash-logo.png"),
    tick_size: 0.001,
    binance_futures: false,
    cmc_rank: 93,
    cmc_ucid: 7431,
  }),
  market({
    symbol: "NOT",
    name: "Notcoin",
    network: "TON",
    coingecko_slug: "notcoin",
    logo: cg("34470/large/not.jpg"),
    tick_size: 0.000001,
    step_size: 100,
    max_leverage: 10,
    cmc_rank: 94,
    cmc_ucid: 28850,
  }),
  market({
    symbol: "BLUR",
    name: "Blur",
    network: "Ethereum",
    coingecko_slug: "blur",
    logo: cg("28453/large/blur.png"),
    tick_size: 0.0001,
    cmc_rank: 95,
    cmc_ucid: 23121,
  }),
  market({
    symbol: "CELO",
    name: "Celo",
    network: "Celo",
    coingecko_slug: "celo",
    logo: cg("11090/large/InjXBNx9_400x400.jpg"),
    tick_size: 0.001,
    cmc_rank: 96,
    cmc_ucid: 5567,
  }),
  market({
    symbol: "ORDI",
    name: "ORDI",
    network: "Bitcoin",
    coingecko_slug: "ordinals",
    coinmarketcap_slug: "ordi",
    logo: cg("30162/large/ordi.png"),
    tick_size: 0.01,
    max_leverage: 10,
    cmc_rank: 97,
    cmc_ucid: 25028,
  }),
  market({
    symbol: "BRETT",
    name: "Brett",
    network: "Base",
    coingecko_slug: "based-brett",
    coinmarketcap_slug: "based-brett",
    logo: cg("35529/large/1000050750.png"),
    tick_size: 0.00001,
    max_leverage: 10,
    binance_futures: false,
    cmc_rank: 98,
    cmc_ucid: 29743,
  }),
  market({
    symbol: "BABYDOGE",
    name: "Baby Doge Coin",
    network: "BNB Chain",
    coingecko_slug: "baby-doge-coin",
    logo: cg("16166/large/babydoge.jpg"),
    tick_size: 0.000000000001,
    step_size: 1_000_000,
    max_leverage: 5,
    cmc_rank: 99,
    cmc_ucid: 10407,
  }),

  // --- Live CG/CMC additions (Spot + Perp) ---
  market({
    symbol: "WBT",
    name: "WhiteBIT Coin",
    network: "Ethereum",
    coingecko_slug: "whitebit",
    logo: cmc(22407),
    max_leverage: 10,
    binance_futures: false,
    cmc_ucid: 22407,
  }),
  market({
    symbol: "RAIN",
    name: "Rain",
    network: "Ethereum",
    coingecko_slug: "rain",
    logo: cmc(36563),
    tick_size: 0.00001,
    max_leverage: 10,
    binance_futures: false,
  }),
  market({
    symbol: "CC",
    name: "Canton",
    network: "Canton",
    coingecko_slug: "canton",
    coinmarketcap_slug: "canton-network",
    logo: cmc(35721),
    tick_size: 0.0001,
    max_leverage: 10,
    binance_futures: false,
  }),
  market({
    symbol: "XAUT",
    name: "Tether Gold",
    network: "Ethereum",
    coingecko_slug: "tether-gold",
    logo: "https://coin-images.coingecko.com/coins/images/10481/large/logo.png",
    majorId: "xaut",
    contract_address: "0x68749665ff8d2d112fa859aa293f07a622782f38",
    tick_size: 0.1,
    max_leverage: 10,
    cmc_ucid: 5176,
  }),
  market({
    symbol: "PAXG",
    name: "PAX Gold",
    network: "Ethereum",
    coingecko_slug: "pax-gold",
    logo: "https://coin-images.coingecko.com/coins/images/9519/large/asset-paxg.png",
    majorId: "paxg",
    contract_address: "0x45804880de22913dafe09f4980848ece6ecbaf78",
    tick_size: 0.1,
    max_leverage: 10,
    cmc_ucid: 4705,
  }),
  market({
    symbol: "OKB",
    name: "OKB",
    network: "Ethereum",
    coingecko_slug: "okb",
    logo: "https://coin-images.coingecko.com/coins/images/4463/large/WeChat_Image_20220118095654.png",
    majorId: "okb",
    contract_address: "0x75231f58b43240c9718dd58b4967c5114342a86c",
    spot_tv: "OKX:OKBUSDT",
    perp_tv: "OKX:OKBUSDT.P",
    binance_futures: false,
    cmc_ucid: 3897,
  }),
  market({
    symbol: "WLFI",
    name: "World Liberty Financial",
    network: "Ethereum",
    coingecko_slug: "world-liberty-financial",
    coinmarketcap_slug: "world-liberty-financial-wlfi",
    logo: "https://coin-images.coingecko.com/coins/images/50767/large/wlfi.png",
    majorId: "wlfi",
    tick_size: 0.00001,
    max_leverage: 10,
  }),
  market({
    symbol: "ASTER",
    name: "Aster",
    network: "BNB Smart Chain",
    coingecko_slug: "aster-2",
    coinmarketcap_slug: "aster",
    logo: "https://coin-images.coingecko.com/coins/images/69040/large/_ASTER.png",
    majorId: "aster",
    tick_size: 0.0001,
    max_leverage: 20,
  }),
  market({
    symbol: "HTX",
    name: "HTX DAO",
    network: "TRON",
    coingecko_slug: "htx-dao",
    logo: cmc(32790),
    tick_size: 0.00000001,
    step_size: 1000,
    max_leverage: 10,
    binance_futures: false,
  }),
  market({
    symbol: "M",
    name: "MemeCore",
    network: "MemeCore",
    coingecko_slug: "memecore",
    logo: cmc(35346),
    tick_size: 0.0001,
    max_leverage: 10,
    binance_futures: false,
  }),
  market({
    symbol: "SKY",
    name: "Sky",
    network: "Ethereum",
    coingecko_slug: "sky",
    logo: cmc(33079),
    tick_size: 0.00001,
    max_leverage: 10,
  }),
  market({
    symbol: "MORPHO",
    name: "Morpho",
    network: "Ethereum",
    coingecko_slug: "morpho",
    logo: cmc(29870),
    max_leverage: 10,
  }),
  market({
    symbol: "WLD",
    name: "Worldcoin",
    network: "Optimism",
    coingecko_slug: "worldcoin",
    coinmarketcap_slug: "worldcoin-org",
    logo: cmc(13502),
    tick_size: 0.0001,
    max_leverage: 20,
    cmc_ucid: 13502,
  }),
  market({
    symbol: "BGB",
    name: "Bitget Token",
    network: "Ethereum",
    coingecko_slug: "bitget-token",
    coinmarketcap_slug: "bitget-token-new",
    logo: "https://coin-images.coingecko.com/coins/images/11610/large/Bitget_logo.png",
    majorId: "bgb",
    max_leverage: 10,
    binance_futures: false,
    cmc_ucid: 11092,
  }),
  market({
    symbol: "PUMP",
    name: "Pump.fun",
    network: "Solana",
    coingecko_slug: "pump-fun",
    logo: "https://coin-images.coingecko.com/coins/images/67164/large/pump.jpg",
    majorId: "pump",
    tick_size: 0.000001,
    step_size: 1,
    max_leverage: 10,
  }),
  market({
    symbol: "JST",
    name: "JUST",
    network: "TRON",
    coingecko_slug: "just",
    logo: cmc(4944),
    tick_size: 0.00001,
    max_leverage: 10,
    cmc_ucid: 4944,
  }),
  market({
    symbol: "STABLE",
    name: "Stable",
    network: "Ethereum",
    coingecko_slug: "stable-2",
    coinmarketcap_slug: "stable",
    logo: cmc(36817),
    tick_size: 0.00001,
    max_leverage: 5,
    binance_futures: false,
  }),
  market({
    symbol: "BEAT",
    name: "Audiera",
    network: "BNB Smart Chain",
    coingecko_slug: "audiera",
    logo: cmc(37390),
    max_leverage: 10,
    binance_futures: false,
  }),
  market({
    symbol: "GT",
    name: "Gate",
    network: "Ethereum",
    coingecko_slug: "gatechain-token",
    coinmarketcap_slug: "gatetoken",
    logo: "https://coin-images.coingecko.com/coins/images/8183/large/200X200.png",
    majorId: "gt",
    max_leverage: 10,
    binance_futures: false,
    cmc_ucid: 4269,
  }),
  market({
    symbol: "BDX",
    name: "Beldex",
    network: "Beldex",
    coingecko_slug: "beldex",
    logo: cmc(2693),
    tick_size: 0.00001,
    max_leverage: 5,
    binance_futures: false,
    bybit_linear: false,
  }),
  market({
    symbol: "VVV",
    name: "Venice Token",
    network: "Base",
    coingecko_slug: "venice-token",
    logo: cmc(35679),
    max_leverage: 10,
    binance_futures: false,
  }),
  market({
    symbol: "LIT",
    name: "Lighter",
    network: "Ethereum",
    coingecko_slug: "lighter",
    logo: cmc(36525),
    max_leverage: 10,
    binance_futures: false,
  }),
  market({
    symbol: "PENGU",
    name: "Pudgy Penguins",
    network: "Solana",
    coingecko_slug: "pudgy-penguins",
    logo: cmc(34466),
    tick_size: 0.000001,
    step_size: 1,
    max_leverage: 20,
    cmc_ucid: 34466,
  }),
  market({
    symbol: "TRUMP",
    name: "OFFICIAL TRUMP",
    network: "Solana",
    coingecko_slug: "official-trump",
    logo: cmc(35336),
    max_leverage: 20,
    cmc_ucid: 35336,
  }),
  market({
    symbol: "ETHFI",
    name: "ether.fi",
    network: "Ethereum",
    coingecko_slug: "ether-fi",
    coinmarketcap_slug: "ether-fi-ethfi",
    logo: cmc(29814),
    tick_size: 0.0001,
    max_leverage: 20,
    cmc_ucid: 29814,
  }),
  market({
    symbol: "SUN",
    name: "Sun",
    network: "TRON",
    coingecko_slug: "sun-token",
    logo: cmc(10529),
    tick_size: 0.00001,
    max_leverage: 10,
    cmc_ucid: 10529,
  }),
  market({
    symbol: "NIGHT",
    name: "Midnight",
    network: "Midnight",
    coingecko_slug: "midnight-network",
    logo: cmc(37055),
    tick_size: 0.00001,
    max_leverage: 5,
    binance_futures: false,
  }),
  market({
    symbol: "TIA",
    name: "Celestia",
    network: "Celestia",
    coingecko_slug: "celestia",
    logo: cmc(22861),
    tick_size: 0.0001,
    max_leverage: 20,
    cmc_ucid: 22861,
  }),
  market({
    symbol: "SPX",
    name: "SPX6900",
    network: "Ethereum",
    coingecko_slug: "spx6900",
    logo: cmc(29569),
    tick_size: 0.0001,
    max_leverage: 10,
    cmc_ucid: 29569,
  }),
  market({
    symbol: "LUNC",
    name: "Terra Classic",
    network: "Terra Classic",
    coingecko_slug: "terra-luna",
    logo: cmc(4172),
    tick_size: 0.00000001,
    step_size: 1,
    max_leverage: 10,
    cmc_ucid: 4172,
  }),
  market({
    symbol: "GNO",
    name: "Gnosis",
    network: "Ethereum",
    coingecko_slug: "gnosis",
    coinmarketcap_slug: "gnosis-gno",
    logo: cmc(1659),
    max_leverage: 10,
    cmc_ucid: 1659,
  }),
  market({
    symbol: "EURC",
    name: "EURC",
    network: "Ethereum",
    coingecko_slug: "euro-coin",
    logo: cmc(20641),
    majorId: "eurc",
    tick_size: 0.0001,
    max_leverage: 5,
    perpetual_enabled: false,
    margin_enabled: false,
    binance_futures: false,
    bybit_linear: false,
    cmc_ucid: 20641,
  }),

  // OpenPay Pro native listing
  market({
    symbol: "PI",
    name: "Pi Network",
    network: "Pi Network",
    coingecko_slug: "pi-network",
    coinmarketcap_slug: "pi",
    logo: "https://coin-images.coingecko.com/coins/images/54342/large/pi_network.jpg?1739347576",
    majorId: "pi",
    spot_tv: "OKX:PIUSDT",
    perp_tv: "OKX:PIUSDT.P",
    binance_futures: false,
    bybit_linear: false,
    max_leverage: 10,
    tick_size: 0.0001,
    cmc_rank: 55,
    cmc_ucid: 35697,
  }),
];

const BY_SYMBOL = new Map(TRADE_MARKETS.map((m) => [m.symbol, m]));

const _listedSymbols = TRADE_MARKETS.filter(
  (m) => m.status === "listed" && (m.spot_enabled || m.perpetual_enabled),
).map((m) => m.symbol);

if (_listedSymbols.length < 1) {
  throw new Error("Master Token Registry has no listed markets");
}

export const PERP_MARKETS = _listedSymbols as [string, ...string[]];
export type PerpMarket = (typeof PERP_MARKETS)[number];

export function getTradeMarket(symbol: string): TradeMarketDef | undefined {
  return BY_SYMBOL.get(symbol.toUpperCase());
}

export function requireTradeMarket(symbol: string): TradeMarketDef {
  const m = getTradeMarket(symbol);
  if (!m) throw new Error(`Unknown trade market: ${symbol}`);
  return m;
}

export function isTradeMarket(v: string): v is PerpMarket {
  return BY_SYMBOL.has(v.toUpperCase()) && getTradeMarket(v)?.status === "listed";
}

export function listedTradeMarkets(): TradeMarketDef[] {
  return TRADE_MARKETS.filter((m) => m.status === "listed");
}

export function marketsForMode(mode: "spot" | "futures"): TradeMarketDef[] {
  return listedTradeMarkets().filter((m) =>
    mode === "spot" ? m.spot_enabled : m.perpetual_enabled,
  );
}
