/** Part B: ja, ko, ru, hi, id, ms */
export default {
  ja: {
    common: {
      appName: "OpenPay Pro",
      loading: "読み込み中…",
      save: "保存",
      cancel: "キャンセル",
      confirm: "確認",
      continue: "続ける",
      back: "戻る",
      close: "閉じる",
      done: "完了",
      search: "検索",
      copy: "コピー",
      copied: "コピーしました",
      max: "最大",
      next: "次へ",
      error: "問題が発生しました",
      retry: "再試行",
      signOut: "サインアウト",
      active: "有効",
      amount: "金額",
      balance: "残高",
      wallet: "ウォレット",
      learnMore: "詳細を見る",
      notFound: "ページが見つかりません",
      notFoundDesc: "そのルートは OpenPay Pro Wallet に存在しません。",
      goHome: "ホームへ",
    },
    nav: {
      home: "ホーム",
      wallet: "ウォレット",
      tokens: "トークン",
      openToken: "OpenToken",
      history: "履歴",
      settings: "設定",
      liveChat: "ライブチャット",
      watchlist: "ウォッチリスト",
      ledgerApi: "Ledger API",
      docs: "OpenPay ドキュメント",
      faq: "FAQ",
      nfts: "コレクティブル",
      send: "送信",
      receive: "受け取り",
      swap: "スワップ",
      buy: "購入",
      scan: "スキャン",
    },
    language: {
      title: "表示言語",
      subtitle: "OpenPay Pro の言語を選択",
      searchPlaceholder: "言語を検索",
      updated: "言語を更新しました",
      current: "現在の言語",
    },
    settings: {
      title: "設定",
      account: "アカウント",
      wallets: "ウォレット",
      security: "セキュリティ",
      preferences: "環境設定",
      connected: "接続済み",
      legal: "法務",
      theme: "テーマ",
      themeDesc: "OpenPay の見た目を選択",
      light: "ライト",
      dark: "ダーク",
      currency: "通貨",
      currencyDesc: "法定通貨の表示単位",
      language: "言語",
      languageDesc: "インターフェース言語",
      priceAlerts: "価格アラート",
      priceAlertsDesc: "大きな変動時に通知",
      txAlerts: "取引アラート",
      txAlertsDesc: "送信・受け取り・チャージ時に通知",
      lockPush: "ロック画面プッシュ",
      lockPushDesc: "端末ロック時やアプリ終了時のシステム通知",
      emailAlerts: "メールアラート",
      emailAlertsDesc: "資金の受け取り・送信時にメール",
      terms: "利用規約",
      privacy: "プライバシーポリシー",
      regulatory: "規制情報",
      signOutConfirm: "OpenPay Pro からサインアウトしますか？",
      profile: "プロフィール",
      editProfile: "プロフィールを編集",
      manageWallets: "ウォレットを管理",
      biometric: "生体認証ロック解除",
      pin: "PIN",
      recovery: "リカバリーフレーズ",
    },
    dashboard: {
      title: "ホーム",
      tokens: "トークン",
      collectibles: "コレクティブル",
      activity: "最近のアクティビティ",
      seeAll: "すべて見る",
      send: "送信",
      receive: "受け取り",
      swap: "スワップ",
      buy: "購入",
      emptyTokens: "まだトークンがありません",
      emptyActivity: "まだアクティビティがありません",
    },
    buy: {
      title: "購入",
      addOusd: "ウォレットに OUSD を追加",
      amount: "金額",
      payWith: "支払い方法",
      openpayBalance: "OpenPay 残高",
      openpayDesc: "接続済みの OpenPay アカウントから支払い · 実際の引き落とし",
      moonpay: "MoonPay",
      moonpayDesc: "カード / Apple Pay / Google Pay · MoonPay → OUSD",
      pi: "Pi Network (π)",
      piDesc: "Pi で支払い · ライブ π 価格 → OUSD ($1) を即時入金",
      usdc: "USDC 支払い",
      usdcDesc: "USDC で支払い · MoonPay Commerce → OUSD",
      crypto: "暗号資産デポジット",
      cryptoDesc: "SOL / 暗号資産 · MoonPay Commerce → OUSD",
      confirmTitle: "チャージを確認",
      confirmDesc: "OUSD の購入内容を確認",
      youPay: "支払い額",
      rateNote: "1 OUSD = $1.00 · 有効なウォレットに入金",
      payOpenPay: "OpenPay で {{amount}} を支払う",
      buyMoonPay: "MoonPay で購入 · {{amount}}",
      depositCrypto: "{{amount}} の暗号資産を入金",
      payUsdc: "USDC で {{amount}} を支払う",
      topUp: "{{amount}} をチャージ",
      connectOpenPay: "続行するには OpenPay を接続",
    },
    wallet: {
      title: "ウォレット",
      mainWallet: "メインウォレット",
      myWallet: "マイウォレット",
      switched: "ウォレットを切り替えました",
      receive: "受け取り",
      send: "送信",
      ousd: "OUSD",
    },
    send: {
      title: "送信",
      to: "宛先",
      from: "送金元",
      review: "確認",
      confirm: "送信を確認",
    },
    receive: {
      title: "受け取り",
      shareAddress: "アドレスを共有",
      copyAddress: "アドレスをコピー",
    },
    swap: {
      title: "スワップ",
      youPay: "支払い額",
      youReceive: "受取額",
      confirm: "スワップを確認",
    },
    auth: {
      signIn: "サインイン",
      welcome: "OpenPay Pro へようこそ",
    },
    tx: {
      confirm: "確認",
      success: "成功",
      pending: "保留中",
      failed: "失敗",
    },
  },

  ko: {
    common: {
      appName: "OpenPay Pro",
      loading: "로딩 중…",
      save: "저장",
      cancel: "취소",
      confirm: "확인",
      continue: "계속",
      back: "뒤로",
      close: "닫기",
      done: "완료",
      search: "검색",
      copy: "복사",
      copied: "복사됨",
      max: "최대",
      next: "다음",
      error: "문제가 발생했습니다",
      retry: "다시 시도",
      signOut: "로그아웃",
      active: "활성",
      amount: "금액",
      balance: "잔액",
      wallet: "지갑",
      learnMore: "자세히 알아보기",
      notFound: "페이지를 찾을 수 없음",
      notFoundDesc: "해당 경로는 OpenPay Pro Wallet에 없습니다.",
      goHome: "홈으로",
    },
    nav: {
      home: "홈",
      wallet: "지갑",
      tokens: "토큰",
      openToken: "OpenToken",
      history: "기록",
      settings: "설정",
      liveChat: "라이브 채팅",
      watchlist: "관심 목록",
      ledgerApi: "Ledger API",
      docs: "OpenPay 문서",
      faq: "FAQ",
      nfts: "수집품",
      send: "보내기",
      receive: "받기",
      swap: "스왑",
      buy: "구매",
      scan: "스캔",
    },
    language: {
      title: "표시 언어",
      subtitle: "OpenPay Pro 언어를 선택하세요",
      searchPlaceholder: "언어 검색",
      updated: "언어가 업데이트되었습니다",
      current: "현재 언어",
    },
    settings: {
      title: "설정",
      account: "계정",
      wallets: "지갑",
      security: "보안",
      preferences: "환경설정",
      connected: "연결됨",
      legal: "법적 고지",
      theme: "테마",
      themeDesc: "OpenPay 모양 선택",
      light: "라이트",
      dark: "다크",
      currency: "통화",
      currencyDesc: "법정화폐 표시 단위",
      language: "언어",
      languageDesc: "인터페이스 언어",
      priceAlerts: "가격 알림",
      priceAlertsDesc: "큰 변동 시 알림",
      txAlerts: "거래 알림",
      txAlertsDesc: "보내기, 받기 및 충전 시 알림",
      lockPush: "잠금 화면 푸시",
      lockPushDesc: "휴대폰 잠금 또는 앱 종료 시 시스템 알림",
      emailAlerts: "이메일 알림",
      emailAlertsDesc: "자금 수령 또는 송금 시 이메일",
      terms: "서비스 약관",
      privacy: "개인정보 처리방침",
      regulatory: "규제 정보",
      signOutConfirm: "OpenPay Pro에서 로그아웃할까요?",
      profile: "프로필",
      editProfile: "프로필 편집",
      manageWallets: "지갑 관리",
      biometric: "생체 인식 잠금 해제",
      pin: "PIN",
      recovery: "복구 구문",
    },
    dashboard: {
      title: "홈",
      tokens: "토큰",
      collectibles: "수집품",
      activity: "최근 활동",
      seeAll: "전체 보기",
      send: "보내기",
      receive: "받기",
      swap: "스왑",
      buy: "구매",
      emptyTokens: "아직 토큰이 없습니다",
      emptyActivity: "아직 활동이 없습니다",
    },
    buy: {
      title: "구매",
      addOusd: "지갑에 OUSD 추가",
      amount: "금액",
      payWith: "결제 수단",
      openpayBalance: "OpenPay 잔액",
      openpayDesc: "연결된 OpenPay 계정에서 결제 · 실제 출금",
      moonpay: "MoonPay",
      moonpayDesc: "카드 / Apple Pay / Google Pay · MoonPay → OUSD",
      pi: "Pi Network (π)",
      piDesc: "Pi로 결제 · 실시간 π 가격 → OUSD ($1) 즉시 입금",
      usdc: "USDC 결제",
      usdcDesc: "USDC로 결제 · MoonPay Commerce → OUSD",
      crypto: "암호화폐 입금",
      cryptoDesc: "SOL / 암호화폐 · MoonPay Commerce → OUSD",
      confirmTitle: "충전 확인",
      confirmDesc: "OUSD 구매 내용을 검토하세요",
      youPay: "결제 금액",
      rateNote: "1 OUSD = $1.00 · 활성 지갑에 입금",
      payOpenPay: "OpenPay로 {{amount}} 결제",
      buyMoonPay: "MoonPay로 구매 · {{amount}}",
      depositCrypto: "{{amount}} 암호화폐 입금",
      payUsdc: "USDC로 {{amount}} 결제",
      topUp: "{{amount}} 충전",
      connectOpenPay: "계속하려면 OpenPay를 연결하세요",
    },
    wallet: {
      title: "지갑",
      mainWallet: "메인 지갑",
      myWallet: "내 지갑",
      switched: "지갑이 전환되었습니다",
      receive: "받기",
      send: "보내기",
      ousd: "OUSD",
    },
    send: {
      title: "보내기",
      to: "받는 사람",
      from: "보내는 사람",
      review: "검토",
      confirm: "전송 확인",
    },
    receive: {
      title: "받기",
      shareAddress: "주소 공유",
      copyAddress: "주소 복사",
    },
    swap: {
      title: "스왑",
      youPay: "결제 금액",
      youReceive: "받는 금액",
      confirm: "스왑 확인",
    },
    auth: {
      signIn: "로그인",
      welcome: "OpenPay Pro에 오신 것을 환영합니다",
    },
    tx: {
      confirm: "확인",
      success: "성공",
      pending: "대기 중",
      failed: "실패",
    },
  },

  ru: {
    common: {
      appName: "OpenPay Pro",
      loading: "Загрузка…",
      save: "Сохранить",
      cancel: "Отмена",
      confirm: "Подтвердить",
      continue: "Продолжить",
      back: "Назад",
      close: "Закрыть",
      done: "Готово",
      search: "Поиск",
      copy: "Копировать",
      copied: "Скопировано",
      max: "Макс.",
      next: "Далее",
      error: "Что-то пошло не так",
      retry: "Повторить",
      signOut: "Выйти",
      active: "Активный",
      amount: "Сумма",
      balance: "Баланс",
      wallet: "Кошелёк",
      learnMore: "Подробнее",
      notFound: "Страница не найдена",
      notFoundDesc: "Этот маршрут не существует в OpenPay Pro Wallet.",
      goHome: "На главную",
    },
    nav: {
      home: "Главная",
      wallet: "Кошелёк",
      tokens: "Токены",
      openToken: "OpenToken",
      history: "История",
      settings: "Настройки",
      liveChat: "Онлайн-чат",
      watchlist: "Список наблюдения",
      ledgerApi: "Ledger API",
      docs: "Документация OpenPay",
      faq: "FAQ",
      nfts: "Коллекционные",
      send: "Отправить",
      receive: "Получить",
      swap: "Обмен",
      buy: "Купить",
      scan: "Сканировать",
    },
    language: {
      title: "Язык интерфейса",
      subtitle: "Выберите язык OpenPay Pro",
      searchPlaceholder: "Поиск языков",
      updated: "Язык обновлён",
      current: "Текущий язык",
    },
    settings: {
      title: "Настройки",
      account: "Аккаунт",
      wallets: "Кошельки",
      security: "Безопасность",
      preferences: "Предпочтения",
      connected: "Подключено",
      legal: "Правовая информация",
      theme: "Тема",
      themeDesc: "Выберите оформление OpenPay",
      light: "Светлая",
      dark: "Тёмная",
      currency: "Валюта",
      currencyDesc: "Отображать фиат в",
      language: "Язык",
      languageDesc: "Язык интерфейса",
      priceAlerts: "Ценовые оповещения",
      priceAlertsDesc: "Уведомлять о крупных движениях",
      txAlerts: "Оповещения о транзакциях",
      txAlertsDesc: "Уведомлять об отправке, получении и пополнении",
      lockPush: "Push на экране блокировки",
      lockPushDesc: "Системные уведомления при блокировке телефона или закрытом приложении",
      emailAlerts: "Email-оповещения",
      emailAlertsDesc: "Письмо при получении или отправке средств",
      terms: "Условия использования",
      privacy: "Политика конфиденциальности",
      regulatory: "Регулирование",
      signOutConfirm: "Выйти из OpenPay Pro?",
      profile: "Профиль",
      editProfile: "Редактировать профиль",
      manageWallets: "Управление кошельками",
      biometric: "Биометрическая разблокировка",
      pin: "PIN",
      recovery: "Фраза восстановления",
    },
    dashboard: {
      title: "Главная",
      tokens: "Токены",
      collectibles: "Коллекционные",
      activity: "Недавняя активность",
      seeAll: "Смотреть все",
      send: "Отправить",
      receive: "Получить",
      swap: "Обмен",
      buy: "Купить",
      emptyTokens: "Пока нет токенов",
      emptyActivity: "Пока нет активности",
    },
    buy: {
      title: "Купить",
      addOusd: "Добавить OUSD в кошелёк",
      amount: "Сумма",
      payWith: "Оплатить с помощью",
      openpayBalance: "Баланс OpenPay",
      openpayDesc: "Оплата с подключённого аккаунта OpenPay · реальное списание",
      moonpay: "MoonPay",
      moonpayDesc: "Карта / Apple Pay / Google Pay · MoonPay → OUSD",
      pi: "Pi Network (π)",
      piDesc: "Оплата Pi · живая цена π → OUSD ($1) мгновенно зачисляется",
      usdc: "Оплата USDC",
      usdcDesc: "Оплата USDC · MoonPay Commerce → OUSD",
      crypto: "Криптодепозит",
      cryptoDesc: "SOL / крипто · MoonPay Commerce → OUSD",
      confirmTitle: "Подтвердить пополнение",
      confirmDesc: "Проверьте покупку OUSD",
      youPay: "Вы платите",
      rateNote: "1 OUSD = $1.00 · зачисляется на активный кошелёк",
      payOpenPay: "Оплатить {{amount}} через OpenPay",
      buyMoonPay: "Купить через MoonPay · {{amount}}",
      depositCrypto: "Внести {{amount}} крипто",
      payUsdc: "Оплатить {{amount}} через USDC",
      topUp: "Пополнить {{amount}}",
      connectOpenPay: "Подключите OpenPay, чтобы продолжить",
    },
    wallet: {
      title: "Кошелёк",
      mainWallet: "Основной кошелёк",
      myWallet: "Мой кошелёк",
      switched: "Кошелёк переключён",
      receive: "Получить",
      send: "Отправить",
      ousd: "OUSD",
    },
    send: {
      title: "Отправить",
      to: "Кому",
      from: "От кого",
      review: "Проверить",
      confirm: "Подтвердить отправку",
    },
    receive: {
      title: "Получить",
      shareAddress: "Поделиться адресом",
      copyAddress: "Скопировать адрес",
    },
    swap: {
      title: "Обмен",
      youPay: "Вы платите",
      youReceive: "Вы получаете",
      confirm: "Подтвердить обмен",
    },
    auth: {
      signIn: "Войти",
      welcome: "Добро пожаловать в OpenPay Pro",
    },
    tx: {
      confirm: "Подтвердить",
      success: "Успешно",
      pending: "В ожидании",
      failed: "Не удалось",
    },
  },

  hi: {
    common: {
      appName: "OpenPay Pro",
      loading: "लोड हो रहा है…",
      save: "सहेजें",
      cancel: "रद्द करें",
      confirm: "पुष्टि करें",
      continue: "जारी रखें",
      back: "वापस",
      close: "बंद करें",
      done: "हो गया",
      search: "खोजें",
      copy: "कॉपी करें",
      copied: "कॉपी हो गया",
      max: "अधिकतम",
      next: "अगला",
      error: "कुछ गलत हो गया",
      retry: "फिर से कोशिश करें",
      signOut: "साइन आउट",
      active: "सक्रिय",
      amount: "राशि",
      balance: "शेष राशि",
      wallet: "वॉलेट",
      learnMore: "और जानें",
      notFound: "पेज नहीं मिला",
      notFoundDesc: "वह रूट OpenPay Pro Wallet में मौजूद नहीं है।",
      goHome: "होम जाएँ",
    },
    nav: {
      home: "होम",
      wallet: "वॉलेट",
      tokens: "टोकन",
      openToken: "OpenToken",
      history: "इतिहास",
      settings: "सेटिंग्स",
      liveChat: "लाइव चैट",
      watchlist: "वॉचलिस्ट",
      ledgerApi: "Ledger API",
      docs: "OpenPay दस्तावेज़",
      faq: "FAQ",
      nfts: "संग्रहणीय",
      send: "भेजें",
      receive: "प्राप्त करें",
      swap: "स्वैप",
      buy: "खरीदें",
      scan: "स्कैन",
    },
    language: {
      title: "प्रदर्शन भाषा",
      subtitle: "अपनी OpenPay Pro भाषा चुनें",
      searchPlaceholder: "भाषाएँ खोजें",
      updated: "भाषा अपडेट हो गई",
      current: "वर्तमान भाषा",
    },
    settings: {
      title: "सेटिंग्स",
      account: "खाता",
      wallets: "वॉलेट",
      security: "सुरक्षा",
      preferences: "वरीयताएँ",
      connected: "कनेक्टेड",
      legal: "कानूनी",
      theme: "थीम",
      themeDesc: "OpenPay कैसा दिखे, चुनें",
      light: "लाइट",
      dark: "डार्क",
      currency: "मुद्रा",
      currencyDesc: "फिएट मान दिखाएँ",
      language: "भाषा",
      languageDesc: "इंटरफ़ेस भाषा",
      priceAlerts: "मूल्य अलर्ट",
      priceAlertsDesc: "बड़े उतार-चढ़ाव पर सूचित करें",
      txAlerts: "लेन-देन अलर्ट",
      txAlertsDesc: "भेजने, प्राप्त करने और टॉप-अप पर सूचित करें",
      lockPush: "लॉक-स्क्रीन पुश",
      lockPushDesc: "फ़ोन लॉक या ऐप बंद होने पर सिस्टम सूचनाएँ",
      emailAlerts: "ईमेल अलर्ट",
      emailAlertsDesc: "फंड प्राप्त या भेजने पर ईमेल",
      terms: "सेवा की शर्तें",
      privacy: "गोपनीयता नीति",
      regulatory: "नियामक",
      signOutConfirm: "OpenPay Pro से साइन आउट करें?",
      profile: "प्रोफ़ाइल",
      editProfile: "प्रोफ़ाइल संपादित करें",
      manageWallets: "वॉलेट प्रबंधित करें",
      biometric: "बायोमेट्रिक अनलॉक",
      pin: "PIN",
      recovery: "रिकवरी वाक्यांश",
    },
    dashboard: {
      title: "होम",
      tokens: "टोकन",
      collectibles: "संग्रहणीय",
      activity: "हाल की गतिविधि",
      seeAll: "सभी देखें",
      send: "भेजें",
      receive: "प्राप्त करें",
      swap: "स्वैप",
      buy: "खरीदें",
      emptyTokens: "अभी कोई टोकन नहीं",
      emptyActivity: "अभी कोई गतिविधि नहीं",
    },
    buy: {
      title: "खरीदें",
      addOusd: "अपने वॉलेट में OUSD जोड़ें",
      amount: "राशि",
      payWith: "भुगतान करें",
      openpayBalance: "OpenPay बैलेंस",
      openpayDesc: "अपने कनेक्टेड OpenPay खाते से भुगतान · वास्तविक डेबिट",
      moonpay: "MoonPay",
      moonpayDesc: "कार्ड / Apple Pay / Google Pay · MoonPay → OUSD",
      pi: "Pi Network (π)",
      piDesc: "Pi से भुगतान · लाइव π मूल्य → OUSD ($1) तुरंत जमा",
      usdc: "USDC भुगतान",
      usdcDesc: "USDC से भुगतान · MoonPay Commerce → OUSD",
      crypto: "क्रिप्टो जमा",
      cryptoDesc: "SOL / क्रिप्टो · MoonPay Commerce → OUSD",
      confirmTitle: "टॉप-अप की पुष्टि करें",
      confirmDesc: "अपनी OUSD खरीद की समीक्षा करें",
      youPay: "आप भुगतान करते हैं",
      rateNote: "1 OUSD = $1.00 · आपके सक्रिय वॉलेट में जमा",
      payOpenPay: "OpenPay से {{amount}} भुगतान करें",
      buyMoonPay: "MoonPay से खरीदें · {{amount}}",
      depositCrypto: "{{amount}} क्रिप्टो जमा करें",
      payUsdc: "USDC से {{amount}} भुगतान करें",
      topUp: "{{amount}} टॉप अप करें",
      connectOpenPay: "जारी रखने के लिए OpenPay कनेक्ट करें",
    },
    wallet: {
      title: "वॉलेट",
      mainWallet: "मुख्य वॉलेट",
      myWallet: "मेरा वॉलेट",
      switched: "वॉलेट बदला गया",
      receive: "प्राप्त करें",
      send: "भेजें",
      ousd: "OUSD",
    },
    send: {
      title: "भेजें",
      to: "प्राप्तकर्ता",
      from: "प्रेषक",
      review: "समीक्षा",
      confirm: "भेजने की पुष्टि करें",
    },
    receive: {
      title: "प्राप्त करें",
      shareAddress: "अपना पता साझा करें",
      copyAddress: "पता कॉपी करें",
    },
    swap: {
      title: "स्वैप",
      youPay: "आप भुगतान करते हैं",
      youReceive: "आप प्राप्त करते हैं",
      confirm: "स्वैप की पुष्टि करें",
    },
    auth: {
      signIn: "साइन इन",
      welcome: "OpenPay Pro में आपका स्वागत है",
    },
    tx: {
      confirm: "पुष्टि करें",
      success: "सफल",
      pending: "लंबित",
      failed: "विफल",
    },
  },

  id: {
    common: {
      appName: "OpenPay Pro",
      loading: "Memuat…",
      save: "Simpan",
      cancel: "Batal",
      confirm: "Konfirmasi",
      continue: "Lanjutkan",
      back: "Kembali",
      close: "Tutup",
      done: "Selesai",
      search: "Cari",
      copy: "Salin",
      copied: "Disalin",
      max: "Maks",
      next: "Berikutnya",
      error: "Terjadi kesalahan",
      retry: "Coba lagi",
      signOut: "Keluar",
      active: "Aktif",
      amount: "Jumlah",
      balance: "Saldo",
      wallet: "Dompet",
      learnMore: "Pelajari lebih lanjut",
      notFound: "Halaman tidak ditemukan",
      notFoundDesc: "Rute itu tidak ada di OpenPay Pro Wallet.",
      goHome: "Ke beranda",
    },
    nav: {
      home: "Beranda",
      wallet: "Dompet",
      tokens: "Token",
      openToken: "OpenToken",
      history: "Riwayat",
      settings: "Pengaturan",
      liveChat: "Obrolan langsung",
      watchlist: "Daftar pantau",
      ledgerApi: "Ledger API",
      docs: "Dokumen OpenPay",
      faq: "FAQ",
      nfts: "Koleksi",
      send: "Kirim",
      receive: "Terima",
      swap: "Tukar",
      buy: "Beli",
      scan: "Pindai",
    },
    language: {
      title: "Bahasa tampilan",
      subtitle: "Pilih bahasa OpenPay Pro Anda",
      searchPlaceholder: "Cari bahasa",
      updated: "Bahasa diperbarui",
      current: "Bahasa saat ini",
    },
    settings: {
      title: "Pengaturan",
      account: "Akun",
      wallets: "Dompet",
      security: "Keamanan",
      preferences: "Preferensi",
      connected: "Terhubung",
      legal: "Legal",
      theme: "Tema",
      themeDesc: "Pilih tampilan OpenPay",
      light: "Terang",
      dark: "Gelap",
      currency: "Mata uang",
      currencyDesc: "Tampilkan nilai fiat dalam",
      language: "Bahasa",
      languageDesc: "Bahasa antarmuka",
      priceAlerts: "Peringatan harga",
      priceAlertsDesc: "Beritahu saat pergerakan besar",
      txAlerts: "Peringatan transaksi",
      txAlertsDesc: "Beritahu saat kirim, terima & isi ulang",
      lockPush: "Push layar kunci",
      lockPushDesc: "Notifikasi sistem saat ponsel terkunci atau aplikasi ditutup",
      emailAlerts: "Peringatan email",
      emailAlertsDesc: "Email saat Anda menerima atau mengirim dana",
      terms: "Ketentuan layanan",
      privacy: "Kebijakan privasi",
      regulatory: "Regulasi",
      signOutConfirm: "Keluar dari OpenPay Pro?",
      profile: "Profil",
      editProfile: "Edit profil",
      manageWallets: "Kelola dompet",
      biometric: "Buka kunci biometrik",
      pin: "PIN",
      recovery: "Frasa pemulihan",
    },
    dashboard: {
      title: "Beranda",
      tokens: "Token",
      collectibles: "Koleksi",
      activity: "Aktivitas terbaru",
      seeAll: "Lihat semua",
      send: "Kirim",
      receive: "Terima",
      swap: "Tukar",
      buy: "Beli",
      emptyTokens: "Belum ada token",
      emptyActivity: "Belum ada aktivitas",
    },
    buy: {
      title: "Beli",
      addOusd: "Tambahkan OUSD ke dompet Anda",
      amount: "Jumlah",
      payWith: "Bayar dengan",
      openpayBalance: "Saldo OpenPay",
      openpayDesc: "Bayar dari akun OpenPay terhubung · debit nyata",
      moonpay: "MoonPay",
      moonpayDesc: "Kartu / Apple Pay / Google Pay · MoonPay → OUSD",
      pi: "Pi Network (π)",
      piDesc: "Bayar dengan Pi · harga π langsung → OUSD ($1) langsung dikreditkan",
      usdc: "Bayar USDC",
      usdcDesc: "Bayar dengan USDC · MoonPay Commerce → OUSD",
      crypto: "Deposit kripto",
      cryptoDesc: "SOL / kripto · MoonPay Commerce → OUSD",
      confirmTitle: "Konfirmasi isi ulang",
      confirmDesc: "Tinjau pembelian OUSD Anda",
      youPay: "Anda membayar",
      rateNote: "1 OUSD = $1.00 · dikreditkan ke dompet aktif Anda",
      payOpenPay: "Bayar {{amount}} dengan OpenPay",
      buyMoonPay: "Beli dengan MoonPay · {{amount}}",
      depositCrypto: "Deposit {{amount}} kripto",
      payUsdc: "Bayar {{amount}} dengan USDC",
      topUp: "Isi ulang {{amount}}",
      connectOpenPay: "Hubungkan OpenPay untuk melanjutkan",
    },
    wallet: {
      title: "Dompet",
      mainWallet: "Dompet utama",
      myWallet: "Dompet saya",
      switched: "Dompet diganti",
      receive: "Terima",
      send: "Kirim",
      ousd: "OUSD",
    },
    send: {
      title: "Kirim",
      to: "Ke",
      from: "Dari",
      review: "Tinjau",
      confirm: "Konfirmasi pengiriman",
    },
    receive: {
      title: "Terima",
      shareAddress: "Bagikan alamat Anda",
      copyAddress: "Salin alamat",
    },
    swap: {
      title: "Tukar",
      youPay: "Anda membayar",
      youReceive: "Anda menerima",
      confirm: "Konfirmasi tukar",
    },
    auth: {
      signIn: "Masuk",
      welcome: "Selamat datang di OpenPay Pro",
    },
    tx: {
      confirm: "Konfirmasi",
      success: "Berhasil",
      pending: "Menunggu",
      failed: "Gagal",
    },
  },

  ms: {
    common: {
      appName: "OpenPay Pro",
      loading: "Memuatkan…",
      save: "Simpan",
      cancel: "Batal",
      confirm: "Sahkan",
      continue: "Teruskan",
      back: "Kembali",
      close: "Tutup",
      done: "Selesai",
      search: "Cari",
      copy: "Salin",
      copied: "Disalin",
      max: "Maks",
      next: "Seterusnya",
      error: "Sesuatu telah berlaku",
      retry: "Cuba lagi",
      signOut: "Log keluar",
      active: "Aktif",
      amount: "Jumlah",
      balance: "Baki",
      wallet: "Dompet",
      learnMore: "Ketahui lebih lanjut",
      notFound: "Halaman tidak dijumpai",
      notFoundDesc: "Laluan itu tidak wujud dalam OpenPay Pro Wallet.",
      goHome: "Pergi ke laman utama",
    },
    nav: {
      home: "Laman utama",
      wallet: "Dompet",
      tokens: "Token",
      openToken: "OpenToken",
      history: "Sejarah",
      settings: "Tetapan",
      liveChat: "Sembang langsung",
      watchlist: "Senarai pantau",
      ledgerApi: "Ledger API",
      docs: "Dokumen OpenPay",
      faq: "Soalan lazim",
      nfts: "Koleksi",
      send: "Hantar",
      receive: "Terima",
      swap: "Tukar",
      buy: "Beli",
      scan: "Imbas",
    },
    language: {
      title: "Bahasa paparan",
      subtitle: "Pilih bahasa OpenPay Pro anda",
      searchPlaceholder: "Cari bahasa",
      updated: "Bahasa dikemas kini",
      current: "Bahasa semasa",
    },
    settings: {
      title: "Tetapan",
      account: "Akaun",
      wallets: "Dompet",
      security: "Keselamatan",
      preferences: "Keutamaan",
      connected: "Disambungkan",
      legal: "Undang-undang",
      theme: "Tema",
      themeDesc: "Pilih rupa OpenPay",
      light: "Cerah",
      dark: "Gelap",
      currency: "Mata wang",
      currencyDesc: "Paparkan nilai fiat dalam",
      language: "Bahasa",
      languageDesc: "Bahasa antara muka",
      priceAlerts: "Makluman harga",
      priceAlertsDesc: "Maklumkan apabila pergerakan besar",
      txAlerts: "Makluman transaksi",
      txAlertsDesc: "Maklumkan untuk hantar, terima & tambah nilai",
      lockPush: "Tolak skrin kunci",
      lockPushDesc: "Pemberitahuan sistem apabila telefon dikunci atau aplikasi ditutup",
      emailAlerts: "Makluman e-mel",
      emailAlertsDesc: "E-mel apabila anda menerima atau menghantar dana",
      terms: "Terma perkhidmatan",
      privacy: "Dasar privasi",
      regulatory: "Kawalselia",
      signOutConfirm: "Log keluar daripada OpenPay Pro?",
      profile: "Profil",
      editProfile: "Edit profil",
      manageWallets: "Urus dompet",
      biometric: "Buka kunci biometrik",
      pin: "PIN",
      recovery: "Frasa pemulihan",
    },
    dashboard: {
      title: "Laman utama",
      tokens: "Token",
      collectibles: "Koleksi",
      activity: "Aktiviti terkini",
      seeAll: "Lihat semua",
      send: "Hantar",
      receive: "Terima",
      swap: "Tukar",
      buy: "Beli",
      emptyTokens: "Belum ada token",
      emptyActivity: "Belum ada aktiviti",
    },
    buy: {
      title: "Beli",
      addOusd: "Tambah OUSD ke dompet anda",
      amount: "Jumlah",
      payWith: "Bayar dengan",
      openpayBalance: "Baki OpenPay",
      openpayDesc: "Bayar dari akaun OpenPay tersambung · debit sebenar",
      moonpay: "MoonPay",
      moonpayDesc: "Kad / Apple Pay / Google Pay · MoonPay → OUSD",
      pi: "Pi Network (π)",
      piDesc: "Bayar dengan Pi · harga π langsung → OUSD ($1) dikredit serta-merta",
      usdc: "Bayar USDC",
      usdcDesc: "Bayar dengan USDC · MoonPay Commerce → OUSD",
      crypto: "Deposit kripto",
      cryptoDesc: "SOL / kripto · MoonPay Commerce → OUSD",
      confirmTitle: "Sahkan tambah nilai",
      confirmDesc: "Semak pembelian OUSD anda",
      youPay: "Anda bayar",
      rateNote: "1 OUSD = $1.00 · dikredit ke dompet aktif anda",
      payOpenPay: "Bayar {{amount}} dengan OpenPay",
      buyMoonPay: "Beli dengan MoonPay · {{amount}}",
      depositCrypto: "Deposit {{amount}} kripto",
      payUsdc: "Bayar {{amount}} dengan USDC",
      topUp: "Tambah nilai {{amount}}",
      connectOpenPay: "Sambungkan OpenPay untuk meneruskan",
    },
    wallet: {
      title: "Dompet",
      mainWallet: "Dompet utama",
      myWallet: "Dompet saya",
      switched: "Dompet ditukar",
      receive: "Terima",
      send: "Hantar",
      ousd: "OUSD",
    },
    send: {
      title: "Hantar",
      to: "Kepada",
      from: "Dari",
      review: "Semak",
      confirm: "Sahkan penghantaran",
    },
    receive: {
      title: "Terima",
      shareAddress: "Kongsi alamat anda",
      copyAddress: "Salin alamat",
    },
    swap: {
      title: "Tukar",
      youPay: "Anda bayar",
      youReceive: "Anda terima",
      confirm: "Sahkan tukar",
    },
    auth: {
      signIn: "Log masuk",
      welcome: "Selamat datang ke OpenPay Pro",
    },
    tx: {
      confirm: "Sahkan",
      success: "Berjaya",
      pending: "Menunggu",
      failed: "Gagal",
    },
  },
};
