/** Part D: partial packs — my, am, gu, ha, ig, pa, sw, ta, te, yo */
export default {
  my: {
    common: {
      appName: "OpenPay Pro",
      loading: "ဖွင့်နေသည်…",
      save: "သိမ်းမည်",
      cancel: "ပယ်ဖျက်",
      confirm: "အတည်ပြု",
      continue: "ဆက်လုပ်မည်",
      back: "နောက်သို့",
      close: "ပိတ်မည်",
      done: "ပြီးပြီ",
      search: "ရှာဖွေ",
      copy: "ကူးယူ",
      copied: "ကူးယူပြီး",
      max: "အများဆုံး",
      next: "ရှေ့သို့",
      error: "တစ်ခုခု မှားယွင်းနေသည်",
      retry: "ပြန်ကြိုးစား",
      signOut: "ထွက်မည်",
      active: "အသုံးပြုနေသည်",
      amount: "ပမာဏ",
      balance: "လက်ကျန်",
      wallet: "ပိုက်ဆံအိတ်",
      learnMore: "ပိုမိုလေ့လာရန်",
      notFound: "စာမျက်နှာ မတွေ့ပါ",
      notFoundDesc: "ထိုလမ်းကြောင်းသည် OpenPay Pro Wallet တွင် မရှိပါ။",
      goHome: "ပင်မသို့ သွားမည်",
    },
    nav: {
      home: "ပင်မ",
      wallet: "ပိုက်ဆံအိတ်",
      tokens: "တိုကင်များ",
      openToken: "OpenToken",
      history: "မှတ်တမ်း",
      settings: "ဆက်တင်များ",
      liveChat: "တိုက်ရိုက်ချတ်",
      watchlist: "စောင့်ကြည့်စာရင်း",
      ledgerApi: "Ledger API",
      docs: "OpenPay စာရွက်စာတမ်း",
      faq: "မေးလေ့ရှိသောမေးခွန်းများ",
      nfts: "စုဆောင်းပစ္စည်းများ",
      send: "ပို့မည်",
      receive: "လက်ခံမည်",
      swap: "လဲလှယ်မည်",
      buy: "ဝယ်မည်",
      scan: "စကန်ဖတ်မည်",
    },
    language: {
      title: "ပြသဘာသာစကား",
      subtitle: "သင့် OpenPay Pro ဘာသာစကားကို ရွေးပါ",
      searchPlaceholder: "ဘာသာစကားများ ရှာရန်",
      updated: "ဘာသာစကား အပ်ဒိတ်လုပ်ပြီး",
      current: "လက်ရှိဘာသာစကား",
    },
    settings: {
      title: "ဆက်တင်များ",
      account: "အကောင့်",
      wallets: "ပိုက်ဆံအိတ်များ",
      security: "လုံခြုံရေး",
      preferences: "ဦးစားပေးများ",
      connected: "ချိတ်ဆက်ပြီး",
      legal: "ဥပဒေရေးရာ",
      theme: "အပြင်အဆင်",
      themeDesc: "OpenPay ၏ အသွင်အပြင်ကို ရွေးပါ",
      light: "အလင်း",
      dark: "အမှောင်",
      currency: "ငွေကြေး",
      currencyDesc: "ဖီယတ်တန်ဖိုးကို ပြသမည့် ယူနစ်",
      language: "ဘာသာစကား",
      languageDesc: "မျက်နှာပြင်ဘာသာစကား",
      priceAlerts: "ဈေးနှုန်းသတိပေးချက်များ",
      priceAlertsDesc: "အကြီးအကျယ် ပြောင်းလဲမှုတွင် အကြောင်းကြားမည်",
      txAlerts: "ငွေလွှဲသတိပေးချက်များ",
      txAlertsDesc: "ပို့ခြင်း၊ လက်ခံခြင်းနှင့် ငွေဖြည့်ခြင်းတွင် အကြောင်းကြားမည်",
      lockPush: "လော့ခ်စခရင် ပုရှ်",
      lockPushDesc: "ဖုန်းလော့ခ် သို့မဟုတ် အက်ပ်ပိတ်နေစဉ် စနစ်အကြောင်းကြားချက်များ",
      emailAlerts: "အီးမေးလ်သတိပေးချက်များ",
      emailAlertsDesc: "ငွေလက်ခံ သို့မဟုတ် ပို့သောအခါ အီးမေးလ်",
      terms: "ဝန်ဆောင်မှုစည်းကမ်းများ",
      privacy: "ကိုယ်ရေးကိုယ်တာမူဝါဒ",
      regulatory: "စည်းမျဉ်းဆိုင်ရာ",
      signOutConfirm: "OpenPay Pro မှ ထွက်မလား?",
      profile: "ပရိုဖိုင်",
      editProfile: "ပရိုဖိုင် ပြင်ဆင်မည်",
      manageWallets: "ပိုက်ဆံအိတ်များ စီမံမည်",
      biometric: "ဇီဝမက်ထရစ် သော့ဖွင့်ခြင်း",
      pin: "PIN",
      recovery: "ပြန်လည်ရယူရေး စကားစု",
    },
    dashboard: {
      title: "ပင်မ",
      tokens: "တိုကင်များ",
      collectibles: "စုဆောင်းပစ္စည်းများ",
      activity: "မကြာသေးမီ လှုပ်ရှားမှု",
      seeAll: "အားလုံးကြည့်မည်",
      send: "ပို့မည်",
      receive: "လက်ခံမည်",
      swap: "လဲလှယ်မည်",
      buy: "ဝယ်မည်",
      emptyTokens: "တိုကင် မရှိသေးပါ",
      emptyActivity: "လှုပ်ရှားမှု မရှိသေးပါ",
    },
    buy: {
      title: "ဝယ်မည်",
      addOusd: "သင့်ပိုက်ဆံအိတ်သို့ OUSD ထည့်မည်",
      amount: "ပမာဏ",
      payWith: "ဖြင့် ပေးချေမည်",
      openpayBalance: "OpenPay လက်ကျန်",
      openpayDesc: "ချိတ်ဆက်ထားသော OpenPay အကောင့်မှ ပေးချေ · အမှန်တကယ် နုတ်ယူမှု",
      moonpay: "MoonPay",
      moonpayDesc: "ကတ် / Apple Pay / Google Pay · MoonPay → OUSD",
      pi: "Pi Network (π)",
      piDesc: "Pi ဖြင့် ပေးချေ · တိုက်ရိုက် π ဈေးနှုန်း → OUSD ($1) ချက်ချင်း ထည့်သွင်း",
      usdc: "USDC ပေးချေမှု",
      usdcDesc: "USDC ဖြင့် ပေးချေ · MoonPay Commerce → OUSD",
      crypto: "ခရစ်ပတို ငွေသွင်း",
      cryptoDesc: "SOL / ခရစ်ပတို · MoonPay Commerce → OUSD",
      confirmTitle: "ငွေဖြည့်မှု အတည်ပြု",
      confirmDesc: "သင့် OUSD ဝယ်ယူမှုကို စစ်ဆေးပါ",
      youPay: "သင်ပေးချေမည်",
      rateNote: "1 OUSD = $1.00 · သင့်အသုံးပြုနေသော ပိုက်ဆံအိတ်သို့ ထည့်သွင်း",
      payOpenPay: "OpenPay ဖြင့် {{amount}} ပေးချေမည်",
      buyMoonPay: "MoonPay ဖြင့် ဝယ်မည် · {{amount}}",
      depositCrypto: "{{amount}} ခရစ်ပတို သွင်းမည်",
      payUsdc: "USDC ဖြင့် {{amount}} ပေးချေမည်",
      topUp: "{{amount}} ငွေဖြည့်မည်",
      connectOpenPay: "ဆက်လုပ်ရန် OpenPay ချိတ်ဆက်ပါ",
    },
    wallet: {
      title: "ပိုက်ဆံအိတ်",
      mainWallet: "ပင်မပိုက်ဆံအိတ်",
      myWallet: "ကျွန်ုပ်၏ ပိုက်ဆံအိတ်",
      switched: "ပိုက်ဆံအိတ် ပြောင်းပြီး",
      receive: "လက်ခံမည်",
      send: "ပို့မည်",
      ousd: "OUSD",
    },
  },

  am: {
    common: {
      appName: "OpenPay Pro",
      loading: "በመጫን ላይ…",
      save: "አስቀምጥ",
      cancel: "ሰርዝ",
      confirm: "አረጋግጥ",
      continue: "ቀጥል",
      back: "ተመለስ",
      close: "ዝጋ",
      done: "ተጠናቅቋል",
      search: "ፈልግ",
      copy: "ቅዳ",
      copied: "ተቀድቷል",
      max: "ከፍተኛ",
      next: "ቀጣይ",
      error: "የሆነ ነገር ተሳስቷል",
      retry: "እንደገና ሞክር",
      signOut: "ውጣ",
      active: "ንቁ",
      amount: "መጠን",
      balance: "ቀሪ ሂሳብ",
      wallet: "ዋሌት",
      learnMore: "ተጨማሪ ይማሩ",
      notFound: "ገጹ አልተገኘም",
      notFoundDesc: "ያ መንገድ በ OpenPay Pro Wallet ውስጥ የለም።",
      goHome: "ወደ መነሻ ሂድ",
    },
    nav: {
      home: "መነሻ",
      wallet: "ዋሌት",
      tokens: "ቶከኖች",
      openToken: "OpenToken",
      history: "ታሪክ",
      settings: "ቅንብሮች",
      liveChat: "ቀጥታ ውይይት",
      watchlist: "የክትትል ዝርዝር",
      ledgerApi: "Ledger API",
      docs: "የ OpenPay ሰነዶች",
      faq: "ተደጋጋሚ ጥያቄዎች",
      nfts: "ስብስቦች",
      send: "ላክ",
      receive: "ተቀበል",
      swap: "ቀይር",
      buy: "ግዛ",
      scan: "ስካን",
    },
    language: {
      title: "የማሳያ ቋንቋ",
      subtitle: "የ OpenPay Pro ቋንቋዎን ይምረጡ",
      searchPlaceholder: "ቋንቋዎችን ፈልግ",
      updated: "ቋንቋ ተዘምኗል",
      current: "አሁን ያለ ቋንቋ",
    },
    settings: {
      title: "ቅንብሮች",
      account: "መለያ",
      wallets: "ዋሌቶች",
      security: "ደህንነት",
      preferences: "ምርጫዎች",
      connected: "ተገናኝቷል",
      legal: "ሕጋዊ",
      theme: "ገጽታ",
      themeDesc: "OpenPay እንዴት እንደሚታይ ይምረጡ",
      light: "ብርሃን",
      dark: "ጨለማ",
      currency: "ምንዛሬ",
      currencyDesc: "የፊያት እሴቶችን አሳይ በ",
      language: "ቋንቋ",
      languageDesc: "የበይነገጽ ቋንቋ",
      priceAlerts: "የዋጋ ማስጠንቀቂያዎች",
      priceAlertsDesc: "በትላልቅ እንቅስቃሴዎች ላይ አሳውቅ",
      txAlerts: "የግብይት ማስጠንቀቂያዎች",
      txAlertsDesc: "በመላክ፣ መቀበል እና መሙላት ላይ አሳውቅ",
      lockPush: "የመቆለፊያ ማያ ገጽ ግፊት",
      lockPushDesc: "ስልኩ ሲቆለፍ ወይም መተግበሪያ ሲዘጋ የስርዓት ማሳወቂያዎች",
      emailAlerts: "የኢሜይል ማስጠንቀቂያዎች",
      emailAlertsDesc: "ገንዘብ ሲቀበሉ ወይም ሲልኩ ኢሜይል",
      terms: "የአገልግሎት ውሎች",
      privacy: "የግላዊነት ፖሊሲ",
      regulatory: "ደንባዊ",
      signOutConfirm: "ከ OpenPay Pro ይውጡ?",
      profile: "መገለጫ",
      editProfile: "መገለጫ አርትዕ",
      manageWallets: "ዋሌቶችን አስተዳድር",
      biometric: "ባዮሜትሪክ መክፈቻ",
      pin: "PIN",
      recovery: "የመልሶ ማግኛ ሐረግ",
    },
    dashboard: {
      title: "መነሻ",
      tokens: "ቶከኖች",
      collectibles: "ስብስቦች",
      activity: "የቅርብ ጊዜ እንቅስቃሴ",
      seeAll: "ሁሉንም ይመልከቱ",
      send: "ላክ",
      receive: "ተቀበል",
      swap: "ቀይር",
      buy: "ግዛ",
      emptyTokens: "እስካሁን ቶከኖች የሉም",
      emptyActivity: "እስካሁን እንቅስቃሴ የለም",
    },
    buy: {
      title: "ግዛ",
      addOusd: "OUSD ወደ ዋሌትዎ ያክሉ",
      amount: "መጠን",
      payWith: "ይክፈሉ በ",
      openpayBalance: "የ OpenPay ቀሪ ሂሳብ",
      openpayDesc: "ከተገናኘው OpenPay መለያ ይክፈሉ · እውነተኛ ዴቢት",
      moonpay: "MoonPay",
      moonpayDesc: "ካርድ / Apple Pay / Google Pay · MoonPay → OUSD",
      pi: "Pi Network (π)",
      piDesc: "በ Pi ይክፈሉ · የቀጥታ π ዋጋ → OUSD ($1) ወዲያውኑ ይገባል",
      usdc: "USDC ክፍያ",
      usdcDesc: "በ USDC ይክፈሉ · MoonPay Commerce → OUSD",
      crypto: "ክሪፕቶ ተቀማጭ",
      cryptoDesc: "SOL / ክሪፕቶ · MoonPay Commerce → OUSD",
      confirmTitle: "መሙላትን አረጋግጥ",
      confirmDesc: "የ OUSD ግዢዎን ይገምግሙ",
      youPay: "እርስዎ ይከፍላሉ",
      rateNote: "1 OUSD = $1.00 · ወደ ንቁ ዋሌትዎ ይገባል",
      payOpenPay: "{{amount}} በ OpenPay ይክፈሉ",
      buyMoonPay: "በ MoonPay ይግዙ · {{amount}}",
      depositCrypto: "{{amount}} ክሪፕቶ ያስቀምጡ",
      payUsdc: "{{amount}} በ USDC ይክፈሉ",
      topUp: "{{amount}} ይሙሉ",
      connectOpenPay: "ለመቀጠል OpenPayን ያገናኙ",
    },
    wallet: {
      title: "ዋሌት",
      mainWallet: "ዋና ዋሌት",
      myWallet: "የእኔ ዋሌት",
      switched: "ዋሌት ተቀይሯል",
      receive: "ተቀበል",
      send: "ላክ",
      ousd: "OUSD",
    },
  },

  gu: {
    common: {
      appName: "OpenPay Pro",
      loading: "લોડ થઈ રહ્યું છે…",
      save: "સાચવો",
      cancel: "રદ કરો",
      confirm: "પુષ્ટિ કરો",
      continue: "ચાલુ રાખો",
      back: "પાછળ",
      close: "બંધ કરો",
      done: "થઈ ગયું",
      search: "શોધો",
      copy: "કૉપિ કરો",
      copied: "કૉપિ થયું",
      max: "મહત્તમ",
      next: "આગળ",
      error: "કંઈક ખોટું થયું",
      retry: "ફરી પ્રયાસ કરો",
      signOut: "સાઇન આઉટ",
      active: "સક્રિય",
      amount: "રકમ",
      balance: "બેલેન્સ",
      wallet: "વૉલેટ",
      learnMore: "વધુ જાણો",
      notFound: "પૃષ્ઠ મળ્યું નથી",
      notFoundDesc: "તે રૂટ OpenPay Pro Walletમાં અસ્તિત્વમાં નથી.",
      goHome: "હોમ પર જાઓ",
    },
    nav: {
      home: "હોમ",
      wallet: "વૉલેટ",
      tokens: "ટોકન્સ",
      openToken: "OpenToken",
      history: "ઇતિહાસ",
      settings: "સેટિંગ્સ",
      liveChat: "લાઇવ ચેટ",
      watchlist: "વૉચલિસ્ટ",
      ledgerApi: "Ledger API",
      docs: "OpenPay ડૉક્સ",
      faq: "FAQ",
      nfts: "કલેક્ટિબલ્સ",
      send: "મોકલો",
      receive: "પ્રાપ્ત કરો",
      swap: "સ્વૅપ",
      buy: "ખરીદો",
      scan: "સ્કેન",
    },
    language: {
      title: "પ્રદર્શન ભાષા",
      subtitle: "તમારી OpenPay Pro ભાષા પસંદ કરો",
      searchPlaceholder: "ભાષાઓ શોધો",
      updated: "ભાષા અપડેટ થઈ",
      current: "વર્તમાન ભાષા",
    },
    settings: {
      title: "સેટિંગ્સ",
      account: "એકાઉન્ટ",
      wallets: "વૉલેટ્સ",
      security: "સુરક્ષા",
      preferences: "પસંદગીઓ",
      connected: "કનેક્ટેડ",
      legal: "કાનૂની",
      theme: "થીમ",
      themeDesc: "OpenPay કેવું દેખાય તે પસંદ કરો",
      light: "લાઇટ",
      dark: "ડાર્ક",
      currency: "ચલણ",
      currencyDesc: "ફિયેટ મૂલ્યો આમાં બતાવો",
      language: "ભાષા",
      languageDesc: "ઇન્ટરફેસ ભાષા",
      priceAlerts: "કિંમત અલર્ટ્સ",
      priceAlertsDesc: "મોટા ફેરફારો પર સૂચના આપો",
      txAlerts: "વ્યવહાર અલર્ટ્સ",
      txAlertsDesc: "મોકલવા, પ્રાપ્ત કરવા અને ટૉપ-અપ પર સૂચના આપો",
      lockPush: "લૉક-સ્ક્રીન પુશ",
      lockPushDesc: "ફોન લૉક અથવા એપ બંધ હોય ત્યારે સિસ્ટમ સૂચનાઓ",
      emailAlerts: "ઇમેઇલ અલર્ટ્સ",
      emailAlertsDesc: "ફંડ પ્રાપ્ત અથવા મોકલતી વખતે ઇમેઇલ",
      terms: "સેવાની શરતો",
      privacy: "ગોપનીયતા નીતિ",
      regulatory: "નિયમનકારી",
      signOutConfirm: "OpenPay Proમાંથી સાઇન આઉટ કરો?",
      profile: "પ્રોફાઇલ",
      editProfile: "પ્રોફાઇલ સંપાદિત કરો",
      manageWallets: "વૉલેટ્સ મેનેજ કરો",
      biometric: "બાયોમેટ્રિક અનલૉક",
      pin: "PIN",
      recovery: "રિકવરી ફ્રેઝ",
    },
    dashboard: {
      title: "હોમ",
      tokens: "ટોકન્સ",
      collectibles: "કલેક્ટિબલ્સ",
      activity: "તાજેતરની પ્રવૃત્તિ",
      seeAll: "બધું જુઓ",
      send: "મોકલો",
      receive: "પ્રાપ્ત કરો",
      swap: "સ્વૅપ",
      buy: "ખરીદો",
      emptyTokens: "હજુ કોઈ ટોકન નથી",
      emptyActivity: "હજુ કોઈ પ્રવૃત્તિ નથી",
    },
    buy: {
      title: "ખરીદો",
      addOusd: "તમારા વૉલેટમાં OUSD ઉમેરો",
      amount: "રકમ",
      payWith: "સાથે ચૂકવો",
      openpayBalance: "OpenPay બેલેન્સ",
      openpayDesc: "તમારા કનેક્ટેડ OpenPay એકાઉન્ટમાંથી ચૂકવો · વાસ્તવિક ડેબિટ",
      moonpay: "MoonPay",
      moonpayDesc: "કાર્ડ / Apple Pay / Google Pay · MoonPay → OUSD",
      pi: "Pi Network (π)",
      piDesc: "Pi સાથે ચૂકવો · લાઇવ π કિંમત → OUSD ($1) તુરંત જમા",
      usdc: "USDC પે",
      usdcDesc: "USDC સાથે ચૂકવો · MoonPay Commerce → OUSD",
      crypto: "ક્રિપ્ટો ડિપોઝિટ",
      cryptoDesc: "SOL / ક્રિપ્ટો · MoonPay Commerce → OUSD",
      confirmTitle: "ટૉપ-અપની પુષ્ટિ કરો",
      confirmDesc: "તમારી OUSD ખરીદીની સમીક્ષા કરો",
      youPay: "તમે ચૂકવો છો",
      rateNote: "1 OUSD = $1.00 · તમારા સક્રિય વૉલેટમાં જમા",
      payOpenPay: "OpenPay સાથે {{amount}} ચૂકવો",
      buyMoonPay: "MoonPay સાથે ખરીદો · {{amount}}",
      depositCrypto: "{{amount}} ક્રિપ્ટો જમા કરો",
      payUsdc: "USDC સાથે {{amount}} ચૂકવો",
      topUp: "{{amount}} ટૉપ અપ કરો",
      connectOpenPay: "ચાલુ રાખવા માટે OpenPay કનેક્ટ કરો",
    },
    wallet: {
      title: "વૉલેટ",
      mainWallet: "મુખ્ય વૉલેટ",
      myWallet: "મારું વૉલેટ",
      switched: "વૉલેટ બદલાયું",
      receive: "પ્રાપ્ત કરો",
      send: "મોકલો",
      ousd: "OUSD",
    },
  },

  ha: {
    common: {
      appName: "OpenPay Pro",
      loading: "Ana lodawa…",
      save: "Ajiye",
      cancel: "Soke",
      confirm: "Tabbatar",
      continue: "Ci gaba",
      back: "Baya",
      close: "Rufe",
      done: "An gama",
      search: "Nema",
      copy: "Kwafi",
      copied: "An kwafi",
      max: "Mafi yawa",
      next: "Na gaba",
      error: "Wani abu ya yi kuskure",
      retry: "Sake gwadawa",
      signOut: "Fita",
      active: "Aiki",
      amount: "Adadi",
      balance: "Ma'auni",
      wallet: "Wallet",
      learnMore: "Ƙara koyo",
      notFound: "Ba a sami shafi ba",
      notFoundDesc: "Wannan hanyar babu ta a OpenPay Pro Wallet.",
      goHome: "Je gida",
    },
    nav: {
      home: "Gida",
      wallet: "Wallet",
      tokens: "Tokens",
      openToken: "OpenToken",
      history: "Tarihi",
      settings: "Saiti",
      liveChat: "Hira kai tsaye",
      watchlist: "Jerin kallo",
      ledgerApi: "Ledger API",
      docs: "Takardun OpenPay",
      faq: "Tambayoyi",
      nfts: "Tarin kaya",
      send: "Aika",
      receive: "Karɓa",
      swap: "Musanya",
      buy: "Saya",
      scan: "Skan",
    },
    language: {
      title: "Harshen nunawa",
      subtitle: "Zaɓi harshen OpenPay Pro naka",
      searchPlaceholder: "Nemo harsuna",
      updated: "An sabunta harshe",
      current: "Harshen yanzu",
    },
    settings: {
      title: "Saiti",
      account: "Asusun",
      wallets: "Wallets",
      security: "Tsaro",
      preferences: "Zaɓuɓɓuka",
      connected: "An haɗa",
      legal: "Shari'a",
      theme: "Jigo",
      themeDesc: "Zaɓi yadda OpenPay yake bayyana",
      light: "Haske",
      dark: "Duhu",
      currency: "Kuɗi",
      currencyDesc: "Nuna ƙimar fiat a",
      language: "Harshe",
      languageDesc: "Harshen interface",
      priceAlerts: "Faɗakarwar farashi",
      priceAlertsDesc: "Sanar da manyan motsi",
      txAlerts: "Faɗakarwar ma'amala",
      txAlertsDesc: "Sanar da aikawa, karɓa da cikawa",
      lockPush: "Push na allon kulle",
      lockPushDesc: "Sanarwar tsarin lokacin da wayar ke kulle ko an rufe app",
      emailAlerts: "Faɗakarwar imel",
      emailAlertsDesc: "Imel lokacin da ka karɓa ko aika kuɗi",
      terms: "Sharuɗɗan sabis",
      privacy: "Manufar sirri",
      regulatory: "Tsari",
      signOutConfirm: "Fita daga OpenPay Pro?",
      profile: "Bayanan martaba",
      editProfile: "Gyara bayanan martaba",
      manageWallets: "Sarrafa wallets",
      biometric: "Buɗe biometric",
      pin: "PIN",
      recovery: "Kalmar farfaɗowa",
    },
    dashboard: {
      title: "Gida",
      tokens: "Tokens",
      collectibles: "Tarin kaya",
      activity: "Ayyukan kwanan nan",
      seeAll: "Duba duka",
      send: "Aika",
      receive: "Karɓa",
      swap: "Musanya",
      buy: "Saya",
      emptyTokens: "Babu tokens tukuna",
      emptyActivity: "Babu aiki tukuna",
    },
    buy: {
      title: "Saya",
      addOusd: "Ƙara OUSD zuwa wallet ɗinka",
      amount: "Adadi",
      payWith: "Biya da",
      openpayBalance: "Ma'aunin OpenPay",
      openpayDesc: "Biya daga asusun OpenPay da aka haɗa · ainihin debit",
      moonpay: "MoonPay",
      moonpayDesc: "Kati / Apple Pay / Google Pay · MoonPay → OUSD",
      pi: "Pi Network (π)",
      piDesc: "Biya da Pi · farashin π kai tsaye → OUSD ($1) ana ƙididdigewa nan take",
      usdc: "Biyan USDC",
      usdcDesc: "Biya da USDC · MoonPay Commerce → OUSD",
      crypto: "Ajiyar crypto",
      cryptoDesc: "SOL / crypto · MoonPay Commerce → OUSD",
      confirmTitle: "Tabbatar da cikawa",
      confirmDesc: "Duba sayen OUSD ɗinka",
      youPay: "Kana biya",
      rateNote: "1 OUSD = $1.00 · ana ƙididdigewa zuwa wallet ɗinka mai aiki",
      payOpenPay: "Biya {{amount}} da OpenPay",
      buyMoonPay: "Saya da MoonPay · {{amount}}",
      depositCrypto: "Ajiye {{amount}} crypto",
      payUsdc: "Biya {{amount}} da USDC",
      topUp: "Cika {{amount}}",
      connectOpenPay: "Haɗa OpenPay don ci gaba",
    },
    wallet: {
      title: "Wallet",
      mainWallet: "Babban wallet",
      myWallet: "Wallet dina",
      switched: "An canza wallet",
      receive: "Karɓa",
      send: "Aika",
      ousd: "OUSD",
    },
  },

  ig: {
    common: {
      appName: "OpenPay Pro",
      loading: "Na-ebugo…",
      save: "Chekwaa",
      cancel: "Kagbuo",
      confirm: "Kwenye",
      continue: "Gaa n'ihu",
      back: "Laghachi",
      close: "Mechie",
      done: "Emechaala",
      search: "Chọọ",
      copy: "Detuo",
      copied: "Edetuola",
      max: "Kachasị",
      next: "Osote",
      error: "Ọ nwere ihe mere n'ụzọ ọjọọ",
      retry: "Nwaa ọzọ",
      signOut: "Pụọ",
      active: "Na-arụ ọrụ",
      amount: "Ọnụ ego",
      balance: "Nguzo",
      wallet: "Akpa ego",
      learnMore: "Mụtakwuo",
      notFound: "Ahụghị ibe",
      notFoundDesc: "Ụzọ ahụ adịghị na OpenPay Pro Wallet.",
      goHome: "Gaa n'ụlọ",
    },
    nav: {
      home: "Ụlọ",
      wallet: "Akpa ego",
      tokens: "Token",
      openToken: "OpenToken",
      history: "Akụkọ ihe mere eme",
      settings: "Ntọala",
      liveChat: "Mkparịta ụka dị ndụ",
      watchlist: "Ndepụta nlele",
      ledgerApi: "Ledger API",
      docs: "Akwụkwọ OpenPay",
      faq: "Ajụjụ",
      nfts: "Ihe nchịkọta",
      send: "Zipu",
      receive: "Nata",
      swap: "Gbanwee",
      buy: "Zụta",
      scan: "Nyochaa",
    },
    language: {
      title: "Asụsụ ngosi",
      subtitle: "Họrọ asụsụ OpenPay Pro gị",
      searchPlaceholder: "Chọọ asụsụ",
      updated: "Emelitere asụsụ",
      current: "Asụsụ dị ugbu a",
    },
    settings: {
      title: "Ntọala",
      account: "Akaụntụ",
      wallets: "Akpa ego",
      security: "Nchekwa",
      preferences: "Mmasị",
      connected: "Ejikọtara",
      legal: "Iwu",
      theme: "Isiokwu",
      themeDesc: "Họrọ otú OpenPay si adị",
      light: "Ìhè",
      dark: "Ọchịchịrị",
      currency: "Ego",
      currencyDesc: "Gosi ụkpụrụ fiat na",
      language: "Asụsụ",
      languageDesc: "Asụsụ interface",
      priceAlerts: "Ịdọ aka ná ntị ọnụahịa",
      priceAlertsDesc: "Gwa mgbe nnukwu mmegharị",
      txAlerts: "Ịdọ aka ná ntị azụmahịa",
      txAlertsDesc: "Gwa na izipu, nnata na nkwado",
      lockPush: "Push ihuenyo mkpọchi",
      lockPushDesc: "Ọkwa sistemụ mgbe ekwentị kpochiri ma ọ bụ mechie app",
      emailAlerts: "Ịdọ aka ná ntị email",
      emailAlertsDesc: "Email mgbe ị natara ma ọ bụ zipụ ego",
      terms: "Usoro ọrụ",
      privacy: "Amụma nzuzo",
      regulatory: "Nchịkwa",
      signOutConfirm: "Pụọ na OpenPay Pro?",
      profile: "Profaịlụ",
      editProfile: "Dezie profaịlụ",
      manageWallets: "Jikwaa akpa ego",
      biometric: "Mmeghe biometric",
      pin: "PIN",
      recovery: "Ahịrịokwu nkwụghachi",
    },
    dashboard: {
      title: "Ụlọ",
      tokens: "Token",
      collectibles: "Ihe nchịkọta",
      activity: "Ọrụ na nso nso a",
      seeAll: "Lee ha niile",
      send: "Zipu",
      receive: "Nata",
      swap: "Gbanwee",
      buy: "Zụta",
      emptyTokens: "Enwebeghị token",
      emptyActivity: "Enwebeghị ọrụ",
    },
    buy: {
      title: "Zụta",
      addOusd: "Tinye OUSD n'akpa ego gị",
      amount: "Ọnụ ego",
      payWith: "Kwụọ ụgwọ site na",
      openpayBalance: "Nguzo OpenPay",
      openpayDesc: "Kwụọ ụgwọ site na akaụntụ OpenPay ejikọtara · ezigbo debit",
      moonpay: "MoonPay",
      moonpayDesc: "Kaadị / Apple Pay / Google Pay · MoonPay → OUSD",
      pi: "Pi Network (π)",
      piDesc: "Kwụọ ụgwọ site na Pi · ọnụahịa π dị ndụ → OUSD ($1) na-abanye ozugbo",
      usdc: "Ịkwụ ụgwọ USDC",
      usdcDesc: "Kwụọ ụgwọ site na USDC · MoonPay Commerce → OUSD",
      crypto: "Nkwụnye crypto",
      cryptoDesc: "SOL / crypto · MoonPay Commerce → OUSD",
      confirmTitle: "Kwenye nkwado",
      confirmDesc: "Lelee ịzụta OUSD gị",
      youPay: "Ị na-akwụ",
      rateNote: "1 OUSD = $1.00 · a na-etinye n'akpa ego gị na-arụ ọrụ",
      payOpenPay: "Kwụọ {{amount}} site na OpenPay",
      buyMoonPay: "Zụta site na MoonPay · {{amount}}",
      depositCrypto: "Tinye {{amount}} crypto",
      payUsdc: "Kwụọ {{amount}} site na USDC",
      topUp: "Kwado {{amount}}",
      connectOpenPay: "Jikọọ OpenPay iji gaa n'ihu",
    },
    wallet: {
      title: "Akpa ego",
      mainWallet: "Akpa ego isi",
      myWallet: "Akpa ego m",
      switched: "Agbanweela akpa ego",
      receive: "Nata",
      send: "Zipu",
      ousd: "OUSD",
    },
  },
};
