/** Part C: th, vi, pt, tr, ar, fil, bn */
export default {
  th: {
    common: {
      appName: "OpenPay Pro",
      loading: "กำลังโหลด…",
      save: "บันทึก",
      cancel: "ยกเลิก",
      confirm: "ยืนยัน",
      continue: "ดำเนินการต่อ",
      back: "ย้อนกลับ",
      close: "ปิด",
      done: "เสร็จสิ้น",
      search: "ค้นหา",
      copy: "คัดลอก",
      copied: "คัดลอกแล้ว",
      max: "สูงสุด",
      next: "ถัดไป",
      error: "เกิดข้อผิดพลาด",
      retry: "ลองอีกครั้ง",
      signOut: "ออกจากระบบ",
      active: "ใช้งานอยู่",
      amount: "จำนวน",
      balance: "ยอดคงเหลือ",
      wallet: "กระเป๋าเงิน",
      learnMore: "เรียนรู้เพิ่มเติม",
      notFound: "ไม่พบหน้า",
      notFoundDesc: "เส้นทางนั้นไม่มีใน OpenPay Pro Wallet",
      goHome: "ไปหน้าแรก",
    },
    nav: {
      home: "หน้าแรก",
      wallet: "กระเป๋าเงิน",
      tokens: "โทเค็น",
      openToken: "OpenToken",
      history: "ประวัติ",
      settings: "การตั้งค่า",
      liveChat: "แชทสด",
      watchlist: "รายการติดตาม",
      ledgerApi: "Ledger API",
      docs: "เอกสาร OpenPay",
      faq: "คำถามที่พบบ่อย",
      nfts: "ของสะสม",
      send: "ส่ง",
      receive: "รับ",
      swap: "แลกเปลี่ยน",
      buy: "ซื้อ",
      scan: "สแกน",
    },
    language: {
      title: "ภาษาที่แสดง",
      subtitle: "เลือกภาษา OpenPay Pro ของคุณ",
      searchPlaceholder: "ค้นหาภาษา",
      updated: "อัปเดตภาษาแล้ว",
      current: "ภาษาปัจจุบัน",
    },
    settings: {
      title: "การตั้งค่า",
      account: "บัญชี",
      wallets: "กระเป๋าเงิน",
      security: "ความปลอดภัย",
      preferences: "การตั้งค่าส่วนตัว",
      connected: "เชื่อมต่อแล้ว",
      legal: "กฎหมาย",
      theme: "ธีม",
      themeDesc: "เลือกรูปลักษณ์ของ OpenPay",
      light: "สว่าง",
      dark: "มืด",
      currency: "สกุลเงิน",
      currencyDesc: "แสดงมูลค่าเงินเฟียตเป็น",
      language: "ภาษา",
      languageDesc: "ภาษาของอินเทอร์เฟซ",
      priceAlerts: "การแจ้งเตือนราคา",
      priceAlertsDesc: "แจ้งเมื่อมีการเคลื่อนไหวใหญ่",
      txAlerts: "การแจ้งเตือนธุรกรรม",
      txAlertsDesc: "แจ้งเมื่อส่ง รับ และเติมเงิน",
      lockPush: "พุชหน้าจอล็อก",
      lockPushDesc: "การแจ้งเตือนระบบเมื่อโทรศัพท์ล็อกหรือปิดแอป",
      emailAlerts: "การแจ้งเตือนอีเมล",
      emailAlertsDesc: "อีเมลเมื่อคุณรับหรือส่งเงิน",
      terms: "ข้อกำหนดการให้บริการ",
      privacy: "นโยบายความเป็นส่วนตัว",
      regulatory: "กฎระเบียบ",
      signOutConfirm: "ออกจากระบบ OpenPay Pro?",
      profile: "โปรไฟล์",
      editProfile: "แก้ไขโปรไฟล์",
      manageWallets: "จัดการกระเป๋าเงิน",
      biometric: "ปลดล็อกด้วยไบโอเมตริก",
      pin: "PIN",
      recovery: "วลีกู้คืน",
    },
    dashboard: {
      title: "หน้าแรก",
      tokens: "โทเค็น",
      collectibles: "ของสะสม",
      activity: "กิจกรรมล่าสุด",
      seeAll: "ดูทั้งหมด",
      send: "ส่ง",
      receive: "รับ",
      swap: "แลกเปลี่ยน",
      buy: "ซื้อ",
      emptyTokens: "ยังไม่มีโทเค็น",
      emptyActivity: "ยังไม่มีกิจกรรม",
    },
    buy: {
      title: "ซื้อ",
      addOusd: "เพิ่ม OUSD ไปยังกระเป๋าเงินของคุณ",
      amount: "จำนวน",
      payWith: "ชำระด้วย",
      openpayBalance: "ยอด OpenPay",
      openpayDesc: "ชำระจากบัญชี OpenPay ที่เชื่อมต่อ · หักจริง",
      moonpay: "MoonPay",
      moonpayDesc: "บัตร / Apple Pay / Google Pay · MoonPay → OUSD",
      pi: "Pi Network (π)",
      piDesc: "ชำระด้วย Pi · ราคา π สด → เครดิต OUSD ($1) ทันที",
      usdc: "ชำระด้วย USDC",
      usdcDesc: "ชำระด้วย USDC · MoonPay Commerce → OUSD",
      crypto: "ฝากคริปโต",
      cryptoDesc: "SOL / คริปโต · MoonPay Commerce → OUSD",
      confirmTitle: "ยืนยันการเติมเงิน",
      confirmDesc: "ตรวจสอบการซื้อ OUSD ของคุณ",
      youPay: "คุณจ่าย",
      rateNote: "1 OUSD = $1.00 · เครดิตไปยังกระเป๋าเงินที่ใช้งานอยู่",
      payOpenPay: "ชำระ {{amount}} ด้วย OpenPay",
      buyMoonPay: "ซื้อด้วย MoonPay · {{amount}}",
      depositCrypto: "ฝากคริปโต {{amount}}",
      payUsdc: "ชำระ {{amount}} ด้วย USDC",
      topUp: "เติมเงิน {{amount}}",
      connectOpenPay: "เชื่อมต่อ OpenPay เพื่อดำเนินการต่อ",
    },
    wallet: {
      title: "กระเป๋าเงิน",
      mainWallet: "กระเป๋าเงินหลัก",
      myWallet: "กระเป๋าเงินของฉัน",
      switched: "เปลี่ยนกระเป๋าเงินแล้ว",
      receive: "รับ",
      send: "ส่ง",
      ousd: "OUSD",
    },
    send: {
      title: "ส่ง",
      to: "ถึง",
      from: "จาก",
      review: "ตรวจสอบ",
      confirm: "ยืนยันการส่ง",
    },
    receive: {
      title: "รับ",
      shareAddress: "แชร์ที่อยู่ของคุณ",
      copyAddress: "คัดลอกที่อยู่",
    },
    swap: {
      title: "แลกเปลี่ยน",
      youPay: "คุณจ่าย",
      youReceive: "คุณได้รับ",
      confirm: "ยืนยันการแลกเปลี่ยน",
    },
    auth: {
      signIn: "เข้าสู่ระบบ",
      welcome: "ยินดีต้อนรับสู่ OpenPay Pro",
    },
    tx: {
      confirm: "ยืนยัน",
      success: "สำเร็จ",
      pending: "รอดำเนินการ",
      failed: "ล้มเหลว",
    },
  },

  vi: {
    common: {
      appName: "OpenPay Pro",
      loading: "Đang tải…",
      save: "Lưu",
      cancel: "Hủy",
      confirm: "Xác nhận",
      continue: "Tiếp tục",
      back: "Quay lại",
      close: "Đóng",
      done: "Xong",
      search: "Tìm kiếm",
      copy: "Sao chép",
      copied: "Đã sao chép",
      max: "Tối đa",
      next: "Tiếp",
      error: "Đã xảy ra lỗi",
      retry: "Thử lại",
      signOut: "Đăng xuất",
      active: "Đang hoạt động",
      amount: "Số tiền",
      balance: "Số dư",
      wallet: "Ví",
      learnMore: "Tìm hiểu thêm",
      notFound: "Không tìm thấy trang",
      notFoundDesc: "Tuyến đường đó không tồn tại trong OpenPay Pro Wallet.",
      goHome: "Về trang chủ",
    },
    nav: {
      home: "Trang chủ",
      wallet: "Ví",
      tokens: "Token",
      openToken: "OpenToken",
      history: "Lịch sử",
      settings: "Cài đặt",
      liveChat: "Trò chuyện trực tiếp",
      watchlist: "Danh sách theo dõi",
      ledgerApi: "Ledger API",
      docs: "Tài liệu OpenPay",
      faq: "Câu hỏi thường gặp",
      nfts: "Sưu tập",
      send: "Gửi",
      receive: "Nhận",
      swap: "Hoán đổi",
      buy: "Mua",
      scan: "Quét",
    },
    language: {
      title: "Ngôn ngữ hiển thị",
      subtitle: "Chọn ngôn ngữ OpenPay Pro của bạn",
      searchPlaceholder: "Tìm ngôn ngữ",
      updated: "Đã cập nhật ngôn ngữ",
      current: "Ngôn ngữ hiện tại",
    },
    settings: {
      title: "Cài đặt",
      account: "Tài khoản",
      wallets: "Ví",
      security: "Bảo mật",
      preferences: "Tùy chọn",
      connected: "Đã kết nối",
      legal: "Pháp lý",
      theme: "Giao diện",
      themeDesc: "Chọn giao diện OpenPay",
      light: "Sáng",
      dark: "Tối",
      currency: "Tiền tệ",
      currencyDesc: "Hiển thị giá trị fiat bằng",
      language: "Ngôn ngữ",
      languageDesc: "Ngôn ngữ giao diện",
      priceAlerts: "Cảnh báo giá",
      priceAlertsDesc: "Thông báo khi biến động lớn",
      txAlerts: "Cảnh báo giao dịch",
      txAlertsDesc: "Thông báo khi gửi, nhận và nạp tiền",
      lockPush: "Đẩy màn hình khóa",
      lockPushDesc: "Thông báo hệ thống khi điện thoại khóa hoặc ứng dụng đóng",
      emailAlerts: "Cảnh báo email",
      emailAlertsDesc: "Email khi bạn nhận hoặc gửi tiền",
      terms: "Điều khoản dịch vụ",
      privacy: "Chính sách quyền riêng tư",
      regulatory: "Quy định",
      signOutConfirm: "Đăng xuất khỏi OpenPay Pro?",
      profile: "Hồ sơ",
      editProfile: "Chỉnh sửa hồ sơ",
      manageWallets: "Quản lý ví",
      biometric: "Mở khóa sinh trắc học",
      pin: "PIN",
      recovery: "Cụm từ khôi phục",
    },
    dashboard: {
      title: "Trang chủ",
      tokens: "Token",
      collectibles: "Sưu tập",
      activity: "Hoạt động gần đây",
      seeAll: "Xem tất cả",
      send: "Gửi",
      receive: "Nhận",
      swap: "Hoán đổi",
      buy: "Mua",
      emptyTokens: "Chưa có token",
      emptyActivity: "Chưa có hoạt động",
    },
    buy: {
      title: "Mua",
      addOusd: "Thêm OUSD vào ví của bạn",
      amount: "Số tiền",
      payWith: "Thanh toán bằng",
      openpayBalance: "Số dư OpenPay",
      openpayDesc: "Thanh toán từ tài khoản OpenPay đã kết nối · ghi nợ thực",
      moonpay: "MoonPay",
      moonpayDesc: "Thẻ / Apple Pay / Google Pay · MoonPay → OUSD",
      pi: "Pi Network (π)",
      piDesc: "Thanh toán bằng Pi · giá π trực tiếp → OUSD ($1) được ghi có ngay",
      usdc: "Thanh toán USDC",
      usdcDesc: "Thanh toán bằng USDC · MoonPay Commerce → OUSD",
      crypto: "Nạp tiền mã hóa",
      cryptoDesc: "SOL / tiền mã hóa · MoonPay Commerce → OUSD",
      confirmTitle: "Xác nhận nạp tiền",
      confirmDesc: "Xem lại giao dịch mua OUSD của bạn",
      youPay: "Bạn trả",
      rateNote: "1 OUSD = $1.00 · ghi có vào ví đang hoạt động",
      payOpenPay: "Thanh toán {{amount}} bằng OpenPay",
      buyMoonPay: "Mua bằng MoonPay · {{amount}}",
      depositCrypto: "Nạp {{amount}} tiền mã hóa",
      payUsdc: "Thanh toán {{amount}} bằng USDC",
      topUp: "Nạp {{amount}}",
      connectOpenPay: "Kết nối OpenPay để tiếp tục",
    },
    wallet: {
      title: "Ví",
      mainWallet: "Ví chính",
      myWallet: "Ví của tôi",
      switched: "Đã chuyển ví",
      receive: "Nhận",
      send: "Gửi",
      ousd: "OUSD",
    },
    send: {
      title: "Gửi",
      to: "Đến",
      from: "Từ",
      review: "Xem lại",
      confirm: "Xác nhận gửi",
    },
    receive: {
      title: "Nhận",
      shareAddress: "Chia sẻ địa chỉ của bạn",
      copyAddress: "Sao chép địa chỉ",
    },
    swap: {
      title: "Hoán đổi",
      youPay: "Bạn trả",
      youReceive: "Bạn nhận",
      confirm: "Xác nhận hoán đổi",
    },
    auth: {
      signIn: "Đăng nhập",
      welcome: "Chào mừng đến OpenPay Pro",
    },
    tx: {
      confirm: "Xác nhận",
      success: "Thành công",
      pending: "Đang chờ",
      failed: "Thất bại",
    },
  },

  pt: {
    common: {
      appName: "OpenPay Pro",
      loading: "Carregando…",
      save: "Salvar",
      cancel: "Cancelar",
      confirm: "Confirmar",
      continue: "Continuar",
      back: "Voltar",
      close: "Fechar",
      done: "Concluído",
      search: "Pesquisar",
      copy: "Copiar",
      copied: "Copiado",
      max: "Máx.",
      next: "Próximo",
      error: "Algo deu errado",
      retry: "Tentar novamente",
      signOut: "Sair",
      active: "Ativo",
      amount: "Valor",
      balance: "Saldo",
      wallet: "Carteira",
      learnMore: "Saiba mais",
      notFound: "Página não encontrada",
      notFoundDesc: "Essa rota não existe no OpenPay Pro Wallet.",
      goHome: "Ir para o início",
    },
    nav: {
      home: "Início",
      wallet: "Carteira",
      tokens: "Tokens",
      openToken: "OpenToken",
      history: "Histórico",
      settings: "Configurações",
      liveChat: "Chat ao vivo",
      watchlist: "Lista de acompanhamento",
      ledgerApi: "Ledger API",
      docs: "Docs OpenPay",
      faq: "FAQ",
      nfts: "Colecionáveis",
      send: "Enviar",
      receive: "Receber",
      swap: "Trocar",
      buy: "Comprar",
      scan: "Escanear",
    },
    language: {
      title: "Idioma de exibição",
      subtitle: "Escolha o idioma do OpenPay Pro",
      searchPlaceholder: "Pesquisar idiomas",
      updated: "Idioma atualizado",
      current: "Idioma atual",
    },
    settings: {
      title: "Configurações",
      account: "Conta",
      wallets: "Carteiras",
      security: "Segurança",
      preferences: "Preferências",
      connected: "Conectado",
      legal: "Legal",
      theme: "Tema",
      themeDesc: "Escolha a aparência do OpenPay",
      light: "Claro",
      dark: "Escuro",
      currency: "Moeda",
      currencyDesc: "Exibir valores fiat em",
      language: "Idioma",
      languageDesc: "Idioma da interface",
      priceAlerts: "Alertas de preço",
      priceAlertsDesc: "Notificar em grandes movimentos",
      txAlerts: "Alertas de transação",
      txAlertsDesc: "Notificar em envios, recebimentos e recargas",
      lockPush: "Push na tela de bloqueio",
      lockPushDesc: "Notificações do sistema com o telefone bloqueado ou o app fechado",
      emailAlerts: "Alertas por e-mail",
      emailAlertsDesc: "E-mail quando você recebe ou envia fundos",
      terms: "Termos de serviço",
      privacy: "Política de privacidade",
      regulatory: "Regulatório",
      signOutConfirm: "Sair do OpenPay Pro?",
      profile: "Perfil",
      editProfile: "Editar perfil",
      manageWallets: "Gerenciar carteiras",
      biometric: "Desbloqueio biométrico",
      pin: "PIN",
      recovery: "Frase de recuperação",
    },
    dashboard: {
      title: "Início",
      tokens: "Tokens",
      collectibles: "Colecionáveis",
      activity: "Atividade recente",
      seeAll: "Ver tudo",
      send: "Enviar",
      receive: "Receber",
      swap: "Trocar",
      buy: "Comprar",
      emptyTokens: "Ainda não há tokens",
      emptyActivity: "Ainda não há atividade",
    },
    buy: {
      title: "Comprar",
      addOusd: "Adicione OUSD à sua carteira",
      amount: "Valor",
      payWith: "Pagar com",
      openpayBalance: "Saldo OpenPay",
      openpayDesc: "Pague da sua conta OpenPay conectada · débito real",
      moonpay: "MoonPay",
      moonpayDesc: "Cartão / Apple Pay / Google Pay · MoonPay → OUSD",
      pi: "Pi Network (π)",
      piDesc: "Pague com Pi · preço π ao vivo → OUSD ($1) creditado instantaneamente",
      usdc: "Pagamento USDC",
      usdcDesc: "Pague com USDC · MoonPay Commerce → OUSD",
      crypto: "Depósito cripto",
      cryptoDesc: "SOL / cripto · MoonPay Commerce → OUSD",
      confirmTitle: "Confirmar recarga",
      confirmDesc: "Revise sua compra de OUSD",
      youPay: "Você paga",
      rateNote: "1 OUSD = $1.00 · creditado na sua carteira ativa",
      payOpenPay: "Pagar {{amount}} com OpenPay",
      buyMoonPay: "Comprar com MoonPay · {{amount}}",
      depositCrypto: "Depositar {{amount}} em cripto",
      payUsdc: "Pagar {{amount}} com USDC",
      topUp: "Recarregar {{amount}}",
      connectOpenPay: "Conecte o OpenPay para continuar",
    },
    wallet: {
      title: "Carteira",
      mainWallet: "Carteira principal",
      myWallet: "Minha carteira",
      switched: "Carteira alterada",
      receive: "Receber",
      send: "Enviar",
      ousd: "OUSD",
    },
    send: {
      title: "Enviar",
      to: "Para",
      from: "De",
      review: "Revisar",
      confirm: "Confirmar envio",
    },
    receive: {
      title: "Receber",
      shareAddress: "Compartilhe seu endereço",
      copyAddress: "Copiar endereço",
    },
    swap: {
      title: "Trocar",
      youPay: "Você paga",
      youReceive: "Você recebe",
      confirm: "Confirmar troca",
    },
    auth: {
      signIn: "Entrar",
      welcome: "Bem-vindo ao OpenPay Pro",
    },
    tx: {
      confirm: "Confirmar",
      success: "Sucesso",
      pending: "Pendente",
      failed: "Falhou",
    },
  },

  tr: {
    common: {
      appName: "OpenPay Pro",
      loading: "Yükleniyor…",
      save: "Kaydet",
      cancel: "İptal",
      confirm: "Onayla",
      continue: "Devam",
      back: "Geri",
      close: "Kapat",
      done: "Tamam",
      search: "Ara",
      copy: "Kopyala",
      copied: "Kopyalandı",
      max: "Maks.",
      next: "İleri",
      error: "Bir şeyler yanlış gitti",
      retry: "Yeniden dene",
      signOut: "Çıkış yap",
      active: "Aktif",
      amount: "Tutar",
      balance: "Bakiye",
      wallet: "Cüzdan",
      learnMore: "Daha fazla bilgi",
      notFound: "Sayfa bulunamadı",
      notFoundDesc: "Bu rota OpenPay Pro Wallet'ta yok.",
      goHome: "Ana sayfaya git",
    },
    nav: {
      home: "Ana sayfa",
      wallet: "Cüzdan",
      tokens: "Tokenlar",
      openToken: "OpenToken",
      history: "Geçmiş",
      settings: "Ayarlar",
      liveChat: "Canlı sohbet",
      watchlist: "İzleme listesi",
      ledgerApi: "Ledger API",
      docs: "OpenPay Dokümanları",
      faq: "SSS",
      nfts: "Koleksiyonlar",
      send: "Gönder",
      receive: "Al",
      swap: "Takas",
      buy: "Satın al",
      scan: "Tara",
    },
    language: {
      title: "Görüntüleme dili",
      subtitle: "OpenPay Pro dilinizi seçin",
      searchPlaceholder: "Dil ara",
      updated: "Dil güncellendi",
      current: "Geçerli dil",
    },
    settings: {
      title: "Ayarlar",
      account: "Hesap",
      wallets: "Cüzdanlar",
      security: "Güvenlik",
      preferences: "Tercihler",
      connected: "Bağlı",
      legal: "Yasal",
      theme: "Tema",
      themeDesc: "OpenPay görünümünü seçin",
      light: "Açık",
      dark: "Koyu",
      currency: "Para birimi",
      currencyDesc: "Fiat değerlerini şu birimde göster",
      language: "Dil",
      languageDesc: "Arayüz dili",
      priceAlerts: "Fiyat uyarıları",
      priceAlertsDesc: "Büyük hareketlerde bildir",
      txAlerts: "İşlem uyarıları",
      txAlertsDesc: "Gönderme, alma ve yüklemelerde bildir",
      lockPush: "Kilit ekranı bildirimi",
      lockPushDesc: "Telefon kilitliyken veya uygulama kapalıyken sistem bildirimleri",
      emailAlerts: "E-posta uyarıları",
      emailAlertsDesc: "Fon aldığınızda veya gönderdiğinizde e-posta",
      terms: "Hizmet şartları",
      privacy: "Gizlilik politikası",
      regulatory: "Düzenleyici",
      signOutConfirm: "OpenPay Pro'dan çıkış yapılsın mı?",
      profile: "Profil",
      editProfile: "Profili düzenle",
      manageWallets: "Cüzdanları yönet",
      biometric: "Biyometrik kilit açma",
      pin: "PIN",
      recovery: "Kurtarma ifadesi",
    },
    dashboard: {
      title: "Ana sayfa",
      tokens: "Tokenlar",
      collectibles: "Koleksiyonlar",
      activity: "Son etkinlik",
      seeAll: "Tümünü gör",
      send: "Gönder",
      receive: "Al",
      swap: "Takas",
      buy: "Satın al",
      emptyTokens: "Henüz token yok",
      emptyActivity: "Henüz etkinlik yok",
    },
    buy: {
      title: "Satın al",
      addOusd: "Cüzdanınıza OUSD ekleyin",
      amount: "Tutar",
      payWith: "Ödeme yöntemi",
      openpayBalance: "OpenPay bakiyesi",
      openpayDesc: "Bağlı OpenPay hesabınızdan ödeyin · gerçek borçlandırma",
      moonpay: "MoonPay",
      moonpayDesc: "Kart / Apple Pay / Google Pay · MoonPay → OUSD",
      pi: "Pi Network (π)",
      piDesc: "Pi ile ödeyin · canlı π fiyatı → OUSD ($1) anında yatırılır",
      usdc: "USDC ödeme",
      usdcDesc: "USDC ile ödeyin · MoonPay Commerce → OUSD",
      crypto: "Kripto yatırımı",
      cryptoDesc: "SOL / kripto · MoonPay Commerce → OUSD",
      confirmTitle: "Yüklemeyi onayla",
      confirmDesc: "OUSD satın alımınızı gözden geçirin",
      youPay: "Ödediğiniz",
      rateNote: "1 OUSD = $1.00 · aktif cüzdanınıza yatırılır",
      payOpenPay: "OpenPay ile {{amount}} öde",
      buyMoonPay: "MoonPay ile satın al · {{amount}}",
      depositCrypto: "{{amount}} kripto yatır",
      payUsdc: "USDC ile {{amount}} öde",
      topUp: "{{amount}} yükle",
      connectOpenPay: "Devam etmek için OpenPay'i bağlayın",
    },
    wallet: {
      title: "Cüzdan",
      mainWallet: "Ana cüzdan",
      myWallet: "Cüzdanım",
      switched: "Cüzdan değiştirildi",
      receive: "Al",
      send: "Gönder",
      ousd: "OUSD",
    },
    send: {
      title: "Gönder",
      to: "Kime",
      from: "Kimden",
      review: "Gözden geçir",
      confirm: "Gönderimi onayla",
    },
    receive: {
      title: "Al",
      shareAddress: "Adresinizi paylaşın",
      copyAddress: "Adresi kopyala",
    },
    swap: {
      title: "Takas",
      youPay: "Ödediğiniz",
      youReceive: "Aldığınız",
      confirm: "Takası onayla",
    },
    auth: {
      signIn: "Giriş yap",
      welcome: "OpenPay Pro'ya hoş geldiniz",
    },
    tx: {
      confirm: "Onayla",
      success: "Başarılı",
      pending: "Beklemede",
      failed: "Başarısız",
    },
  },

  ar: {
    common: {
      appName: "OpenPay Pro",
      loading: "جارٍ التحميل…",
      save: "حفظ",
      cancel: "إلغاء",
      confirm: "تأكيد",
      continue: "متابعة",
      back: "رجوع",
      close: "إغلاق",
      done: "تم",
      search: "بحث",
      copy: "نسخ",
      copied: "تم النسخ",
      max: "الحد الأقصى",
      next: "التالي",
      error: "حدث خطأ ما",
      retry: "إعادة المحاولة",
      signOut: "تسجيل الخروج",
      active: "نشط",
      amount: "المبلغ",
      balance: "الرصيد",
      wallet: "المحفظة",
      learnMore: "معرفة المزيد",
      notFound: "الصفحة غير موجودة",
      notFoundDesc: "هذا المسار غير موجود في OpenPay Pro Wallet.",
      goHome: "العودة للرئيسية",
    },
    nav: {
      home: "الرئيسية",
      wallet: "المحفظة",
      tokens: "الرموز",
      openToken: "OpenToken",
      history: "السجل",
      settings: "الإعدادات",
      liveChat: "دردشة مباشرة",
      watchlist: "قائمة المتابعة",
      ledgerApi: "Ledger API",
      docs: "وثائق OpenPay",
      faq: "الأسئلة الشائعة",
      nfts: "المقتنيات",
      send: "إرسال",
      receive: "استلام",
      swap: "تبديل",
      buy: "شراء",
      scan: "مسح",
    },
    language: {
      title: "لغة العرض",
      subtitle: "اختر لغة OpenPay Pro",
      searchPlaceholder: "البحث عن اللغات",
      updated: "تم تحديث اللغة",
      current: "اللغة الحالية",
    },
    settings: {
      title: "الإعدادات",
      account: "الحساب",
      wallets: "المحافظ",
      security: "الأمان",
      preferences: "التفضيلات",
      connected: "متصل",
      legal: "قانوني",
      theme: "المظهر",
      themeDesc: "اختر مظهر OpenPay",
      light: "فاتح",
      dark: "داكن",
      currency: "العملة",
      currencyDesc: "عرض قيم العملات الورقية بـ",
      language: "اللغة",
      languageDesc: "لغة الواجهة",
      priceAlerts: "تنبيهات الأسعار",
      priceAlertsDesc: "إشعار عند التحركات الكبيرة",
      txAlerts: "تنبيهات المعاملات",
      txAlertsDesc: "إشعار عند الإرسال والاستلام والشحن",
      lockPush: "دفع شاشة القفل",
      lockPushDesc: "إشعارات النظام عند قفل الهاتف أو إغلاق التطبيق",
      emailAlerts: "تنبيهات البريد",
      emailAlertsDesc: "بريد إلكتروني عند استلام أو إرسال الأموال",
      terms: "شروط الخدمة",
      privacy: "سياسة الخصوصية",
      regulatory: "تنظيمي",
      signOutConfirm: "تسجيل الخروج من OpenPay Pro؟",
      profile: "الملف الشخصي",
      editProfile: "تعديل الملف الشخصي",
      manageWallets: "إدارة المحافظ",
      biometric: "فتح القفل البيومتري",
      pin: "PIN",
      recovery: "عبارة الاسترداد",
    },
    dashboard: {
      title: "الرئيسية",
      tokens: "الرموز",
      collectibles: "المقتنيات",
      activity: "النشاط الأخير",
      seeAll: "عرض الكل",
      send: "إرسال",
      receive: "استلام",
      swap: "تبديل",
      buy: "شراء",
      emptyTokens: "لا توجد رموز بعد",
      emptyActivity: "لا يوجد نشاط بعد",
    },
    buy: {
      title: "شراء",
      addOusd: "أضف OUSD إلى محفظتك",
      amount: "المبلغ",
      payWith: "الدفع بواسطة",
      openpayBalance: "رصيد OpenPay",
      openpayDesc: "ادفع من حساب OpenPay المتصل · خصم حقيقي",
      moonpay: "MoonPay",
      moonpayDesc: "بطاقة / Apple Pay / Google Pay · MoonPay → OUSD",
      pi: "Pi Network (π)",
      piDesc: "ادفع بـ Pi · سعر π المباشر → يُضاف OUSD ($1) فوراً",
      usdc: "دفع USDC",
      usdcDesc: "ادفع بـ USDC · MoonPay Commerce → OUSD",
      crypto: "إيداع عملات مشفرة",
      cryptoDesc: "SOL / عملات مشفرة · MoonPay Commerce → OUSD",
      confirmTitle: "تأكيد الشحن",
      confirmDesc: "راجع عملية شراء OUSD",
      youPay: "أنت تدفع",
      rateNote: "1 OUSD = $1.00 · يُضاف إلى محفظتك النشطة",
      payOpenPay: "ادفع {{amount}} عبر OpenPay",
      buyMoonPay: "اشترِ عبر MoonPay · {{amount}}",
      depositCrypto: "أودع {{amount}} من العملات المشفرة",
      payUsdc: "ادفع {{amount}} عبر USDC",
      topUp: "اشحن {{amount}}",
      connectOpenPay: "اربط OpenPay للمتابعة",
    },
    wallet: {
      title: "المحفظة",
      mainWallet: "المحفظة الرئيسية",
      myWallet: "محفظتي",
      switched: "تم تبديل المحفظة",
      receive: "استلام",
      send: "إرسال",
      ousd: "OUSD",
    },
    send: {
      title: "إرسال",
      to: "إلى",
      from: "من",
      review: "مراجعة",
      confirm: "تأكيد الإرسال",
    },
    receive: {
      title: "استلام",
      shareAddress: "شارك عنوانك",
      copyAddress: "نسخ العنوان",
    },
    swap: {
      title: "تبديل",
      youPay: "أنت تدفع",
      youReceive: "أنت تستلم",
      confirm: "تأكيد التبديل",
    },
    auth: {
      signIn: "تسجيل الدخول",
      welcome: "مرحباً بك في OpenPay Pro",
    },
    tx: {
      confirm: "تأكيد",
      success: "نجاح",
      pending: "قيد الانتظار",
      failed: "فشل",
    },
  },

  fil: {
    common: {
      appName: "OpenPay Pro",
      loading: "Naglo-load…",
      save: "I-save",
      cancel: "Kanselahin",
      confirm: "Kumpirmahin",
      continue: "Magpatuloy",
      back: "Bumalik",
      close: "Isara",
      done: "Tapos",
      search: "Maghanap",
      copy: "Kopyahin",
      copied: "Nakopya",
      max: "Max",
      next: "Susunod",
      error: "May nangyaring mali",
      retry: "Subukan muli",
      signOut: "Mag-sign out",
      active: "Aktibo",
      amount: "Halaga",
      balance: "Balanse",
      wallet: "Wallet",
      learnMore: "Alamin pa",
      notFound: "Hindi nahanap ang page",
      notFoundDesc: "Walang ganoong route sa OpenPay Pro Wallet.",
      goHome: "Pumunta sa home",
    },
    nav: {
      home: "Home",
      wallet: "Wallet",
      tokens: "Mga token",
      openToken: "OpenToken",
      history: "Kasaysayan",
      settings: "Mga setting",
      liveChat: "Live chat",
      watchlist: "Watchlist",
      ledgerApi: "Ledger API",
      docs: "OpenPay Docs",
      faq: "FAQ",
      nfts: "Mga collectible",
      send: "Magpadala",
      receive: "Tumanggap",
      swap: "Mag-swap",
      buy: "Bumili",
      scan: "I-scan",
    },
    language: {
      title: "Wika ng display",
      subtitle: "Piliin ang wika ng OpenPay Pro",
      searchPlaceholder: "Maghanap ng mga wika",
      updated: "Na-update ang wika",
      current: "Kasalukuyang wika",
    },
    settings: {
      title: "Mga setting",
      account: "Account",
      wallets: "Mga wallet",
      security: "Seguridad",
      preferences: "Mga preference",
      connected: "Nakakonekta",
      legal: "Legal",
      theme: "Tema",
      themeDesc: "Piliin kung paano mukhang ang OpenPay",
      light: "Maliwanag",
      dark: "Madilim",
      currency: "Pera",
      currencyDesc: "Ipakita ang mga fiat value sa",
      language: "Wika",
      languageDesc: "Wika ng interface",
      priceAlerts: "Mga alerto sa presyo",
      priceAlertsDesc: "Abisuhan sa malalaking galaw",
      txAlerts: "Mga alerto sa transaksyon",
      txAlertsDesc: "Abisuhan sa pagpapadala, pagtanggap at top-up",
      lockPush: "Lock-screen push",
      lockPushDesc: "Mga system notification kapag naka-lock ang telepono o sarado ang app",
      emailAlerts: "Mga alerto sa email",
      emailAlertsDesc: "Email kapag tumanggap o nagpadala ka ng pondo",
      terms: "Mga tuntunin ng serbisyo",
      privacy: "Patakaran sa privacy",
      regulatory: "Regulatoryo",
      signOutConfirm: "Mag-sign out sa OpenPay Pro?",
      profile: "Profile",
      editProfile: "I-edit ang profile",
      manageWallets: "Pamahalaan ang mga wallet",
      biometric: "Biometric unlock",
      pin: "PIN",
      recovery: "Recovery phrase",
    },
    dashboard: {
      title: "Home",
      tokens: "Mga token",
      collectibles: "Mga collectible",
      activity: "Kamakailang aktibidad",
      seeAll: "Tingnan lahat",
      send: "Magpadala",
      receive: "Tumanggap",
      swap: "Mag-swap",
      buy: "Bumili",
      emptyTokens: "Wala pang token",
      emptyActivity: "Wala pang aktibidad",
    },
    buy: {
      title: "Bumili",
      addOusd: "Magdagdag ng OUSD sa iyong wallet",
      amount: "Halaga",
      payWith: "Magbayad gamit ang",
      openpayBalance: "OpenPay Balance",
      openpayDesc: "Magbayad mula sa nakakonektang OpenPay account · totoong debit",
      moonpay: "MoonPay",
      moonpayDesc: "Card / Apple Pay / Google Pay · MoonPay → OUSD",
      pi: "Pi Network (π)",
      piDesc: "Magbayad gamit ang Pi · live π price → agad na naikredito ang OUSD ($1)",
      usdc: "USDC Pay",
      usdcDesc: "Magbayad gamit ang USDC · MoonPay Commerce → OUSD",
      crypto: "Crypto Deposit",
      cryptoDesc: "SOL / crypto · MoonPay Commerce → OUSD",
      confirmTitle: "Kumpirmahin ang top-up",
      confirmDesc: "Suriin ang iyong OUSD purchase",
      youPay: "Babayaran mo",
      rateNote: "1 OUSD = $1.00 · naikredito sa iyong aktibong wallet",
      payOpenPay: "Magbayad ng {{amount}} gamit ang OpenPay",
      buyMoonPay: "Bumili gamit ang MoonPay · {{amount}}",
      depositCrypto: "Mag-deposit ng {{amount}} crypto",
      payUsdc: "Magbayad ng {{amount}} gamit ang USDC",
      topUp: "I-top up ang {{amount}}",
      connectOpenPay: "Ikonekta ang OpenPay para magpatuloy",
    },
    wallet: {
      title: "Wallet",
      mainWallet: "Pangunahing wallet",
      myWallet: "Aking wallet",
      switched: "Napalitan ang wallet",
      receive: "Tumanggap",
      send: "Magpadala",
      ousd: "OUSD",
    },
    send: {
      title: "Magpadala",
      to: "Para kay",
      from: "Mula kay",
      review: "Suriin",
      confirm: "Kumpirmahin ang pagpapadala",
    },
    receive: {
      title: "Tumanggap",
      shareAddress: "Ibahagi ang iyong address",
      copyAddress: "Kopyahin ang address",
    },
    swap: {
      title: "Mag-swap",
      youPay: "Babayaran mo",
      youReceive: "Matatanggap mo",
      confirm: "Kumpirmahin ang swap",
    },
    auth: {
      signIn: "Mag-sign in",
      welcome: "Maligayang pagdating sa OpenPay Pro",
    },
    tx: {
      confirm: "Kumpirmahin",
      success: "Tagumpay",
      pending: "Nakabinbin",
      failed: "Nabigo",
    },
  },

  bn: {
    common: {
      appName: "OpenPay Pro",
      loading: "লোড হচ্ছে…",
      save: "সংরক্ষণ",
      cancel: "বাতিল",
      confirm: "নিশ্চিত করুন",
      continue: "চালিয়ে যান",
      back: "পিছনে",
      close: "বন্ধ",
      done: "সম্পন্ন",
      search: "অনুসন্ধান",
      copy: "কপি",
      copied: "কপি হয়েছে",
      max: "সর্বোচ্চ",
      next: "পরবর্তী",
      error: "কিছু ভুল হয়েছে",
      retry: "আবার চেষ্টা করুন",
      signOut: "সাইন আউট",
      active: "সক্রিয়",
      amount: "পরিমাণ",
      balance: "ব্যালেন্স",
      wallet: "ওয়ালেট",
      learnMore: "আরও জানুন",
      notFound: "পৃষ্ঠা পাওয়া যায়নি",
      notFoundDesc: "সেই রুট OpenPay Pro Wallet-এ নেই।",
      goHome: "হোমে যান",
    },
    nav: {
      home: "হোম",
      wallet: "ওয়ালেট",
      tokens: "টোকেন",
      openToken: "OpenToken",
      history: "ইতিহাস",
      settings: "সেটিংস",
      liveChat: "লাইভ চ্যাট",
      watchlist: "ওয়াচলিস্ট",
      ledgerApi: "Ledger API",
      docs: "OpenPay ডকুমেন্টস",
      faq: "FAQ",
      nfts: "সংগ্রহযোগ্য",
      send: "পাঠান",
      receive: "গ্রহণ",
      swap: "সোয়াপ",
      buy: "কিনুন",
      scan: "স্ক্যান",
    },
    language: {
      title: "প্রদর্শনের ভাষা",
      subtitle: "আপনার OpenPay Pro ভাষা বেছে নিন",
      searchPlaceholder: "ভাষা খুঁজুন",
      updated: "ভাষা আপডেট হয়েছে",
      current: "বর্তমান ভাষা",
    },
    settings: {
      title: "সেটিংস",
      account: "অ্যাকাউন্ট",
      wallets: "ওয়ালেট",
      security: "নিরাপত্তা",
      preferences: "পছন্দসমূহ",
      connected: "সংযুক্ত",
      legal: "আইনি",
      theme: "থিম",
      themeDesc: "OpenPay কেমন দেখাবে তা বেছে নিন",
      light: "লাইট",
      dark: "ডার্ক",
      currency: "মুদ্রা",
      currencyDesc: "ফিয়াট মান দেখান",
      language: "ভাষা",
      languageDesc: "ইন্টারফেস ভাষা",
      priceAlerts: "মূল্য সতর্কতা",
      priceAlertsDesc: "বড় পরিবর্তনে জানান",
      txAlerts: "লেনদেন সতর্কতা",
      txAlertsDesc: "পাঠানো, গ্রহণ ও টপ-আপে জানান",
      lockPush: "লক-স্ক্রিন পুশ",
      lockPushDesc: "ফোন লক বা অ্যাপ বন্ধ থাকলে সিস্টেম বিজ্ঞপ্তি",
      emailAlerts: "ইমেইল সতর্কতা",
      emailAlertsDesc: "তহবিল গ্রহণ বা পাঠালে ইমেইল",
      terms: "সেবার শর্তাবলি",
      privacy: "গোপনীয়তা নীতি",
      regulatory: "নিয়ন্ত্রক",
      signOutConfirm: "OpenPay Pro থেকে সাইন আউট করবেন?",
      profile: "প্রোফাইল",
      editProfile: "প্রোফাইল সম্পাদনা",
      manageWallets: "ওয়ালেট পরিচালনা",
      biometric: "বায়োমেট্রিক আনলক",
      pin: "PIN",
      recovery: "রিকভারি ফ্রেজ",
    },
    dashboard: {
      title: "হোম",
      tokens: "টোকেন",
      collectibles: "সংগ্রহযোগ্য",
      activity: "সাম্প্রতিক কার্যক্রম",
      seeAll: "সব দেখুন",
      send: "পাঠান",
      receive: "গ্রহণ",
      swap: "সোয়াপ",
      buy: "কিনুন",
      emptyTokens: "এখনও কোনো টোকেন নেই",
      emptyActivity: "এখনও কোনো কার্যক্রম নেই",
    },
    buy: {
      title: "কিনুন",
      addOusd: "আপনার ওয়ালেটে OUSD যোগ করুন",
      amount: "পরিমাণ",
      payWith: "দিয়ে পরিশোধ করুন",
      openpayBalance: "OpenPay ব্যালেন্স",
      openpayDesc: "আপনার সংযুক্ত OpenPay অ্যাকাউন্ট থেকে পরিশোধ · প্রকৃত ডেবিট",
      moonpay: "MoonPay",
      moonpayDesc: "কার্ড / Apple Pay / Google Pay · MoonPay → OUSD",
      pi: "Pi Network (π)",
      piDesc: "Pi দিয়ে পরিশোধ · লাইভ π মূল্য → OUSD ($1) তাৎক্ষণিক জমা",
      usdc: "USDC পে",
      usdcDesc: "USDC দিয়ে পরিশোধ · MoonPay Commerce → OUSD",
      crypto: "ক্রিপ্টো ডিপোজিট",
      cryptoDesc: "SOL / ক্রিপ্টো · MoonPay Commerce → OUSD",
      confirmTitle: "টপ-আপ নিশ্চিত করুন",
      confirmDesc: "আপনার OUSD ক্রয় পর্যালোচনা করুন",
      youPay: "আপনি পরিশোধ করেন",
      rateNote: "1 OUSD = $1.00 · আপনার সক্রিয় ওয়ালেটে জমা",
      payOpenPay: "OpenPay দিয়ে {{amount}} পরিশোধ করুন",
      buyMoonPay: "MoonPay দিয়ে কিনুন · {{amount}}",
      depositCrypto: "{{amount}} ক্রিপ্টো জমা দিন",
      payUsdc: "USDC দিয়ে {{amount}} পরিশোধ করুন",
      topUp: "{{amount}} টপ আপ করুন",
      connectOpenPay: "চালিয়ে যেতে OpenPay সংযুক্ত করুন",
    },
    wallet: {
      title: "ওয়ালেট",
      mainWallet: "প্রধান ওয়ালেট",
      myWallet: "আমার ওয়ালেট",
      switched: "ওয়ালেট পরিবর্তিত হয়েছে",
      receive: "গ্রহণ",
      send: "পাঠান",
      ousd: "OUSD",
    },
    send: {
      title: "পাঠান",
      to: "প্রাপক",
      from: "প্রেরক",
      review: "পর্যালোচনা",
      confirm: "পাঠানো নিশ্চিত করুন",
    },
    receive: {
      title: "গ্রহণ",
      shareAddress: "আপনার ঠিকানা শেয়ার করুন",
      copyAddress: "ঠিকানা কপি করুন",
    },
    swap: {
      title: "সোয়াপ",
      youPay: "আপনি পরিশোধ করেন",
      youReceive: "আপনি পান",
      confirm: "সোয়াপ নিশ্চিত করুন",
    },
    auth: {
      signIn: "সাইন ইন",
      welcome: "OpenPay Pro-তে স্বাগতম",
    },
    tx: {
      confirm: "নিশ্চিত করুন",
      success: "সফল",
      pending: "মুলতুবি",
      failed: "ব্যর্থ",
    },
  },
};
