/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthpiRouteImport } from './routes/authpi'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TestnetRewardRouteImport } from './routes/testnet-reward'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedKycRouteImport } from './routes/_authenticated/kyc'
import { Route as AuthenticatedLedgerRouteImport } from './routes/_authenticated/ledger'
import { Route as AuthenticatedNftsRouteImport } from './routes/_authenticated/nfts'
import { Route as AuthenticatedOpentokenRouteImport } from './routes/_authenticated/opentoken'
import { Route as AuthenticatedOusdRouteImport } from './routes/_authenticated/ousd'
import { Route as AuthenticatedReceiveRouteImport } from './routes/_authenticated/receive'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedSendRouteImport } from './routes/_authenticated/send'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSwapRouteImport } from './routes/_authenticated/swap'
import { Route as AuthenticatedTokensRouteImport } from './routes/_authenticated/tokens'
import { Route as AuthenticatedTopupRouteImport } from './routes/_authenticated/topup'
import { Route as AuthenticatedWcPayRouteImport } from './routes/_authenticated/wc-pay'
import { Route as AdminTestnetProgressRouteImport } from './routes/admin.testnet-progress'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DocsOpenpayRouteImport } from './routes/docs.openpay'
import { Route as AuthenticatedAdminTopupRouteImport } from './routes/_authenticated/admin.topup'
import { Route as AuthenticatedAssetTokenIdRouteImport } from './routes/_authenticated/asset_.$tokenId'
import { Route as AuthenticatedNftsMintRouteImport } from './routes/_authenticated/nfts.mint'
import { Route as AuthenticatedOpentokenTokenIdRouteImport } from './routes/_authenticated/opentoken_.$tokenId'
import { Route as AuthenticatedOpentokenAdminRouteImport } from './routes/_authenticated/opentoken_.admin'
import { Route as AuthenticatedOpentokenCreateRouteImport } from './routes/_authenticated/opentoken_.create'
import { Route as AuthenticatedOpentokenPortfolioRouteImport } from './routes/_authenticated/opentoken_.portfolio'
import { Route as AuthenticatedTokensCreateRouteImport } from './routes/_authenticated/tokens.create'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicKycWebhookRouteImport } from './routes/api/public/kyc-webhook'
import { Route as ApiPublicMoonpaySignRouteImport } from './routes/api/public/moonpay-sign'
import { Route as ApiPublicMoonpayWebhookRouteImport } from './routes/api/public/moonpay-webhook'
import { Route as ApiPublicOpenpayAuthRouteImport } from './routes/api/public/openpay-auth'
import { Route as ApiPublicPiA2uRouteImport } from './routes/api/public/pi-a2u'
import { Route as ApiPublicPiAuthRouteImport } from './routes/api/public/pi-auth'
import { Route as ApiPublicSolanaAuthRouteImport } from './routes/api/public/solana-auth'
import { Route as ApiPublicSupabaseConfigRouteImport } from './routes/api/public/supabase-config'
import { Route as AuthOpenpayCallbackRouteImport } from './routes/auth.openpay.callback'
import { Route as AuthPiCallbackRouteImport } from './routes/auth.pi.callback'
import { Route as AuthenticatedOpenpayConnectCallbackRouteImport } from './routes/_authenticated/openpay.connect.callback'
import { Route as AuthenticatedOpentokenCreatorUserIdRouteImport } from './routes/_authenticated/opentoken_.creator.$userId'
import { Route as ApiPublicDocsOpenpayRouteImport } from './routes/api/public/docs/openpay'
import { Route as ApiPublicLedgerEntriesRouteImport } from './routes/api/public/ledger/entries'
import { Route as ApiPublicLedgerStatsRouteImport } from './routes/api/public/ledger/stats'
import { Route as ApiPublicOpenpayInboundRouteImport } from './routes/api/public/openpay/inbound'
import { Route as ApiPublicPiPaymentsApproveRouteImport } from './routes/api/public/pi-payments/approve'
import { Route as ApiPublicPiPaymentsCompleteRouteImport } from './routes/api/public/pi-payments/complete'
import { Route as ApiPublicPiPaymentsIncompleteRouteImport } from './routes/api/public/pi-payments/incomplete'
import { Route as ApiPublicLedgerEntriesIdRouteImport } from './routes/api/public/ledger/entries.$id'
import { Route as ApiPublicOpenpayConnectConfirmRouteImport } from './routes/api/public/openpay/connect/confirm'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthpiRoute = AuthpiRouteImport.update({
  id: '/authpi',
  path: '/authpi',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TestnetRewardRoute = TestnetRewardRouteImport.update({
  id: '/testnet-reward',
  path: '/testnet-reward',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKycRoute = AuthenticatedKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLedgerRoute = AuthenticatedLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNftsRoute = AuthenticatedNftsRouteImport.update({
  id: '/nfts',
  path: '/nfts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpentokenRoute = AuthenticatedOpentokenRouteImport.update({
  id: '/opentoken',
  path: '/opentoken',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOusdRoute = AuthenticatedOusdRouteImport.update({
  id: '/ousd',
  path: '/ousd',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceiveRoute = AuthenticatedReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSendRoute = AuthenticatedSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSwapRoute = AuthenticatedSwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTokensRoute = AuthenticatedTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTopupRoute = AuthenticatedTopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWcPayRoute = AuthenticatedWcPayRouteImport.update({
  id: '/wc-pay',
  path: '/wc-pay',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminTestnetProgressRoute = AdminTestnetProgressRouteImport.update({
  id: '/admin/testnet-progress',
  path: '/admin/testnet-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const DocsOpenpayRoute = DocsOpenpayRouteImport.update({
  id: '/docs/openpay',
  path: '/docs/openpay',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminTopupRoute = AuthenticatedAdminTopupRouteImport.update({
  id: '/admin/topup',
  path: '/admin/topup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssetTokenIdRoute =
  AuthenticatedAssetTokenIdRouteImport.update({
    id: '/asset_/$tokenId',
    path: '/asset/$tokenId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNftsMintRoute = AuthenticatedNftsMintRouteImport.update({
  id: '/mint',
  path: '/mint',
  getParentRoute: () => AuthenticatedNftsRoute,
} as any)
const AuthenticatedOpentokenTokenIdRoute =
  AuthenticatedOpentokenTokenIdRouteImport.update({
    id: '/opentoken_/$tokenId',
    path: '/opentoken/$tokenId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpentokenAdminRoute =
  AuthenticatedOpentokenAdminRouteImport.update({
    id: '/opentoken_/admin',
    path: '/opentoken/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpentokenCreateRoute =
  AuthenticatedOpentokenCreateRouteImport.update({
    id: '/opentoken_/create',
    path: '/opentoken/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpentokenPortfolioRoute =
  AuthenticatedOpentokenPortfolioRouteImport.update({
    id: '/opentoken_/portfolio',
    path: '/opentoken/portfolio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTokensCreateRoute =
  AuthenticatedTokensCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedTokensRoute,
  } as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKycWebhookRoute = ApiPublicKycWebhookRouteImport.update({
  id: '/api/public/kyc-webhook',
  path: '/api/public/kyc-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMoonpaySignRoute = ApiPublicMoonpaySignRouteImport.update({
  id: '/api/public/moonpay-sign',
  path: '/api/public/moonpay-sign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMoonpayWebhookRoute = ApiPublicMoonpayWebhookRouteImport.update({
  id: '/api/public/moonpay-webhook',
  path: '/api/public/moonpay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOpenpayAuthRoute = ApiPublicOpenpayAuthRouteImport.update({
  id: '/api/public/openpay-auth',
  path: '/api/public/openpay-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiA2uRoute = ApiPublicPiA2uRouteImport.update({
  id: '/api/public/pi-a2u',
  path: '/api/public/pi-a2u',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiAuthRoute = ApiPublicPiAuthRouteImport.update({
  id: '/api/public/pi-auth',
  path: '/api/public/pi-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSolanaAuthRoute = ApiPublicSolanaAuthRouteImport.update({
  id: '/api/public/solana-auth',
  path: '/api/public/solana-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSupabaseConfigRoute = ApiPublicSupabaseConfigRouteImport.update({
  id: '/api/public/supabase-config',
  path: '/api/public/supabase-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOpenpayCallbackRoute = AuthOpenpayCallbackRouteImport.update({
  id: '/openpay/callback',
  path: '/openpay/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPiCallbackRoute = AuthPiCallbackRouteImport.update({
  id: '/pi/callback',
  path: '/pi/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedOpenpayConnectCallbackRoute =
  AuthenticatedOpenpayConnectCallbackRouteImport.update({
    id: '/openpay/connect/callback',
    path: '/openpay/connect/callback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpentokenCreatorUserIdRoute =
  AuthenticatedOpentokenCreatorUserIdRouteImport.update({
    id: '/opentoken_/creator/$userId',
    path: '/opentoken/creator/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicDocsOpenpayRoute = ApiPublicDocsOpenpayRouteImport.update({
  id: '/api/public/docs/openpay',
  path: '/api/public/docs/openpay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLedgerEntriesRoute = ApiPublicLedgerEntriesRouteImport.update({
  id: '/api/public/ledger/entries',
  path: '/api/public/ledger/entries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLedgerStatsRoute = ApiPublicLedgerStatsRouteImport.update({
  id: '/api/public/ledger/stats',
  path: '/api/public/ledger/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOpenpayInboundRoute = ApiPublicOpenpayInboundRouteImport.update({
  id: '/api/public/openpay/inbound',
  path: '/api/public/openpay/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiPaymentsApproveRoute =
  ApiPublicPiPaymentsApproveRouteImport.update({
    id: '/api/public/pi-payments/approve',
    path: '/api/public/pi-payments/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPiPaymentsCompleteRoute =
  ApiPublicPiPaymentsCompleteRouteImport.update({
    id: '/api/public/pi-payments/complete',
    path: '/api/public/pi-payments/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPiPaymentsIncompleteRoute =
  ApiPublicPiPaymentsIncompleteRouteImport.update({
    id: '/api/public/pi-payments/incomplete',
    path: '/api/public/pi-payments/incomplete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLedgerEntriesIdRoute =
  ApiPublicLedgerEntriesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiPublicLedgerEntriesRoute,
  } as any)
const ApiPublicOpenpayConnectConfirmRoute =
  ApiPublicOpenpayConnectConfirmRouteImport.update({
    id: '/api/public/openpay/connect/confirm',
    path: '/api/public/openpay/connect/confirm',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/authpi': typeof AuthpiRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/testnet-reward': typeof TestnetRewardRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/nfts': typeof AuthenticatedNftsRouteWithChildren
  '/opentoken': typeof AuthenticatedOpentokenRoute
  '/ousd': typeof AuthenticatedOusdRoute
  '/receive': typeof AuthenticatedReceiveRoute
  '/scan': typeof AuthenticatedScanRoute
  '/send': typeof AuthenticatedSendRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/swap': typeof AuthenticatedSwapRoute
  '/tokens': typeof AuthenticatedTokensRouteWithChildren
  '/topup': typeof AuthenticatedTopupRoute
  '/wc-pay': typeof AuthenticatedWcPayRoute
  '/admin/testnet-progress': typeof AdminTestnetProgressRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/docs/openpay': typeof DocsOpenpayRoute
  '/admin/topup': typeof AuthenticatedAdminTopupRoute
  '/asset/$tokenId': typeof AuthenticatedAssetTokenIdRoute
  '/nfts/mint': typeof AuthenticatedNftsMintRoute
  '/opentoken/$tokenId': typeof AuthenticatedOpentokenTokenIdRoute
  '/opentoken/admin': typeof AuthenticatedOpentokenAdminRoute
  '/opentoken/create': typeof AuthenticatedOpentokenCreateRoute
  '/opentoken/portfolio': typeof AuthenticatedOpentokenPortfolioRoute
  '/tokens/create': typeof AuthenticatedTokensCreateRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/kyc-webhook': typeof ApiPublicKycWebhookRoute
  '/api/public/moonpay-sign': typeof ApiPublicMoonpaySignRoute
  '/api/public/moonpay-webhook': typeof ApiPublicMoonpayWebhookRoute
  '/api/public/openpay-auth': typeof ApiPublicOpenpayAuthRoute
  '/api/public/pi-a2u': typeof ApiPublicPiA2uRoute
  '/api/public/pi-auth': typeof ApiPublicPiAuthRoute
  '/api/public/solana-auth': typeof ApiPublicSolanaAuthRoute
  '/api/public/supabase-config': typeof ApiPublicSupabaseConfigRoute
  '/auth/openpay/callback': typeof AuthOpenpayCallbackRoute
  '/auth/pi/callback': typeof AuthPiCallbackRoute
  '/openpay/connect/callback': typeof AuthenticatedOpenpayConnectCallbackRoute
  '/opentoken/creator/$userId': typeof AuthenticatedOpentokenCreatorUserIdRoute
  '/api/public/docs/openpay': typeof ApiPublicDocsOpenpayRoute
  '/api/public/ledger/entries': typeof ApiPublicLedgerEntriesRouteWithChildren
  '/api/public/ledger/stats': typeof ApiPublicLedgerStatsRoute
  '/api/public/openpay/inbound': typeof ApiPublicOpenpayInboundRoute
  '/api/public/pi-payments/approve': typeof ApiPublicPiPaymentsApproveRoute
  '/api/public/pi-payments/complete': typeof ApiPublicPiPaymentsCompleteRoute
  '/api/public/pi-payments/incomplete': typeof ApiPublicPiPaymentsIncompleteRoute
  '/api/public/ledger/entries/$id': typeof ApiPublicLedgerEntriesIdRoute
  '/api/public/openpay/connect/confirm': typeof ApiPublicOpenpayConnectConfirmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/authpi': typeof AuthpiRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/testnet-reward': typeof TestnetRewardRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/nfts': typeof AuthenticatedNftsRouteWithChildren
  '/opentoken': typeof AuthenticatedOpentokenRoute
  '/ousd': typeof AuthenticatedOusdRoute
  '/receive': typeof AuthenticatedReceiveRoute
  '/scan': typeof AuthenticatedScanRoute
  '/send': typeof AuthenticatedSendRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/swap': typeof AuthenticatedSwapRoute
  '/tokens': typeof AuthenticatedTokensRouteWithChildren
  '/topup': typeof AuthenticatedTopupRoute
  '/wc-pay': typeof AuthenticatedWcPayRoute
  '/admin/testnet-progress': typeof AdminTestnetProgressRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/docs/openpay': typeof DocsOpenpayRoute
  '/admin/topup': typeof AuthenticatedAdminTopupRoute
  '/asset/$tokenId': typeof AuthenticatedAssetTokenIdRoute
  '/nfts/mint': typeof AuthenticatedNftsMintRoute
  '/opentoken/$tokenId': typeof AuthenticatedOpentokenTokenIdRoute
  '/opentoken/admin': typeof AuthenticatedOpentokenAdminRoute
  '/opentoken/create': typeof AuthenticatedOpentokenCreateRoute
  '/opentoken/portfolio': typeof AuthenticatedOpentokenPortfolioRoute
  '/tokens/create': typeof AuthenticatedTokensCreateRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/kyc-webhook': typeof ApiPublicKycWebhookRoute
  '/api/public/moonpay-sign': typeof ApiPublicMoonpaySignRoute
  '/api/public/moonpay-webhook': typeof ApiPublicMoonpayWebhookRoute
  '/api/public/openpay-auth': typeof ApiPublicOpenpayAuthRoute
  '/api/public/pi-a2u': typeof ApiPublicPiA2uRoute
  '/api/public/pi-auth': typeof ApiPublicPiAuthRoute
  '/api/public/solana-auth': typeof ApiPublicSolanaAuthRoute
  '/api/public/supabase-config': typeof ApiPublicSupabaseConfigRoute
  '/auth/openpay/callback': typeof AuthOpenpayCallbackRoute
  '/auth/pi/callback': typeof AuthPiCallbackRoute
  '/openpay/connect/callback': typeof AuthenticatedOpenpayConnectCallbackRoute
  '/opentoken/creator/$userId': typeof AuthenticatedOpentokenCreatorUserIdRoute
  '/api/public/docs/openpay': typeof ApiPublicDocsOpenpayRoute
  '/api/public/ledger/entries': typeof ApiPublicLedgerEntriesRouteWithChildren
  '/api/public/ledger/stats': typeof ApiPublicLedgerStatsRoute
  '/api/public/openpay/inbound': typeof ApiPublicOpenpayInboundRoute
  '/api/public/pi-payments/approve': typeof ApiPublicPiPaymentsApproveRoute
  '/api/public/pi-payments/complete': typeof ApiPublicPiPaymentsCompleteRoute
  '/api/public/pi-payments/incomplete': typeof ApiPublicPiPaymentsIncompleteRoute
  '/api/public/ledger/entries/$id': typeof ApiPublicLedgerEntriesIdRoute
  '/api/public/openpay/connect/confirm': typeof ApiPublicOpenpayConnectConfirmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/authpi': typeof AuthpiRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/testnet-reward': typeof TestnetRewardRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kyc': typeof AuthenticatedKycRoute
  '/_authenticated/ledger': typeof AuthenticatedLedgerRoute
  '/_authenticated/nfts': typeof AuthenticatedNftsRouteWithChildren
  '/_authenticated/opentoken': typeof AuthenticatedOpentokenRoute
  '/_authenticated/ousd': typeof AuthenticatedOusdRoute
  '/_authenticated/receive': typeof AuthenticatedReceiveRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/_authenticated/send': typeof AuthenticatedSendRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/swap': typeof AuthenticatedSwapRoute
  '/_authenticated/tokens': typeof AuthenticatedTokensRouteWithChildren
  '/_authenticated/topup': typeof AuthenticatedTopupRoute
  '/_authenticated/wc-pay': typeof AuthenticatedWcPayRoute
  '/admin/testnet-progress': typeof AdminTestnetProgressRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/docs/openpay': typeof DocsOpenpayRoute
  '/_authenticated/admin/topup': typeof AuthenticatedAdminTopupRoute
  '/_authenticated/asset_/$tokenId': typeof AuthenticatedAssetTokenIdRoute
  '/_authenticated/nfts/mint': typeof AuthenticatedNftsMintRoute
  '/_authenticated/opentoken_/$tokenId': typeof AuthenticatedOpentokenTokenIdRoute
  '/_authenticated/opentoken_/admin': typeof AuthenticatedOpentokenAdminRoute
  '/_authenticated/opentoken_/create': typeof AuthenticatedOpentokenCreateRoute
  '/_authenticated/opentoken_/portfolio': typeof AuthenticatedOpentokenPortfolioRoute
  '/_authenticated/tokens/create': typeof AuthenticatedTokensCreateRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/kyc-webhook': typeof ApiPublicKycWebhookRoute
  '/api/public/moonpay-sign': typeof ApiPublicMoonpaySignRoute
  '/api/public/moonpay-webhook': typeof ApiPublicMoonpayWebhookRoute
  '/api/public/openpay-auth': typeof ApiPublicOpenpayAuthRoute
  '/api/public/pi-a2u': typeof ApiPublicPiA2uRoute
  '/api/public/pi-auth': typeof ApiPublicPiAuthRoute
  '/api/public/solana-auth': typeof ApiPublicSolanaAuthRoute
  '/api/public/supabase-config': typeof ApiPublicSupabaseConfigRoute
  '/auth/openpay/callback': typeof AuthOpenpayCallbackRoute
  '/auth/pi/callback': typeof AuthPiCallbackRoute
  '/_authenticated/openpay/connect/callback': typeof AuthenticatedOpenpayConnectCallbackRoute
  '/_authenticated/opentoken_/creator/$userId': typeof AuthenticatedOpentokenCreatorUserIdRoute
  '/api/public/docs/openpay': typeof ApiPublicDocsOpenpayRoute
  '/api/public/ledger/entries': typeof ApiPublicLedgerEntriesRouteWithChildren
  '/api/public/ledger/stats': typeof ApiPublicLedgerStatsRoute
  '/api/public/openpay/inbound': typeof ApiPublicOpenpayInboundRoute
  '/api/public/pi-payments/approve': typeof ApiPublicPiPaymentsApproveRoute
  '/api/public/pi-payments/complete': typeof ApiPublicPiPaymentsCompleteRoute
  '/api/public/pi-payments/incomplete': typeof ApiPublicPiPaymentsIncompleteRoute
  '/api/public/ledger/entries/$id': typeof ApiPublicLedgerEntriesIdRoute
  '/api/public/openpay/connect/confirm': typeof ApiPublicOpenpayConnectConfirmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/authpi'
    | '/privacy'
    | '/terms'
    | '/testnet-reward'
    | '/activity'
    | '/dashboard'
    | '/kyc'
    | '/ledger'
    | '/nfts'
    | '/opentoken'
    | '/ousd'
    | '/receive'
    | '/scan'
    | '/send'
    | '/settings'
    | '/swap'
    | '/tokens'
    | '/topup'
    | '/wc-pay'
    | '/admin/testnet-progress'
    | '/auth/callback'
    | '/docs/openpay'
    | '/admin/topup'
    | '/asset/$tokenId'
    | '/nfts/mint'
    | '/opentoken/$tokenId'
    | '/opentoken/admin'
    | '/opentoken/create'
    | '/opentoken/portfolio'
    | '/tokens/create'
    | '/api/public/health'
    | '/api/public/kyc-webhook'
    | '/api/public/moonpay-sign'
    | '/api/public/moonpay-webhook'
    | '/api/public/openpay-auth'
    | '/api/public/pi-a2u'
    | '/api/public/pi-auth'
    | '/api/public/solana-auth'
    | '/api/public/supabase-config'
    | '/auth/openpay/callback'
    | '/auth/pi/callback'
    | '/openpay/connect/callback'
    | '/opentoken/creator/$userId'
    | '/api/public/docs/openpay'
    | '/api/public/ledger/entries'
    | '/api/public/ledger/stats'
    | '/api/public/openpay/inbound'
    | '/api/public/pi-payments/approve'
    | '/api/public/pi-payments/complete'
    | '/api/public/pi-payments/incomplete'
    | '/api/public/ledger/entries/$id'
    | '/api/public/openpay/connect/confirm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/authpi'
    | '/privacy'
    | '/terms'
    | '/testnet-reward'
    | '/activity'
    | '/dashboard'
    | '/kyc'
    | '/ledger'
    | '/nfts'
    | '/opentoken'
    | '/ousd'
    | '/receive'
    | '/scan'
    | '/send'
    | '/settings'
    | '/swap'
    | '/tokens'
    | '/topup'
    | '/wc-pay'
    | '/admin/testnet-progress'
    | '/auth/callback'
    | '/docs/openpay'
    | '/admin/topup'
    | '/asset/$tokenId'
    | '/nfts/mint'
    | '/opentoken/$tokenId'
    | '/opentoken/admin'
    | '/opentoken/create'
    | '/opentoken/portfolio'
    | '/tokens/create'
    | '/api/public/health'
    | '/api/public/kyc-webhook'
    | '/api/public/moonpay-sign'
    | '/api/public/moonpay-webhook'
    | '/api/public/openpay-auth'
    | '/api/public/pi-a2u'
    | '/api/public/pi-auth'
    | '/api/public/solana-auth'
    | '/api/public/supabase-config'
    | '/auth/openpay/callback'
    | '/auth/pi/callback'
    | '/openpay/connect/callback'
    | '/opentoken/creator/$userId'
    | '/api/public/docs/openpay'
    | '/api/public/ledger/entries'
    | '/api/public/ledger/stats'
    | '/api/public/openpay/inbound'
    | '/api/public/pi-payments/approve'
    | '/api/public/pi-payments/complete'
    | '/api/public/pi-payments/incomplete'
    | '/api/public/ledger/entries/$id'
    | '/api/public/openpay/connect/confirm'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/authpi'
    | '/privacy'
    | '/terms'
    | '/testnet-reward'
    | '/_authenticated/activity'
    | '/_authenticated/dashboard'
    | '/_authenticated/kyc'
    | '/_authenticated/ledger'
    | '/_authenticated/nfts'
    | '/_authenticated/opentoken'
    | '/_authenticated/ousd'
    | '/_authenticated/receive'
    | '/_authenticated/scan'
    | '/_authenticated/send'
    | '/_authenticated/settings'
    | '/_authenticated/swap'
    | '/_authenticated/tokens'
    | '/_authenticated/topup'
    | '/_authenticated/wc-pay'
    | '/admin/testnet-progress'
    | '/auth/callback'
    | '/docs/openpay'
    | '/_authenticated/admin/topup'
    | '/_authenticated/asset_/$tokenId'
    | '/_authenticated/nfts/mint'
    | '/_authenticated/opentoken_/$tokenId'
    | '/_authenticated/opentoken_/admin'
    | '/_authenticated/opentoken_/create'
    | '/_authenticated/opentoken_/portfolio'
    | '/_authenticated/tokens/create'
    | '/api/public/health'
    | '/api/public/kyc-webhook'
    | '/api/public/moonpay-sign'
    | '/api/public/moonpay-webhook'
    | '/api/public/openpay-auth'
    | '/api/public/pi-a2u'
    | '/api/public/pi-auth'
    | '/api/public/solana-auth'
    | '/api/public/supabase-config'
    | '/auth/openpay/callback'
    | '/auth/pi/callback'
    | '/_authenticated/openpay/connect/callback'
    | '/_authenticated/opentoken_/creator/$userId'
    | '/api/public/docs/openpay'
    | '/api/public/ledger/entries'
    | '/api/public/ledger/stats'
    | '/api/public/openpay/inbound'
    | '/api/public/pi-payments/approve'
    | '/api/public/pi-payments/complete'
    | '/api/public/pi-payments/incomplete'
    | '/api/public/ledger/entries/$id'
    | '/api/public/openpay/connect/confirm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AuthpiRoute: typeof AuthpiRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TestnetRewardRoute: typeof TestnetRewardRoute
  AdminTestnetProgressRoute: typeof AdminTestnetProgressRoute
  DocsOpenpayRoute: typeof DocsOpenpayRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicKycWebhookRoute: typeof ApiPublicKycWebhookRoute
  ApiPublicMoonpaySignRoute: typeof ApiPublicMoonpaySignRoute
  ApiPublicMoonpayWebhookRoute: typeof ApiPublicMoonpayWebhookRoute
  ApiPublicOpenpayAuthRoute: typeof ApiPublicOpenpayAuthRoute
  ApiPublicPiA2uRoute: typeof ApiPublicPiA2uRoute
  ApiPublicPiAuthRoute: typeof ApiPublicPiAuthRoute
  ApiPublicSolanaAuthRoute: typeof ApiPublicSolanaAuthRoute
  ApiPublicSupabaseConfigRoute: typeof ApiPublicSupabaseConfigRoute
  ApiPublicDocsOpenpayRoute: typeof ApiPublicDocsOpenpayRoute
  ApiPublicLedgerEntriesRoute: typeof ApiPublicLedgerEntriesRouteWithChildren
  ApiPublicLedgerStatsRoute: typeof ApiPublicLedgerStatsRoute
  ApiPublicOpenpayInboundRoute: typeof ApiPublicOpenpayInboundRoute
  ApiPublicPiPaymentsApproveRoute: typeof ApiPublicPiPaymentsApproveRoute
  ApiPublicPiPaymentsCompleteRoute: typeof ApiPublicPiPaymentsCompleteRoute
  ApiPublicPiPaymentsIncompleteRoute: typeof ApiPublicPiPaymentsIncompleteRoute
  ApiPublicOpenpayConnectConfirmRoute: typeof ApiPublicOpenpayConnectConfirmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authpi': {
      id: '/authpi'
      path: '/authpi'
      fullPath: '/authpi'
      preLoaderRoute: typeof AuthpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testnet-reward': {
      id: '/testnet-reward'
      path: '/testnet-reward'
      fullPath: '/testnet-reward'
      preLoaderRoute: typeof TestnetRewardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kyc': {
      id: '/_authenticated/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AuthenticatedKycRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ledger': {
      id: '/_authenticated/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AuthenticatedLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nfts': {
      id: '/_authenticated/nfts'
      path: '/nfts'
      fullPath: '/nfts'
      preLoaderRoute: typeof AuthenticatedNftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opentoken': {
      id: '/_authenticated/opentoken'
      path: '/opentoken'
      fullPath: '/opentoken'
      preLoaderRoute: typeof AuthenticatedOpentokenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ousd': {
      id: '/_authenticated/ousd'
      path: '/ousd'
      fullPath: '/ousd'
      preLoaderRoute: typeof AuthenticatedOusdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receive': {
      id: '/_authenticated/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof AuthenticatedReceiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/send': {
      id: '/_authenticated/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AuthenticatedSendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/swap': {
      id: '/_authenticated/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof AuthenticatedSwapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tokens': {
      id: '/_authenticated/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof AuthenticatedTokensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/topup': {
      id: '/_authenticated/topup'
      path: '/topup'
      fullPath: '/topup'
      preLoaderRoute: typeof AuthenticatedTopupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wc-pay': {
      id: '/_authenticated/wc-pay'
      path: '/wc-pay'
      fullPath: '/wc-pay'
      preLoaderRoute: typeof AuthenticatedWcPayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/testnet-progress': {
      id: '/admin/testnet-progress'
      path: '/admin/testnet-progress'
      fullPath: '/admin/testnet-progress'
      preLoaderRoute: typeof AdminTestnetProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/docs/openpay': {
      id: '/docs/openpay'
      path: '/docs/openpay'
      fullPath: '/docs/openpay'
      preLoaderRoute: typeof DocsOpenpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/topup': {
      id: '/_authenticated/admin/topup'
      path: '/admin/topup'
      fullPath: '/admin/topup'
      preLoaderRoute: typeof AuthenticatedAdminTopupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/asset_/$tokenId': {
      id: '/_authenticated/asset_/$tokenId'
      path: '/asset/$tokenId'
      fullPath: '/asset/$tokenId'
      preLoaderRoute: typeof AuthenticatedAssetTokenIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nfts/mint': {
      id: '/_authenticated/nfts/mint'
      path: '/mint'
      fullPath: '/nfts/mint'
      preLoaderRoute: typeof AuthenticatedNftsMintRouteImport
      parentRoute: typeof AuthenticatedNftsRoute
    }
    '/_authenticated/opentoken_/$tokenId': {
      id: '/_authenticated/opentoken_/$tokenId'
      path: '/opentoken/$tokenId'
      fullPath: '/opentoken/$tokenId'
      preLoaderRoute: typeof AuthenticatedOpentokenTokenIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opentoken_/admin': {
      id: '/_authenticated/opentoken_/admin'
      path: '/opentoken/admin'
      fullPath: '/opentoken/admin'
      preLoaderRoute: typeof AuthenticatedOpentokenAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opentoken_/create': {
      id: '/_authenticated/opentoken_/create'
      path: '/opentoken/create'
      fullPath: '/opentoken/create'
      preLoaderRoute: typeof AuthenticatedOpentokenCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opentoken_/portfolio': {
      id: '/_authenticated/opentoken_/portfolio'
      path: '/opentoken/portfolio'
      fullPath: '/opentoken/portfolio'
      preLoaderRoute: typeof AuthenticatedOpentokenPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tokens/create': {
      id: '/_authenticated/tokens/create'
      path: '/create'
      fullPath: '/tokens/create'
      preLoaderRoute: typeof AuthenticatedTokensCreateRouteImport
      parentRoute: typeof AuthenticatedTokensRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kyc-webhook': {
      id: '/api/public/kyc-webhook'
      path: '/api/public/kyc-webhook'
      fullPath: '/api/public/kyc-webhook'
      preLoaderRoute: typeof ApiPublicKycWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/moonpay-sign': {
      id: '/api/public/moonpay-sign'
      path: '/api/public/moonpay-sign'
      fullPath: '/api/public/moonpay-sign'
      preLoaderRoute: typeof ApiPublicMoonpaySignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/moonpay-webhook': {
      id: '/api/public/moonpay-webhook'
      path: '/api/public/moonpay-webhook'
      fullPath: '/api/public/moonpay-webhook'
      preLoaderRoute: typeof ApiPublicMoonpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/openpay-auth': {
      id: '/api/public/openpay-auth'
      path: '/api/public/openpay-auth'
      fullPath: '/api/public/openpay-auth'
      preLoaderRoute: typeof ApiPublicOpenpayAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-a2u': {
      id: '/api/public/pi-a2u'
      path: '/api/public/pi-a2u'
      fullPath: '/api/public/pi-a2u'
      preLoaderRoute: typeof ApiPublicPiA2uRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-auth': {
      id: '/api/public/pi-auth'
      path: '/api/public/pi-auth'
      fullPath: '/api/public/pi-auth'
      preLoaderRoute: typeof ApiPublicPiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/solana-auth': {
      id: '/api/public/solana-auth'
      path: '/api/public/solana-auth'
      fullPath: '/api/public/solana-auth'
      preLoaderRoute: typeof ApiPublicSolanaAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/supabase-config': {
      id: '/api/public/supabase-config'
      path: '/api/public/supabase-config'
      fullPath: '/api/public/supabase-config'
      preLoaderRoute: typeof ApiPublicSupabaseConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/openpay/callback': {
      id: '/auth/openpay/callback'
      path: '/openpay/callback'
      fullPath: '/auth/openpay/callback'
      preLoaderRoute: typeof AuthOpenpayCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/pi/callback': {
      id: '/auth/pi/callback'
      path: '/pi/callback'
      fullPath: '/auth/pi/callback'
      preLoaderRoute: typeof AuthPiCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/openpay/connect/callback': {
      id: '/_authenticated/openpay/connect/callback'
      path: '/openpay/connect/callback'
      fullPath: '/openpay/connect/callback'
      preLoaderRoute: typeof AuthenticatedOpenpayConnectCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opentoken_/creator/$userId': {
      id: '/_authenticated/opentoken_/creator/$userId'
      path: '/opentoken/creator/$userId'
      fullPath: '/opentoken/creator/$userId'
      preLoaderRoute: typeof AuthenticatedOpentokenCreatorUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/docs/openpay': {
      id: '/api/public/docs/openpay'
      path: '/api/public/docs/openpay'
      fullPath: '/api/public/docs/openpay'
      preLoaderRoute: typeof ApiPublicDocsOpenpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ledger/entries': {
      id: '/api/public/ledger/entries'
      path: '/api/public/ledger/entries'
      fullPath: '/api/public/ledger/entries'
      preLoaderRoute: typeof ApiPublicLedgerEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ledger/stats': {
      id: '/api/public/ledger/stats'
      path: '/api/public/ledger/stats'
      fullPath: '/api/public/ledger/stats'
      preLoaderRoute: typeof ApiPublicLedgerStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/openpay/inbound': {
      id: '/api/public/openpay/inbound'
      path: '/api/public/openpay/inbound'
      fullPath: '/api/public/openpay/inbound'
      preLoaderRoute: typeof ApiPublicOpenpayInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-payments/approve': {
      id: '/api/public/pi-payments/approve'
      path: '/api/public/pi-payments/approve'
      fullPath: '/api/public/pi-payments/approve'
      preLoaderRoute: typeof ApiPublicPiPaymentsApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-payments/complete': {
      id: '/api/public/pi-payments/complete'
      path: '/api/public/pi-payments/complete'
      fullPath: '/api/public/pi-payments/complete'
      preLoaderRoute: typeof ApiPublicPiPaymentsCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-payments/incomplete': {
      id: '/api/public/pi-payments/incomplete'
      path: '/api/public/pi-payments/incomplete'
      fullPath: '/api/public/pi-payments/incomplete'
      preLoaderRoute: typeof ApiPublicPiPaymentsIncompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ledger/entries/$id': {
      id: '/api/public/ledger/entries/$id'
      path: '/$id'
      fullPath: '/api/public/ledger/entries/$id'
      preLoaderRoute: typeof ApiPublicLedgerEntriesIdRouteImport
      parentRoute: typeof ApiPublicLedgerEntriesRoute
    }
    '/api/public/openpay/connect/confirm': {
      id: '/api/public/openpay/connect/confirm'
      path: '/api/public/openpay/connect/confirm'
      fullPath: '/api/public/openpay/connect/confirm'
      preLoaderRoute: typeof ApiPublicOpenpayConnectConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedNftsRouteChildren {
  AuthenticatedNftsMintRoute: typeof AuthenticatedNftsMintRoute
}

const AuthenticatedNftsRouteChildren: AuthenticatedNftsRouteChildren = {
  AuthenticatedNftsMintRoute: AuthenticatedNftsMintRoute,
}

const AuthenticatedNftsRouteWithChildren =
  AuthenticatedNftsRoute._addFileChildren(AuthenticatedNftsRouteChildren)

interface AuthenticatedTokensRouteChildren {
  AuthenticatedTokensCreateRoute: typeof AuthenticatedTokensCreateRoute
}

const AuthenticatedTokensRouteChildren: AuthenticatedTokensRouteChildren = {
  AuthenticatedTokensCreateRoute: AuthenticatedTokensCreateRoute,
}

const AuthenticatedTokensRouteWithChildren =
  AuthenticatedTokensRoute._addFileChildren(AuthenticatedTokensRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKycRoute: typeof AuthenticatedKycRoute
  AuthenticatedLedgerRoute: typeof AuthenticatedLedgerRoute
  AuthenticatedNftsRoute: typeof AuthenticatedNftsRouteWithChildren
  AuthenticatedOpentokenRoute: typeof AuthenticatedOpentokenRoute
  AuthenticatedOusdRoute: typeof AuthenticatedOusdRoute
  AuthenticatedReceiveRoute: typeof AuthenticatedReceiveRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedSendRoute: typeof AuthenticatedSendRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSwapRoute: typeof AuthenticatedSwapRoute
  AuthenticatedTokensRoute: typeof AuthenticatedTokensRouteWithChildren
  AuthenticatedTopupRoute: typeof AuthenticatedTopupRoute
  AuthenticatedWcPayRoute: typeof AuthenticatedWcPayRoute
  AuthenticatedAdminTopupRoute: typeof AuthenticatedAdminTopupRoute
  AuthenticatedAssetTokenIdRoute: typeof AuthenticatedAssetTokenIdRoute
  AuthenticatedOpentokenTokenIdRoute: typeof AuthenticatedOpentokenTokenIdRoute
  AuthenticatedOpentokenAdminRoute: typeof AuthenticatedOpentokenAdminRoute
  AuthenticatedOpentokenCreateRoute: typeof AuthenticatedOpentokenCreateRoute
  AuthenticatedOpentokenPortfolioRoute: typeof AuthenticatedOpentokenPortfolioRoute
  AuthenticatedOpenpayConnectCallbackRoute: typeof AuthenticatedOpenpayConnectCallbackRoute
  AuthenticatedOpentokenCreatorUserIdRoute: typeof AuthenticatedOpentokenCreatorUserIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKycRoute: AuthenticatedKycRoute,
  AuthenticatedLedgerRoute: AuthenticatedLedgerRoute,
  AuthenticatedNftsRoute: AuthenticatedNftsRouteWithChildren,
  AuthenticatedOpentokenRoute: AuthenticatedOpentokenRoute,
  AuthenticatedOusdRoute: AuthenticatedOusdRoute,
  AuthenticatedReceiveRoute: AuthenticatedReceiveRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedSendRoute: AuthenticatedSendRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSwapRoute: AuthenticatedSwapRoute,
  AuthenticatedTokensRoute: AuthenticatedTokensRouteWithChildren,
  AuthenticatedTopupRoute: AuthenticatedTopupRoute,
  AuthenticatedWcPayRoute: AuthenticatedWcPayRoute,
  AuthenticatedAdminTopupRoute: AuthenticatedAdminTopupRoute,
  AuthenticatedAssetTokenIdRoute: AuthenticatedAssetTokenIdRoute,
  AuthenticatedOpentokenTokenIdRoute: AuthenticatedOpentokenTokenIdRoute,
  AuthenticatedOpentokenAdminRoute: AuthenticatedOpentokenAdminRoute,
  AuthenticatedOpentokenCreateRoute: AuthenticatedOpentokenCreateRoute,
  AuthenticatedOpentokenPortfolioRoute: AuthenticatedOpentokenPortfolioRoute,
  AuthenticatedOpenpayConnectCallbackRoute:
    AuthenticatedOpenpayConnectCallbackRoute,
  AuthenticatedOpentokenCreatorUserIdRoute:
    AuthenticatedOpentokenCreatorUserIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthOpenpayCallbackRoute: typeof AuthOpenpayCallbackRoute
  AuthPiCallbackRoute: typeof AuthPiCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthOpenpayCallbackRoute: AuthOpenpayCallbackRoute,
  AuthPiCallbackRoute: AuthPiCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ApiPublicLedgerEntriesRouteChildren {
  ApiPublicLedgerEntriesIdRoute: typeof ApiPublicLedgerEntriesIdRoute
}

const ApiPublicLedgerEntriesRouteChildren: ApiPublicLedgerEntriesRouteChildren =
  {
    ApiPublicLedgerEntriesIdRoute: ApiPublicLedgerEntriesIdRoute,
  }

const ApiPublicLedgerEntriesRouteWithChildren =
  ApiPublicLedgerEntriesRoute._addFileChildren(
    ApiPublicLedgerEntriesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AuthpiRoute: AuthpiRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TestnetRewardRoute: TestnetRewardRoute,
  AdminTestnetProgressRoute: AdminTestnetProgressRoute,
  DocsOpenpayRoute: DocsOpenpayRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicKycWebhookRoute: ApiPublicKycWebhookRoute,
  ApiPublicMoonpaySignRoute: ApiPublicMoonpaySignRoute,
  ApiPublicMoonpayWebhookRoute: ApiPublicMoonpayWebhookRoute,
  ApiPublicOpenpayAuthRoute: ApiPublicOpenpayAuthRoute,
  ApiPublicPiA2uRoute: ApiPublicPiA2uRoute,
  ApiPublicPiAuthRoute: ApiPublicPiAuthRoute,
  ApiPublicSolanaAuthRoute: ApiPublicSolanaAuthRoute,
  ApiPublicSupabaseConfigRoute: ApiPublicSupabaseConfigRoute,
  ApiPublicDocsOpenpayRoute: ApiPublicDocsOpenpayRoute,
  ApiPublicLedgerEntriesRoute: ApiPublicLedgerEntriesRouteWithChildren,
  ApiPublicLedgerStatsRoute: ApiPublicLedgerStatsRoute,
  ApiPublicOpenpayInboundRoute: ApiPublicOpenpayInboundRoute,
  ApiPublicPiPaymentsApproveRoute: ApiPublicPiPaymentsApproveRoute,
  ApiPublicPiPaymentsCompleteRoute: ApiPublicPiPaymentsCompleteRoute,
  ApiPublicPiPaymentsIncompleteRoute: ApiPublicPiPaymentsIncompleteRoute,
  ApiPublicOpenpayConnectConfirmRoute: ApiPublicOpenpayConnectConfirmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
