/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthpiRouteImport } from './routes/authpi'
import { Route as TestnetRewardRouteImport } from './routes/testnet-reward'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedKycRouteImport } from './routes/_authenticated/kyc'
import { Route as AuthenticatedLedgerRouteImport } from './routes/_authenticated/ledger'
import { Route as AuthenticatedNftsRouteImport } from './routes/_authenticated/nfts'
import { Route as AuthenticatedOusdRouteImport } from './routes/_authenticated/ousd'
import { Route as AuthenticatedReceiveRouteImport } from './routes/_authenticated/receive'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedSendRouteImport } from './routes/_authenticated/send'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSwapRouteImport } from './routes/_authenticated/swap'
import { Route as AuthenticatedTokensRouteImport } from './routes/_authenticated/tokens'
import { Route as AuthenticatedTopupRouteImport } from './routes/_authenticated/topup'
import { Route as AdminTestnetProgressRouteImport } from './routes/admin.testnet-progress'
import { Route as AuthenticatedAdminTopupRouteImport } from './routes/_authenticated/admin.topup'
import { Route as AuthenticatedNftsMintRouteImport } from './routes/_authenticated/nfts.mint'
import { Route as AuthenticatedTokensCreateRouteImport } from './routes/_authenticated/tokens.create'
import { Route as ApiPublicKycWebhookRouteImport } from './routes/api/public/kyc-webhook'
import { Route as ApiPublicPiA2uRouteImport } from './routes/api/public/pi-a2u'
import { Route as ApiPublicPiAuthRouteImport } from './routes/api/public/pi-auth'
import { Route as AuthPiCallbackRouteImport } from './routes/auth.pi.callback'
import { Route as ApiPublicLedgerEntriesRouteImport } from './routes/api/public/ledger/entries'
import { Route as ApiPublicLedgerStatsRouteImport } from './routes/api/public/ledger/stats'
import { Route as ApiPublicPiPaymentsApproveRouteImport } from './routes/api/public/pi-payments/approve'
import { Route as ApiPublicPiPaymentsCompleteRouteImport } from './routes/api/public/pi-payments/complete'
import { Route as ApiPublicPiPaymentsIncompleteRouteImport } from './routes/api/public/pi-payments/incomplete'
import { Route as ApiPublicLedgerEntriesIdRouteImport } from './routes/api/public/ledger/entries.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthpiRoute = AuthpiRouteImport.update({
  id: '/authpi',
  path: '/authpi',
  getParentRoute: () => rootRouteImport,
} as any)
const TestnetRewardRoute = TestnetRewardRouteImport.update({
  id: '/testnet-reward',
  path: '/testnet-reward',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKycRoute = AuthenticatedKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLedgerRoute = AuthenticatedLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNftsRoute = AuthenticatedNftsRouteImport.update({
  id: '/nfts',
  path: '/nfts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOusdRoute = AuthenticatedOusdRouteImport.update({
  id: '/ousd',
  path: '/ousd',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceiveRoute = AuthenticatedReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSendRoute = AuthenticatedSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSwapRoute = AuthenticatedSwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTokensRoute = AuthenticatedTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTopupRoute = AuthenticatedTopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminTestnetProgressRoute = AdminTestnetProgressRouteImport.update({
  id: '/admin/testnet-progress',
  path: '/admin/testnet-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminTopupRoute = AuthenticatedAdminTopupRouteImport.update({
  id: '/admin/topup',
  path: '/admin/topup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNftsMintRoute = AuthenticatedNftsMintRouteImport.update({
  id: '/mint',
  path: '/mint',
  getParentRoute: () => AuthenticatedNftsRoute,
} as any)
const AuthenticatedTokensCreateRoute =
  AuthenticatedTokensCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedTokensRoute,
  } as any)
const ApiPublicKycWebhookRoute = ApiPublicKycWebhookRouteImport.update({
  id: '/api/public/kyc-webhook',
  path: '/api/public/kyc-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiA2uRoute = ApiPublicPiA2uRouteImport.update({
  id: '/api/public/pi-a2u',
  path: '/api/public/pi-a2u',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiAuthRoute = ApiPublicPiAuthRouteImport.update({
  id: '/api/public/pi-auth',
  path: '/api/public/pi-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPiCallbackRoute = AuthPiCallbackRouteImport.update({
  id: '/pi/callback',
  path: '/pi/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiPublicLedgerEntriesRoute = ApiPublicLedgerEntriesRouteImport.update({
  id: '/api/public/ledger/entries',
  path: '/api/public/ledger/entries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLedgerStatsRoute = ApiPublicLedgerStatsRouteImport.update({
  id: '/api/public/ledger/stats',
  path: '/api/public/ledger/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiPaymentsApproveRoute =
  ApiPublicPiPaymentsApproveRouteImport.update({
    id: '/api/public/pi-payments/approve',
    path: '/api/public/pi-payments/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPiPaymentsCompleteRoute =
  ApiPublicPiPaymentsCompleteRouteImport.update({
    id: '/api/public/pi-payments/complete',
    path: '/api/public/pi-payments/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPiPaymentsIncompleteRoute =
  ApiPublicPiPaymentsIncompleteRouteImport.update({
    id: '/api/public/pi-payments/incomplete',
    path: '/api/public/pi-payments/incomplete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLedgerEntriesIdRoute =
  ApiPublicLedgerEntriesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiPublicLedgerEntriesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/authpi': typeof AuthpiRoute
  '/testnet-reward': typeof TestnetRewardRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/nfts': typeof AuthenticatedNftsRouteWithChildren
  '/ousd': typeof AuthenticatedOusdRoute
  '/receive': typeof AuthenticatedReceiveRoute
  '/scan': typeof AuthenticatedScanRoute
  '/send': typeof AuthenticatedSendRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/swap': typeof AuthenticatedSwapRoute
  '/tokens': typeof AuthenticatedTokensRouteWithChildren
  '/topup': typeof AuthenticatedTopupRoute
  '/admin/testnet-progress': typeof AdminTestnetProgressRoute
  '/admin/topup': typeof AuthenticatedAdminTopupRoute
  '/nfts/mint': typeof AuthenticatedNftsMintRoute
  '/tokens/create': typeof AuthenticatedTokensCreateRoute
  '/api/public/kyc-webhook': typeof ApiPublicKycWebhookRoute
  '/api/public/pi-a2u': typeof ApiPublicPiA2uRoute
  '/api/public/pi-auth': typeof ApiPublicPiAuthRoute
  '/auth/pi/callback': typeof AuthPiCallbackRoute
  '/api/public/ledger/entries': typeof ApiPublicLedgerEntriesRouteWithChildren
  '/api/public/ledger/stats': typeof ApiPublicLedgerStatsRoute
  '/api/public/pi-payments/approve': typeof ApiPublicPiPaymentsApproveRoute
  '/api/public/pi-payments/complete': typeof ApiPublicPiPaymentsCompleteRoute
  '/api/public/pi-payments/incomplete': typeof ApiPublicPiPaymentsIncompleteRoute
  '/api/public/ledger/entries/$id': typeof ApiPublicLedgerEntriesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/authpi': typeof AuthpiRoute
  '/testnet-reward': typeof TestnetRewardRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/nfts': typeof AuthenticatedNftsRouteWithChildren
  '/ousd': typeof AuthenticatedOusdRoute
  '/receive': typeof AuthenticatedReceiveRoute
  '/scan': typeof AuthenticatedScanRoute
  '/send': typeof AuthenticatedSendRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/swap': typeof AuthenticatedSwapRoute
  '/tokens': typeof AuthenticatedTokensRouteWithChildren
  '/topup': typeof AuthenticatedTopupRoute
  '/admin/testnet-progress': typeof AdminTestnetProgressRoute
  '/admin/topup': typeof AuthenticatedAdminTopupRoute
  '/nfts/mint': typeof AuthenticatedNftsMintRoute
  '/tokens/create': typeof AuthenticatedTokensCreateRoute
  '/api/public/kyc-webhook': typeof ApiPublicKycWebhookRoute
  '/api/public/pi-a2u': typeof ApiPublicPiA2uRoute
  '/api/public/pi-auth': typeof ApiPublicPiAuthRoute
  '/auth/pi/callback': typeof AuthPiCallbackRoute
  '/api/public/ledger/entries': typeof ApiPublicLedgerEntriesRouteWithChildren
  '/api/public/ledger/stats': typeof ApiPublicLedgerStatsRoute
  '/api/public/pi-payments/approve': typeof ApiPublicPiPaymentsApproveRoute
  '/api/public/pi-payments/complete': typeof ApiPublicPiPaymentsCompleteRoute
  '/api/public/pi-payments/incomplete': typeof ApiPublicPiPaymentsIncompleteRoute
  '/api/public/ledger/entries/$id': typeof ApiPublicLedgerEntriesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/authpi': typeof AuthpiRoute
  '/testnet-reward': typeof TestnetRewardRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kyc': typeof AuthenticatedKycRoute
  '/_authenticated/ledger': typeof AuthenticatedLedgerRoute
  '/_authenticated/nfts': typeof AuthenticatedNftsRouteWithChildren
  '/_authenticated/ousd': typeof AuthenticatedOusdRoute
  '/_authenticated/receive': typeof AuthenticatedReceiveRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/_authenticated/send': typeof AuthenticatedSendRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/swap': typeof AuthenticatedSwapRoute
  '/_authenticated/tokens': typeof AuthenticatedTokensRouteWithChildren
  '/_authenticated/topup': typeof AuthenticatedTopupRoute
  '/admin/testnet-progress': typeof AdminTestnetProgressRoute
  '/_authenticated/admin/topup': typeof AuthenticatedAdminTopupRoute
  '/_authenticated/nfts/mint': typeof AuthenticatedNftsMintRoute
  '/_authenticated/tokens/create': typeof AuthenticatedTokensCreateRoute
  '/api/public/kyc-webhook': typeof ApiPublicKycWebhookRoute
  '/api/public/pi-a2u': typeof ApiPublicPiA2uRoute
  '/api/public/pi-auth': typeof ApiPublicPiAuthRoute
  '/auth/pi/callback': typeof AuthPiCallbackRoute
  '/api/public/ledger/entries': typeof ApiPublicLedgerEntriesRouteWithChildren
  '/api/public/ledger/stats': typeof ApiPublicLedgerStatsRoute
  '/api/public/pi-payments/approve': typeof ApiPublicPiPaymentsApproveRoute
  '/api/public/pi-payments/complete': typeof ApiPublicPiPaymentsCompleteRoute
  '/api/public/pi-payments/incomplete': typeof ApiPublicPiPaymentsIncompleteRoute
  '/api/public/ledger/entries/$id': typeof ApiPublicLedgerEntriesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/authpi'
    | '/testnet-reward'
    | '/activity'
    | '/dashboard'
    | '/kyc'
    | '/ledger'
    | '/nfts'
    | '/ousd'
    | '/receive'
    | '/scan'
    | '/send'
    | '/settings'
    | '/swap'
    | '/tokens'
    | '/topup'
    | '/admin/testnet-progress'
    | '/admin/topup'
    | '/nfts/mint'
    | '/tokens/create'
    | '/api/public/kyc-webhook'
    | '/api/public/pi-a2u'
    | '/api/public/pi-auth'
    | '/auth/pi/callback'
    | '/api/public/ledger/entries'
    | '/api/public/ledger/stats'
    | '/api/public/pi-payments/approve'
    | '/api/public/pi-payments/complete'
    | '/api/public/pi-payments/incomplete'
    | '/api/public/ledger/entries/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/authpi'
    | '/testnet-reward'
    | '/activity'
    | '/dashboard'
    | '/kyc'
    | '/ledger'
    | '/nfts'
    | '/ousd'
    | '/receive'
    | '/scan'
    | '/send'
    | '/settings'
    | '/swap'
    | '/tokens'
    | '/topup'
    | '/admin/testnet-progress'
    | '/admin/topup'
    | '/nfts/mint'
    | '/tokens/create'
    | '/api/public/kyc-webhook'
    | '/api/public/pi-a2u'
    | '/api/public/pi-auth'
    | '/auth/pi/callback'
    | '/api/public/ledger/entries'
    | '/api/public/ledger/stats'
    | '/api/public/pi-payments/approve'
    | '/api/public/pi-payments/complete'
    | '/api/public/pi-payments/incomplete'
    | '/api/public/ledger/entries/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/authpi'
    | '/testnet-reward'
    | '/_authenticated/activity'
    | '/_authenticated/dashboard'
    | '/_authenticated/kyc'
    | '/_authenticated/ledger'
    | '/_authenticated/nfts'
    | '/_authenticated/ousd'
    | '/_authenticated/receive'
    | '/_authenticated/scan'
    | '/_authenticated/send'
    | '/_authenticated/settings'
    | '/_authenticated/swap'
    | '/_authenticated/tokens'
    | '/_authenticated/topup'
    | '/admin/testnet-progress'
    | '/_authenticated/admin/topup'
    | '/_authenticated/nfts/mint'
    | '/_authenticated/tokens/create'
    | '/api/public/kyc-webhook'
    | '/api/public/pi-a2u'
    | '/api/public/pi-auth'
    | '/auth/pi/callback'
    | '/api/public/ledger/entries'
    | '/api/public/ledger/stats'
    | '/api/public/pi-payments/approve'
    | '/api/public/pi-payments/complete'
    | '/api/public/pi-payments/incomplete'
    | '/api/public/ledger/entries/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AuthpiRoute: typeof AuthpiRoute
  TestnetRewardRoute: typeof TestnetRewardRoute
  AdminTestnetProgressRoute: typeof AdminTestnetProgressRoute
  ApiPublicKycWebhookRoute: typeof ApiPublicKycWebhookRoute
  ApiPublicPiA2uRoute: typeof ApiPublicPiA2uRoute
  ApiPublicPiAuthRoute: typeof ApiPublicPiAuthRoute
  ApiPublicLedgerEntriesRoute: typeof ApiPublicLedgerEntriesRouteWithChildren
  ApiPublicLedgerStatsRoute: typeof ApiPublicLedgerStatsRoute
  ApiPublicPiPaymentsApproveRoute: typeof ApiPublicPiPaymentsApproveRoute
  ApiPublicPiPaymentsCompleteRoute: typeof ApiPublicPiPaymentsCompleteRoute
  ApiPublicPiPaymentsIncompleteRoute: typeof ApiPublicPiPaymentsIncompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authpi': {
      id: '/authpi'
      path: '/authpi'
      fullPath: '/authpi'
      preLoaderRoute: typeof AuthpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testnet-reward': {
      id: '/testnet-reward'
      path: '/testnet-reward'
      fullPath: '/testnet-reward'
      preLoaderRoute: typeof TestnetRewardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kyc': {
      id: '/_authenticated/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AuthenticatedKycRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ledger': {
      id: '/_authenticated/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AuthenticatedLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nfts': {
      id: '/_authenticated/nfts'
      path: '/nfts'
      fullPath: '/nfts'
      preLoaderRoute: typeof AuthenticatedNftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ousd': {
      id: '/_authenticated/ousd'
      path: '/ousd'
      fullPath: '/ousd'
      preLoaderRoute: typeof AuthenticatedOusdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receive': {
      id: '/_authenticated/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof AuthenticatedReceiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/send': {
      id: '/_authenticated/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AuthenticatedSendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/swap': {
      id: '/_authenticated/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof AuthenticatedSwapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tokens': {
      id: '/_authenticated/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof AuthenticatedTokensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/topup': {
      id: '/_authenticated/topup'
      path: '/topup'
      fullPath: '/topup'
      preLoaderRoute: typeof AuthenticatedTopupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/testnet-progress': {
      id: '/admin/testnet-progress'
      path: '/admin/testnet-progress'
      fullPath: '/admin/testnet-progress'
      preLoaderRoute: typeof AdminTestnetProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/topup': {
      id: '/_authenticated/admin/topup'
      path: '/admin/topup'
      fullPath: '/admin/topup'
      preLoaderRoute: typeof AuthenticatedAdminTopupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nfts/mint': {
      id: '/_authenticated/nfts/mint'
      path: '/mint'
      fullPath: '/nfts/mint'
      preLoaderRoute: typeof AuthenticatedNftsMintRouteImport
      parentRoute: typeof AuthenticatedNftsRoute
    }
    '/_authenticated/tokens/create': {
      id: '/_authenticated/tokens/create'
      path: '/create'
      fullPath: '/tokens/create'
      preLoaderRoute: typeof AuthenticatedTokensCreateRouteImport
      parentRoute: typeof AuthenticatedTokensRoute
    }
    '/api/public/kyc-webhook': {
      id: '/api/public/kyc-webhook'
      path: '/api/public/kyc-webhook'
      fullPath: '/api/public/kyc-webhook'
      preLoaderRoute: typeof ApiPublicKycWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-a2u': {
      id: '/api/public/pi-a2u'
      path: '/api/public/pi-a2u'
      fullPath: '/api/public/pi-a2u'
      preLoaderRoute: typeof ApiPublicPiA2uRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-auth': {
      id: '/api/public/pi-auth'
      path: '/api/public/pi-auth'
      fullPath: '/api/public/pi-auth'
      preLoaderRoute: typeof ApiPublicPiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/pi/callback': {
      id: '/auth/pi/callback'
      path: '/pi/callback'
      fullPath: '/auth/pi/callback'
      preLoaderRoute: typeof AuthPiCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/public/ledger/entries': {
      id: '/api/public/ledger/entries'
      path: '/api/public/ledger/entries'
      fullPath: '/api/public/ledger/entries'
      preLoaderRoute: typeof ApiPublicLedgerEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ledger/stats': {
      id: '/api/public/ledger/stats'
      path: '/api/public/ledger/stats'
      fullPath: '/api/public/ledger/stats'
      preLoaderRoute: typeof ApiPublicLedgerStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-payments/approve': {
      id: '/api/public/pi-payments/approve'
      path: '/api/public/pi-payments/approve'
      fullPath: '/api/public/pi-payments/approve'
      preLoaderRoute: typeof ApiPublicPiPaymentsApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-payments/complete': {
      id: '/api/public/pi-payments/complete'
      path: '/api/public/pi-payments/complete'
      fullPath: '/api/public/pi-payments/complete'
      preLoaderRoute: typeof ApiPublicPiPaymentsCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-payments/incomplete': {
      id: '/api/public/pi-payments/incomplete'
      path: '/api/public/pi-payments/incomplete'
      fullPath: '/api/public/pi-payments/incomplete'
      preLoaderRoute: typeof ApiPublicPiPaymentsIncompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ledger/entries/$id': {
      id: '/api/public/ledger/entries/$id'
      path: '/$id'
      fullPath: '/api/public/ledger/entries/$id'
      preLoaderRoute: typeof ApiPublicLedgerEntriesIdRouteImport
      parentRoute: typeof ApiPublicLedgerEntriesRoute
    }
  }
}

interface AuthenticatedNftsRouteChildren {
  AuthenticatedNftsMintRoute: typeof AuthenticatedNftsMintRoute
}

const AuthenticatedNftsRouteChildren: AuthenticatedNftsRouteChildren = {
  AuthenticatedNftsMintRoute: AuthenticatedNftsMintRoute,
}

const AuthenticatedNftsRouteWithChildren =
  AuthenticatedNftsRoute._addFileChildren(AuthenticatedNftsRouteChildren)

interface AuthenticatedTokensRouteChildren {
  AuthenticatedTokensCreateRoute: typeof AuthenticatedTokensCreateRoute
}

const AuthenticatedTokensRouteChildren: AuthenticatedTokensRouteChildren = {
  AuthenticatedTokensCreateRoute: AuthenticatedTokensCreateRoute,
}

const AuthenticatedTokensRouteWithChildren =
  AuthenticatedTokensRoute._addFileChildren(AuthenticatedTokensRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKycRoute: typeof AuthenticatedKycRoute
  AuthenticatedLedgerRoute: typeof AuthenticatedLedgerRoute
  AuthenticatedNftsRoute: typeof AuthenticatedNftsRouteWithChildren
  AuthenticatedOusdRoute: typeof AuthenticatedOusdRoute
  AuthenticatedReceiveRoute: typeof AuthenticatedReceiveRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedSendRoute: typeof AuthenticatedSendRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSwapRoute: typeof AuthenticatedSwapRoute
  AuthenticatedTokensRoute: typeof AuthenticatedTokensRouteWithChildren
  AuthenticatedTopupRoute: typeof AuthenticatedTopupRoute
  AuthenticatedAdminTopupRoute: typeof AuthenticatedAdminTopupRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKycRoute: AuthenticatedKycRoute,
  AuthenticatedLedgerRoute: AuthenticatedLedgerRoute,
  AuthenticatedNftsRoute: AuthenticatedNftsRouteWithChildren,
  AuthenticatedOusdRoute: AuthenticatedOusdRoute,
  AuthenticatedReceiveRoute: AuthenticatedReceiveRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedSendRoute: AuthenticatedSendRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSwapRoute: AuthenticatedSwapRoute,
  AuthenticatedTokensRoute: AuthenticatedTokensRouteWithChildren,
  AuthenticatedTopupRoute: AuthenticatedTopupRoute,
  AuthenticatedAdminTopupRoute: AuthenticatedAdminTopupRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthPiCallbackRoute: typeof AuthPiCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthPiCallbackRoute: AuthPiCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ApiPublicLedgerEntriesRouteChildren {
  ApiPublicLedgerEntriesIdRoute: typeof ApiPublicLedgerEntriesIdRoute
}

const ApiPublicLedgerEntriesRouteChildren: ApiPublicLedgerEntriesRouteChildren =
  {
    ApiPublicLedgerEntriesIdRoute: ApiPublicLedgerEntriesIdRoute,
  }

const ApiPublicLedgerEntriesRouteWithChildren =
  ApiPublicLedgerEntriesRoute._addFileChildren(
    ApiPublicLedgerEntriesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AuthpiRoute: AuthpiRoute,
  TestnetRewardRoute: TestnetRewardRoute,
  AdminTestnetProgressRoute: AdminTestnetProgressRoute,
  ApiPublicKycWebhookRoute: ApiPublicKycWebhookRoute,
  ApiPublicPiA2uRoute: ApiPublicPiA2uRoute,
  ApiPublicPiAuthRoute: ApiPublicPiAuthRoute,
  ApiPublicLedgerEntriesRoute: ApiPublicLedgerEntriesRouteWithChildren,
  ApiPublicLedgerStatsRoute: ApiPublicLedgerStatsRoute,
  ApiPublicPiPaymentsApproveRoute: ApiPublicPiPaymentsApproveRoute,
  ApiPublicPiPaymentsCompleteRoute: ApiPublicPiPaymentsCompleteRoute,
  ApiPublicPiPaymentsIncompleteRoute: ApiPublicPiPaymentsIncompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
